In [27]:
import pandas as pd
from database_connection import engine

# 2007

In [28]:
# Import csv into pandas dataframe
data_2007 = pd.read_csv("Resources/2007-PIT-Counts-by-State.csv")
data_2007_df = pd.DataFrame(data_2007)
data_2007_df.head()

,State,Number of CoCs,"Overall Homeless, 2007","Sheltered ES Homeless, 2007","Sheltered TH Homeless, 2007","Sheltered Total Homeless, 2007","Unsheltered Homeless, 2007","Overall Homeless Individuals, 2007","Sheltered ES Homeless Individuals, 2007","Sheltered TH Homeless Individuals, 2007",...,"Sheltered ES Homeless Family Households, 2007","Sheltered TH Homeless Family Households, 2007","Sheltered Total Homeless Family Households, 2007","Unsheltered Homeless Family Households, 2007","Overall Chronically Homeless Individuals, 2007","Sheltered Total Chronically Homeless Individuals, 2007","Unsheltered Chronically Homeless Individuals, 2007","Overall Homeless Veterans, 2007","Sheltered Total Homeless Veterans, 2007","Unsheltered Homeless Veterans, 2007"
0,AK,2.0,"1,642",898,489,"1,387",255,"1,062",618,273,...,95,70,165,25,278,221,57,203,152,51
1,AL,8.0,"5,452","1,452","2,344","3,796","1,656","4,184","1,210","1,613",...,96,251,347,119,993,483,510,974,745,229
2,AR,9.0,"3,836","1,251","1,034","2,285","1,551","2,987",985,781,...,97,87,184,140,852,409,443,287,255,32
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,"14,646","3,934","4,684","8,618","6,028","10,020","2,412","2,011",...,463,828,"1,291",168,"2,804",650,"2,154",869,858,11

In [29]:
# Create column for the year and set to 2007
data_2007_df["Year"] = 2007
data_2007_df.head()

,State,Number of CoCs,"Overall Homeless, 2007","Sheltered ES Homeless, 2007","Sheltered TH Homeless, 2007","Sheltered Total Homeless, 2007","Unsheltered Homeless, 2007","Overall Homeless Individuals, 2007","Sheltered ES Homeless Individuals, 2007","Sheltered TH Homeless Individuals, 2007",...,"Sheltered TH Homeless Family Households, 2007","Sheltered Total Homeless Family Households, 2007","Unsheltered Homeless Family Households, 2007","Overall Chronically Homeless Individuals, 2007","Sheltered Total Chronically Homeless Individuals, 2007","Unsheltered Chronically Homeless Individuals, 2007","Overall Homeless Veterans, 2007","Sheltered Total Homeless Veterans, 2007","Unsheltered Homeless Veterans, 2007",Year
0,AK,2.0,"1,642",898,489,"1,387",255,"1,062",618,273,...,70,165,25,278,221,57,203,152,51,2007
1,AL,8.0,"5,452","1,452","2,344","3,796","1,656","4,184","1,210","1,613",...,251,347,119,993,483,510,974,745,229,2007
2,AR,9.0,"3,836","1,251","1,034","2,285","1,551","2,987",985,781,...,87,184,140,852,409,443,287,255,32,2007
3,AS,0.0,,,,,,,,,...,,,,,,,,,,2007
4,AZ,3.0,"14,646","3,934","4,684","8,618","6,028","10,020","2,412","2,011",...,828,"1,291",168,"2,804",650,"2,154",869,858,11,2007

In [30]:
# Get Column Names
cols = data_2007_df.columns.tolist()
cols

['State',
 'Number of CoCs',
 'Overall Homeless, 2007',
 'Sheltered ES Homeless, 2007',
 'Sheltered TH Homeless, 2007',
 'Sheltered Total Homeless, 2007',
 'Unsheltered Homeless, 2007',
 'Overall Homeless Individuals, 2007',
 'Sheltered ES Homeless Individuals, 2007',
 'Sheltered TH Homeless Individuals, 2007',
 'Sheltered Total Homeless Individuals, 2007',
 'Unsheltered Homeless Individuals, 2007',
 'Overall Homeless People in Families, 2007',
 'Sheltered ES Homeless People in Families, 2007',
 'Sheltered TH Homeless People in Families, 2007',
 'Sheltered Total Homeless People in Families, 2007',
 'Unsheltered Homeless People in Families, 2007',
 'Overall Homeless Family Households, 2007',
 'Sheltered ES Homeless Family Households, 2007',
 'Sheltered TH Homeless Family Households, 2007',
 'Sheltered Total Homeless Family Households, 2007',
 'Unsheltered Homeless Family Households, 2007',
 'Overall Chronically Homeless Individuals, 2007',
 'Sheltered Total Chronically Homeless Individuals, 2007',
 'Unsheltered Chronically Homeless Individuals, 2007',
 'Overall Homeless Veterans, 2007',
 'Sheltered Total Homeless Veterans, 2007',
 'Unsheltered Homeless Veterans, 2007',
 'Year']

In [31]:
# Rearrange column names so year is second
new_cols = ['State', 'Year',
 'Number of CoCs',
 'Overall Homeless, 2007',
 'Sheltered ES Homeless, 2007',
 'Sheltered TH Homeless, 2007',
 'Sheltered Total Homeless, 2007',
 'Unsheltered Homeless, 2007',
 'Overall Homeless Individuals, 2007',
 'Sheltered ES Homeless Individuals, 2007',
 'Sheltered TH Homeless Individuals, 2007',
 'Sheltered Total Homeless Individuals, 2007',
 'Unsheltered Homeless Individuals, 2007',
 'Overall Homeless People in Families, 2007',
 'Sheltered ES Homeless People in Families, 2007',
 'Sheltered TH Homeless People in Families, 2007',
 'Sheltered Total Homeless People in Families, 2007',
 'Unsheltered Homeless People in Families, 2007',
 'Overall Homeless Family Households, 2007',
 'Sheltered ES Homeless Family Households, 2007',
 'Sheltered TH Homeless Family Households, 2007',
 'Sheltered Total Homeless Family Households, 2007',
 'Unsheltered Homeless Family Households, 2007',
 'Overall Chronically Homeless Individuals, 2007',
 'Sheltered Total Chronically Homeless Individuals, 2007',
 'Unsheltered Chronically Homeless Individuals, 2007',
 'Overall Homeless Veterans, 2007',
 'Sheltered Total Homeless Veterans, 2007',
 'Unsheltered Homeless Veterans, 2007'
 ]

In [32]:
# Apply rearranged column names
data_2007_df = data_2007_df[new_cols]
data_2007_df.head()

,State,Year,Number of CoCs,"Overall Homeless, 2007","Sheltered ES Homeless, 2007","Sheltered TH Homeless, 2007","Sheltered Total Homeless, 2007","Unsheltered Homeless, 2007","Overall Homeless Individuals, 2007","Sheltered ES Homeless Individuals, 2007",...,"Sheltered ES Homeless Family Households, 2007","Sheltered TH Homeless Family Households, 2007","Sheltered Total Homeless Family Households, 2007","Unsheltered Homeless Family Households, 2007","Overall Chronically Homeless Individuals, 2007","Sheltered Total Chronically Homeless Individuals, 2007","Unsheltered Chronically Homeless Individuals, 2007","Overall Homeless Veterans, 2007","Sheltered Total Homeless Veterans, 2007","Unsheltered Homeless Veterans, 2007"
0,AK,2007,2.0,"1,642",898,489,"1,387",255,"1,062",618,...,95,70,165,25,278,221,57,203,152,51
1,AL,2007,8.0,"5,452","1,452","2,344","3,796","1,656","4,184","1,210",...,96,251,347,119,993,483,510,974,745,229
2,AR,2007,9.0,"3,836","1,251","1,034","2,285","1,551","2,987",985,...,97,87,184,140,852,409,443,287,255,32
3,AS,2007,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2007,3.0,"14,646","3,934","4,684","8,618","6,028","10,020","2,412",...,463,828,"1,291",168,"2,804",650,"2,154",869,858,11

In [33]:
# rename columns to remove year from each column title
dict = {
 'Overall Homeless, 2007':'Overall Homeless',
 'Sheltered ES Homeless, 2007':'Sheltered ES Homeless',
 'Sheltered TH Homeless, 2007':'Sheltered TH Homeless',
 'Sheltered Total Homeless, 2007':'Sheltered Total Homeless',
 'Unsheltered Homeless, 2007':'Unsheltered Homeless',
 'Overall Homeless Individuals, 2007':'Overall Homeless Individuals',
 'Sheltered ES Homeless Individuals, 2007':'Sheltered ES Homeless Individuals',
 'Sheltered TH Homeless Individuals, 2007':'Sheltered TH Homeless Individuals',
 'Sheltered Total Homeless Individuals, 2007':'Sheltered Total Homeless Individuals',
 'Unsheltered Homeless Individuals, 2007':'Unsheltered Homeless Individuals',
 'Overall Homeless People in Families, 2007':'Overall Homeless People in Families',
 'Sheltered ES Homeless People in Families, 2007':'Sheltered ES Homeless People in Families',
 'Sheltered TH Homeless People in Families, 2007':'Sheltered TH Homeless People in Families',
 'Sheltered Total Homeless People in Families, 2007':'Sheltered Total Homeless People in Families',
 'Unsheltered Homeless People in Families, 2007':'Unsheltered Homeless People in Families',
 'Overall Homeless Family Households, 2007':'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households, 2007':'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households, 2007':'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households, 2007':'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households, 2007':'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless Individuals, 2007':'Overall Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals, 2007':'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals, 2007':'Unsheltered Chronically Homeless Individuals',
 'Overall Homeless Veterans, 2007':'Overall Homeless Veterans',
 'Sheltered Total Homeless Veterans, 2007':'Sheltered Total Homeless Veterans',
 'Unsheltered Homeless Veterans, 2007':'Unsheltered Homeless Veterans'
       }
data_2007_df.rename(columns=dict, inplace=True)

In [34]:
# Export df to sql table
data_2007_df.to_sql(name='data_2007', con=engine, if_exists='replace')

# 2008

In [35]:
# Import csv into pandas dataframe 2008
data_2008 = pd.read_csv("Resources/2008-PIT-Counts-by-State.csv")
data_2008_df = pd.DataFrame(data_2008)
data_2008_df.head()

,State,Number of CoCs,"Overall Homeless, 2008","Sheltered ES Homeless, 2008","Sheltered TH Homeless, 2008","Sheltered Total Homeless, 2008","Unsheltered Homeless, 2008","Overall Homeless Individuals, 2008","Sheltered ES Homeless Individuals, 2008","Sheltered TH Homeless Individuals, 2008",...,"Sheltered ES Homeless Family Households, 2008","Sheltered TH Homeless Family Households, 2008","Sheltered Total Homeless Family Households, 2008","Unsheltered Homeless Family Households, 2008","Overall Chronically Homeless Individuals, 2008","Sheltered Total Chronically Homeless Individuals, 2008","Unsheltered Chronically Homeless Individuals, 2008","Overall Homeless Veterans, 2008","Sheltered Total Homeless Veterans, 2008","Unsheltered Homeless Veterans, 2008"
0,AK,2.0,"1,646",847,605,"1,452",194,"1,067",557,355,...,83,75,158,14,439,355,84,218,189,29
1,AL,8.0,"5,387","1,534","2,309","3,843","1,544","4,086","1,159","1,644",...,131,245,376,107,"1,052",579,473,801,677,124
2,AR,6.0,"3,255","1,048",972,"2,020","1,235","2,625",860,757,...,76,81,157,128,893,492,401,235,219,16
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,"12,488","3,104","3,866","6,970","5,518","8,428","1,782","1,594",...,404,681,"1,085",192,"3,097","1,223","1,874",736,736,0

In [36]:
# Create column for the year and set to 2008
data_2008_df["Year"] = 2008
data_2008_df.head()

,State,Number of CoCs,"Overall Homeless, 2008","Sheltered ES Homeless, 2008","Sheltered TH Homeless, 2008","Sheltered Total Homeless, 2008","Unsheltered Homeless, 2008","Overall Homeless Individuals, 2008","Sheltered ES Homeless Individuals, 2008","Sheltered TH Homeless Individuals, 2008",...,"Sheltered TH Homeless Family Households, 2008","Sheltered Total Homeless Family Households, 2008","Unsheltered Homeless Family Households, 2008","Overall Chronically Homeless Individuals, 2008","Sheltered Total Chronically Homeless Individuals, 2008","Unsheltered Chronically Homeless Individuals, 2008","Overall Homeless Veterans, 2008","Sheltered Total Homeless Veterans, 2008","Unsheltered Homeless Veterans, 2008",Year
0,AK,2.0,"1,646",847,605,"1,452",194,"1,067",557,355,...,75,158,14,439,355,84,218,189,29,2008
1,AL,8.0,"5,387","1,534","2,309","3,843","1,544","4,086","1,159","1,644",...,245,376,107,"1,052",579,473,801,677,124,2008
2,AR,6.0,"3,255","1,048",972,"2,020","1,235","2,625",860,757,...,81,157,128,893,492,401,235,219,16,2008
3,AS,0.0,,,,,,,,,...,,,,,,,,,,2008
4,AZ,3.0,"12,488","3,104","3,866","6,970","5,518","8,428","1,782","1,594",...,681,"1,085",192,"3,097","1,223","1,874",736,736,0,2008

In [37]:
# Get Column Names
cols_2008 = data_2008_df.columns.tolist()
cols_2008

['State',
 'Number of CoCs',
 'Overall Homeless, 2008',
 'Sheltered ES Homeless, 2008',
 'Sheltered TH Homeless, 2008',
 'Sheltered Total Homeless, 2008',
 'Unsheltered Homeless, 2008',
 'Overall Homeless Individuals, 2008',
 'Sheltered ES Homeless Individuals, 2008',
 'Sheltered TH Homeless Individuals, 2008',
 'Sheltered Total Homeless Individuals, 2008',
 'Unsheltered Homeless Individuals, 2008',
 'Overall Homeless People in Families, 2008',
 'Sheltered ES Homeless People in Families, 2008',
 'Sheltered TH Homeless People in Families, 2008',
 'Sheltered Total Homeless People in Families, 2008',
 'Unsheltered Homeless People in Families, 2008',
 'Overall Homeless Family Households, 2008',
 'Sheltered ES Homeless Family Households, 2008',
 'Sheltered TH Homeless Family Households, 2008',
 'Sheltered Total Homeless Family Households, 2008',
 'Unsheltered Homeless Family Households, 2008',
 'Overall Chronically Homeless Individuals, 2008',
 'Sheltered Total Chronically Homeless Individuals, 2008',
 'Unsheltered Chronically Homeless Individuals, 2008',
 'Overall Homeless Veterans, 2008',
 'Sheltered Total Homeless Veterans, 2008',
 'Unsheltered Homeless Veterans, 2008',
 'Year']

In [39]:
# Rearrange column names so year is second
new_cols_2008 = ['State',
 'Year',
 'Number of CoCs',
 'Overall Homeless, 2008',
 'Sheltered ES Homeless, 2008',
 'Sheltered TH Homeless, 2008',
 'Sheltered Total Homeless, 2008',
 'Unsheltered Homeless, 2008',
 'Overall Homeless Individuals, 2008',
 'Sheltered ES Homeless Individuals, 2008',
 'Sheltered TH Homeless Individuals, 2008',
 'Sheltered Total Homeless Individuals, 2008',
 'Unsheltered Homeless Individuals, 2008',
 'Overall Homeless People in Families, 2008',
 'Sheltered ES Homeless People in Families, 2008',
 'Sheltered TH Homeless People in Families, 2008',
 'Sheltered Total Homeless People in Families, 2008',
 'Unsheltered Homeless People in Families, 2008',
 'Overall Homeless Family Households, 2008',
 'Sheltered ES Homeless Family Households, 2008',
 'Sheltered TH Homeless Family Households, 2008',
 'Sheltered Total Homeless Family Households, 2008',
 'Unsheltered Homeless Family Households, 2008',
 'Overall Chronically Homeless Individuals, 2008',
 'Sheltered Total Chronically Homeless Individuals, 2008',
 'Unsheltered Chronically Homeless Individuals, 2008',
 'Overall Homeless Veterans, 2008',
 'Sheltered Total Homeless Veterans, 2008',
 'Unsheltered Homeless Veterans, 2008'
 ]

In [40]:
# Apply rearranged column names
data_2008_df = data_2008_df[new_cols_2008]
data_2008_df.head()

,State,Year,Number of CoCs,"Overall Homeless, 2008","Sheltered ES Homeless, 2008","Sheltered TH Homeless, 2008","Sheltered Total Homeless, 2008","Unsheltered Homeless, 2008","Overall Homeless Individuals, 2008","Sheltered ES Homeless Individuals, 2008",...,"Sheltered ES Homeless Family Households, 2008","Sheltered TH Homeless Family Households, 2008","Sheltered Total Homeless Family Households, 2008","Unsheltered Homeless Family Households, 2008","Overall Chronically Homeless Individuals, 2008","Sheltered Total Chronically Homeless Individuals, 2008","Unsheltered Chronically Homeless Individuals, 2008","Overall Homeless Veterans, 2008","Sheltered Total Homeless Veterans, 2008","Unsheltered Homeless Veterans, 2008"
0,AK,2008,2.0,"1,646",847,605,"1,452",194,"1,067",557,...,83,75,158,14,439,355,84,218,189,29
1,AL,2008,8.0,"5,387","1,534","2,309","3,843","1,544","4,086","1,159",...,131,245,376,107,"1,052",579,473,801,677,124
2,AR,2008,6.0,"3,255","1,048",972,"2,020","1,235","2,625",860,...,76,81,157,128,893,492,401,235,219,16
3,AS,2008,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2008,3.0,"12,488","3,104","3,866","6,970","5,518","8,428","1,782",...,404,681,"1,085",192,"3,097","1,223","1,874",736,736,0

In [43]:
# rename columns to remove year from each column title
dict = {
 'Overall Homeless, 2008':'Overall Homeless',
 'Sheltered ES Homeless, 2008':'Sheltered ES Homeless',
 'Sheltered TH Homeless, 2008':'Sheltered TH Homeless',
 'Sheltered Total Homeless, 2008':'Sheltered Total Homeless',
 'Unsheltered Homeless, 2008':'Unsheltered Homeless',
 'Overall Homeless Individuals, 2008':'Overall Homeless Individuals',
 'Sheltered ES Homeless Individuals, 2008':'Sheltered ES Homeless Individuals',
 'Sheltered TH Homeless Individuals, 2008':'Sheltered TH Homeless Individuals',
 'Sheltered Total Homeless Individuals, 2008':'Sheltered Total Homeless Individuals',
 'Unsheltered Homeless Individuals, 2008':'Unsheltered Homeless Individuals',
 'Overall Homeless People in Families, 2008':'Overall Homeless People in Families',
 'Sheltered ES Homeless People in Families, 2008':'Sheltered ES Homeless People in Families',
 'Sheltered TH Homeless People in Families, 2008':'Sheltered TH Homeless People in Families',
 'Sheltered Total Homeless People in Families, 2008':'Sheltered Total Homeless People in Families',
 'Unsheltered Homeless People in Families, 2008':'Unsheltered Homeless People in Families',
 'Overall Homeless Family Households, 2008':'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households, 2008':'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households, 2008':'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households, 2008':'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households, 2008':'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless Individuals, 2008':'Overall Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals, 2008':'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals, 2008':'Unsheltered Chronically Homeless Individuals',
 'Overall Homeless Veterans, 2008':'Overall Homeless Veterans',
 'Sheltered Total Homeless Veterans, 2008':'Sheltered Total Homeless Veterans',
 'Unsheltered Homeless Veterans, 2008':'Unsheltered Homeless Veterans'
       }
data_2008_df.rename(columns=dict, inplace=True)

In [44]:
# Export df to sql table
data_2008_df.to_sql(name='data_2008', con=engine, if_exists='replace')

# 2009

In [45]:
# Import csv into pandas dataframe 2008
data_2009 = pd.read_csv("Resources/2009-PIT-Counts-by-State.csv")
data_2009_df = pd.DataFrame(data_2009)
data_2009_df.head()

,State,Number of CoCs,"Overall Homeless, 2009","Sheltered ES Homeless, 2009","Sheltered TH Homeless, 2009","Sheltered Total Homeless, 2009","Unsheltered Homeless, 2009","Overall Homeless Individuals, 2009","Sheltered ES Homeless Individuals, 2009","Sheltered TH Homeless Individuals, 2009",...,"Sheltered TH Homeless Family Households, 2009","Sheltered Total Homeless Family Households, 2009","Unsheltered Homeless Family Households, 2009","Overall Chronically Homeless Individuals, 2009","Sheltered ES Chronically Homeless Individuals, 2009","Sheltered Total Chronically Homeless Individuals, 2009","Unsheltered Chronically Homeless Individuals, 2009","Overall Homeless Veterans, 2009","Sheltered Total Homeless Veterans, 2009","Unsheltered Homeless Veterans, 2009"
0,AK,2.0,"1,992","1,009",656,"1,665",327,"1,239",626,363,...,92,210,27,323,245,245,78,259,222,37
1,AL,8.0,"6,080","1,419","2,494","3,913","2,167","4,686","1,104","1,927",...,201,313,196,"1,189",652,652,537,"1,063",858,205
2,AR,6.0,"2,852",652,"1,078","1,730","1,122","2,181",499,798,...,85,143,91,406,146,146,260,249,168,82
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,"14,721","4,020","4,346","8,366","6,355","9,959","2,452","1,839",...,773,"1,251",155,"2,229",538,538,"1,691","2,343","1,216","1,127"

In [46]:
# Create column for the year and set to 2009
data_2009_df["Year"] = 2009
data_2009_df.head()

,State,Number of CoCs,"Overall Homeless, 2009","Sheltered ES Homeless, 2009","Sheltered TH Homeless, 2009","Sheltered Total Homeless, 2009","Unsheltered Homeless, 2009","Overall Homeless Individuals, 2009","Sheltered ES Homeless Individuals, 2009","Sheltered TH Homeless Individuals, 2009",...,"Sheltered Total Homeless Family Households, 2009","Unsheltered Homeless Family Households, 2009","Overall Chronically Homeless Individuals, 2009","Sheltered ES Chronically Homeless Individuals, 2009","Sheltered Total Chronically Homeless Individuals, 2009","Unsheltered Chronically Homeless Individuals, 2009","Overall Homeless Veterans, 2009","Sheltered Total Homeless Veterans, 2009","Unsheltered Homeless Veterans, 2009",Year
0,AK,2.0,"1,992","1,009",656,"1,665",327,"1,239",626,363,...,210,27,323,245,245,78,259,222,37,2009
1,AL,8.0,"6,080","1,419","2,494","3,913","2,167","4,686","1,104","1,927",...,313,196,"1,189",652,652,537,"1,063",858,205,2009
2,AR,6.0,"2,852",652,"1,078","1,730","1,122","2,181",499,798,...,143,91,406,146,146,260,249,168,82,2009
3,AS,0.0,,,,,,,,,...,,,,,,,,,,2009
4,AZ,3.0,"14,721","4,020","4,346","8,366","6,355","9,959","2,452","1,839",...,"1,251",155,"2,229",538,538,"1,691","2,343","1,216","1,127",2009

In [47]:
# Get Column Names
cols_2009 = data_2009_df.columns.tolist()
cols_2009

['State',
 'Number of CoCs',
 'Overall Homeless, 2009',
 'Sheltered ES Homeless, 2009',
 'Sheltered TH Homeless, 2009',
 'Sheltered Total Homeless, 2009',
 'Unsheltered Homeless, 2009',
 'Overall Homeless Individuals, 2009',
 'Sheltered ES Homeless Individuals, 2009',
 'Sheltered TH Homeless Individuals, 2009',
 'Sheltered Total Homeless Individuals, 2009',
 'Unsheltered Homeless Individuals, 2009',
 'Overall Homeless People in Families, 2009',
 'Sheltered ES Homeless People in Families, 2009',
 'Sheltered TH Homeless People in Families, 2009',
 'Sheltered Total Homeless People in Families, 2009',
 'Unsheltered Homeless People in Families, 2009',
 'Overall Homeless Family Households, 2009',
 'Sheltered ES Homeless Family Households, 2009',
 'Sheltered TH Homeless Family Households, 2009',
 'Sheltered Total Homeless Family Households, 2009',
 'Unsheltered Homeless Family Households, 2009',
 'Overall Chronically Homeless Individuals, 2009',
 'Sheltered ES Chronically Homeless Individuals, 2009',
 'Sheltered Total Chronically Homeless Individuals, 2009',
 'Unsheltered Chronically Homeless Individuals, 2009',
 'Overall Homeless Veterans, 2009',
 'Sheltered Total Homeless Veterans, 2009',
 'Unsheltered Homeless Veterans, 2009',
 'Year']

In [48]:
# Rearrange column names so year is second
new_cols_2009 = ['State','Year',
 'Number of CoCs',
 'Overall Homeless, 2009',
 'Sheltered ES Homeless, 2009',
 'Sheltered TH Homeless, 2009',
 'Sheltered Total Homeless, 2009',
 'Unsheltered Homeless, 2009',
 'Overall Homeless Individuals, 2009',
 'Sheltered ES Homeless Individuals, 2009',
 'Sheltered TH Homeless Individuals, 2009',
 'Sheltered Total Homeless Individuals, 2009',
 'Unsheltered Homeless Individuals, 2009',
 'Overall Homeless People in Families, 2009',
 'Sheltered ES Homeless People in Families, 2009',
 'Sheltered TH Homeless People in Families, 2009',
 'Sheltered Total Homeless People in Families, 2009',
 'Unsheltered Homeless People in Families, 2009',
 'Overall Homeless Family Households, 2009',
 'Sheltered ES Homeless Family Households, 2009',
 'Sheltered TH Homeless Family Households, 2009',
 'Sheltered Total Homeless Family Households, 2009',
 'Unsheltered Homeless Family Households, 2009',
 'Overall Chronically Homeless Individuals, 2009',
 'Sheltered ES Chronically Homeless Individuals, 2009',
 'Sheltered Total Chronically Homeless Individuals, 2009',
 'Unsheltered Chronically Homeless Individuals, 2009',
 'Overall Homeless Veterans, 2009',
 'Sheltered Total Homeless Veterans, 2009',
 'Unsheltered Homeless Veterans, 2009'
 ]

In [49]:
# Apply rearranged column names
data_2009_df = data_2009_df[new_cols_2009]
data_2009_df.head()

,State,Year,Number of CoCs,"Overall Homeless, 2009","Sheltered ES Homeless, 2009","Sheltered TH Homeless, 2009","Sheltered Total Homeless, 2009","Unsheltered Homeless, 2009","Overall Homeless Individuals, 2009","Sheltered ES Homeless Individuals, 2009",...,"Sheltered TH Homeless Family Households, 2009","Sheltered Total Homeless Family Households, 2009","Unsheltered Homeless Family Households, 2009","Overall Chronically Homeless Individuals, 2009","Sheltered ES Chronically Homeless Individuals, 2009","Sheltered Total Chronically Homeless Individuals, 2009","Unsheltered Chronically Homeless Individuals, 2009","Overall Homeless Veterans, 2009","Sheltered Total Homeless Veterans, 2009","Unsheltered Homeless Veterans, 2009"
0,AK,2009,2.0,"1,992","1,009",656,"1,665",327,"1,239",626,...,92,210,27,323,245,245,78,259,222,37
1,AL,2009,8.0,"6,080","1,419","2,494","3,913","2,167","4,686","1,104",...,201,313,196,"1,189",652,652,537,"1,063",858,205
2,AR,2009,6.0,"2,852",652,"1,078","1,730","1,122","2,181",499,...,85,143,91,406,146,146,260,249,168,82
3,AS,2009,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2009,3.0,"14,721","4,020","4,346","8,366","6,355","9,959","2,452",...,773,"1,251",155,"2,229",538,538,"1,691","2,343","1,216","1,127"

In [50]:
# rename columns to remove year from each column title
dict = {
 'Overall Homeless, 2009':'Overall Homeless',
 'Sheltered ES Homeless, 2009':'Sheltered ES Homeless',
 'Sheltered TH Homeless, 2009':'Sheltered TH Homeless',
 'Sheltered Total Homeless, 2009':'Sheltered Total Homeless',
 'Unsheltered Homeless, 2009':'Unsheltered Homeless',
 'Overall Homeless Individuals, 2009':'Overall Homeless Individuals',
 'Sheltered ES Homeless Individuals, 2009':'Sheltered ES Homeless Individuals',
 'Sheltered TH Homeless Individuals, 2009':'Sheltered TH Homeless Individuals',
 'Sheltered Total Homeless Individuals, 2009':'Sheltered Total Homeless Individuals',
 'Unsheltered Homeless Individuals, 2009':'Unsheltered Homeless Individuals',
 'Overall Homeless People in Families, 2009':'Overall Homeless People in Families',
 'Sheltered ES Homeless People in Families, 2009':'Sheltered ES Homeless People in Families',
 'Sheltered TH Homeless People in Families, 2009':'Sheltered TH Homeless People in Families',
 'Sheltered Total Homeless People in Families, 2009':'Sheltered Total Homeless People in Families',
 'Unsheltered Homeless People in Families, 2009':'Unsheltered Homeless People in Families',
 'Overall Homeless Family Households, 2009':'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households, 2009':'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households, 2009':'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households, 2009':'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households, 2009':'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless Individuals, 2009':'Overall Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals, 2009':'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals, 2009':'Unsheltered Chronically Homeless Individuals',
 'Overall Homeless Veterans, 2009':'Overall Homeless Veterans',
 'Sheltered Total Homeless Veterans, 2009':'Sheltered Total Homeless Veterans',
 'Unsheltered Homeless Veterans, 2009':'Unsheltered Homeless Veterans'
       }
data_2009_df.rename(columns=dict, inplace=True)

In [51]:
# Export df to sql table
data_2009_df.to_sql(name='data_2009', con=engine, if_exists='replace')

# 2010

In [52]:
# Import csv into pandas dataframe 2008
data_2010 = pd.read_csv("Resources/2010-PIT-Counts-by-State.csv")
data_2010_df = pd.DataFrame(data_2010)
data_2010_df.head()

,State,Number of CoCs,"Overall Homeless, 2010","Sheltered ES Homeless, 2010","Sheltered TH Homeless, 2010","Sheltered SH Homeless, 2010","Sheltered Total Homeless, 2010","Unsheltered Homeless, 2010","Overall Homeless Individuals, 2010","Sheltered ES Homeless Individuals, 2010",...,"Unsheltered Homeless Family Households, 2010","Sheltered SH Chronically Homeless, 2010","Overall Chronically Homeless Individuals, 2010","Sheltered ES Chronically Homeless Individuals, 2010","Sheltered SH Chronically Homeless Individuals, 2010","Sheltered Total Chronically Homeless Individuals, 2010","Unsheltered Chronically Homeless Individuals, 2010","Overall Homeless Veterans, 2010","Sheltered Total Homeless Veterans, 2010","Unsheltered Homeless Veterans, 2010"
0,AK,2.0,"1,863","1,013",658,0,"1,671",192,"1,118",641,...,8,0,164,119,0,119,45,300,270,30
1,AL,8.0,"6,046","1,428","2,463",0,"3,891","2,155","4,553",997,...,162,0,"1,043",502,0,502,541,"1,089",911,178
2,AR,5.0,"2,762",668,"1,060",0,"1,728","1,034","2,120",542,...,85,0,395,145,0,145,250,362,247,115
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,"13,711","3,503","3,671",40,"7,214","6,497","9,226","2,018",...,180,25,"1,935",519,25,544,"1,391","2,230","1,052","1,178"

In [53]:
# Create column for the year and set to 2010
data_2010_df["Year"] = 2010
data_2010_df.head()

,State,Number of CoCs,"Overall Homeless, 2010","Sheltered ES Homeless, 2010","Sheltered TH Homeless, 2010","Sheltered SH Homeless, 2010","Sheltered Total Homeless, 2010","Unsheltered Homeless, 2010","Overall Homeless Individuals, 2010","Sheltered ES Homeless Individuals, 2010",...,"Sheltered SH Chronically Homeless, 2010","Overall Chronically Homeless Individuals, 2010","Sheltered ES Chronically Homeless Individuals, 2010","Sheltered SH Chronically Homeless Individuals, 2010","Sheltered Total Chronically Homeless Individuals, 2010","Unsheltered Chronically Homeless Individuals, 2010","Overall Homeless Veterans, 2010","Sheltered Total Homeless Veterans, 2010","Unsheltered Homeless Veterans, 2010",Year
0,AK,2.0,"1,863","1,013",658,0,"1,671",192,"1,118",641,...,0,164,119,0,119,45,300,270,30,2010
1,AL,8.0,"6,046","1,428","2,463",0,"3,891","2,155","4,553",997,...,0,"1,043",502,0,502,541,"1,089",911,178,2010
2,AR,5.0,"2,762",668,"1,060",0,"1,728","1,034","2,120",542,...,0,395,145,0,145,250,362,247,115,2010
3,AS,0.0,,,,,,,,,...,,,,,,,,,,2010
4,AZ,3.0,"13,711","3,503","3,671",40,"7,214","6,497","9,226","2,018",...,25,"1,935",519,25,544,"1,391","2,230","1,052","1,178",2010

In [54]:
# Get Column Names
cols_2010 = data_2010_df.columns.tolist()
cols_2010

['State',
 'Number of CoCs',
 'Overall Homeless, 2010',
 'Sheltered ES Homeless, 2010',
 'Sheltered TH Homeless, 2010',
 'Sheltered SH Homeless, 2010',
 'Sheltered Total Homeless, 2010',
 'Unsheltered Homeless, 2010',
 'Overall Homeless Individuals, 2010',
 'Sheltered ES Homeless Individuals, 2010',
 'Sheltered TH Homeless Individuals, 2010',
 'Sheltered SH Homeless Individuals, 2010',
 'Sheltered Total Homeless Individuals, 2010',
 'Unsheltered Homeless Individuals, 2010',
 'Overall Homeless People in Families, 2010',
 'Sheltered ES Homeless People in Families, 2010',
 'Sheltered TH Homeless People in Families, 2010',
 'Sheltered Total Homeless People in Families, 2010',
 'Unsheltered Homeless People in Families, 2010',
 'Overall Homeless Family Households, 2010',
 'Sheltered ES Homeless Family Households, 2010',
 'Sheltered TH Homeless Family Households, 2010',
 'Sheltered Total Homeless Family Households, 2010',
 'Unsheltered Homeless Family Households, 2010',
 'Sheltered SH Chronically Homeless, 2010',
 'Overall Chronically Homeless Individuals, 2010',
 'Sheltered ES Chronically Homeless Individuals, 2010',
 'Sheltered SH Chronically Homeless Individuals, 2010',
 'Sheltered Total Chronically Homeless Individuals, 2010',
 'Unsheltered Chronically Homeless Individuals, 2010',
 'Overall Homeless Veterans, 2010',
 'Sheltered Total Homeless Veterans, 2010',
 'Unsheltered Homeless Veterans, 2010',
 'Year']

In [57]:
# Rearrange column names so year is second
new_cols_2010 = ['State', 'Year',
 'Number of CoCs',
 'Overall Homeless, 2010',
 'Sheltered ES Homeless, 2010',
 'Sheltered TH Homeless, 2010',
 'Sheltered SH Homeless, 2010',
 'Sheltered Total Homeless, 2010',
 'Unsheltered Homeless, 2010',
 'Overall Homeless Individuals, 2010',
 'Sheltered ES Homeless Individuals, 2010',
 'Sheltered TH Homeless Individuals, 2010',
 'Sheltered SH Homeless Individuals, 2010',
 'Sheltered Total Homeless Individuals, 2010',
 'Unsheltered Homeless Individuals, 2010',
 'Overall Homeless People in Families, 2010',
 'Sheltered ES Homeless People in Families, 2010',
 'Sheltered TH Homeless People in Families, 2010',
 'Sheltered Total Homeless People in Families, 2010',
 'Unsheltered Homeless People in Families, 2010',
 'Overall Homeless Family Households, 2010',
 'Sheltered ES Homeless Family Households, 2010',
 'Sheltered TH Homeless Family Households, 2010',
 'Sheltered Total Homeless Family Households, 2010',
 'Unsheltered Homeless Family Households, 2010',
 'Sheltered SH Chronically Homeless, 2010',
 'Overall Chronically Homeless Individuals, 2010',
 'Sheltered ES Chronically Homeless Individuals, 2010',
 'Sheltered SH Chronically Homeless Individuals, 2010',
 'Sheltered Total Chronically Homeless Individuals, 2010',
 'Unsheltered Chronically Homeless Individuals, 2010',
 'Overall Homeless Veterans, 2010',
 'Sheltered Total Homeless Veterans, 2010',
 'Unsheltered Homeless Veterans, 2010'
 ]

In [58]:
# Apply rearranged column names
data_2010_df = data_2010_df[new_cols_2010]
data_2010_df.head()

,State,Year,Number of CoCs,"Overall Homeless, 2010","Sheltered ES Homeless, 2010","Sheltered TH Homeless, 2010","Sheltered SH Homeless, 2010","Sheltered Total Homeless, 2010","Unsheltered Homeless, 2010","Overall Homeless Individuals, 2010",...,"Unsheltered Homeless Family Households, 2010","Sheltered SH Chronically Homeless, 2010","Overall Chronically Homeless Individuals, 2010","Sheltered ES Chronically Homeless Individuals, 2010","Sheltered SH Chronically Homeless Individuals, 2010","Sheltered Total Chronically Homeless Individuals, 2010","Unsheltered Chronically Homeless Individuals, 2010","Overall Homeless Veterans, 2010","Sheltered Total Homeless Veterans, 2010","Unsheltered Homeless Veterans, 2010"
0,AK,2010,2.0,"1,863","1,013",658,0,"1,671",192,"1,118",...,8,0,164,119,0,119,45,300,270,30
1,AL,2010,8.0,"6,046","1,428","2,463",0,"3,891","2,155","4,553",...,162,0,"1,043",502,0,502,541,"1,089",911,178
2,AR,2010,5.0,"2,762",668,"1,060",0,"1,728","1,034","2,120",...,85,0,395,145,0,145,250,362,247,115
3,AS,2010,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2010,3.0,"13,711","3,503","3,671",40,"7,214","6,497","9,226",...,180,25,"1,935",519,25,544,"1,391","2,230","1,052","1,178"

In [59]:
# rename columns to remove year from each column title
dict = {
 'Overall Homeless, 2010':'Overall Homeless',
 'Sheltered ES Homeless, 2010':'Sheltered ES Homeless',
 'Sheltered TH Homeless, 2010':'Sheltered TH Homeless',
 'Sheltered Total Homeless, 2010':'Sheltered Total Homeless',
 'Unsheltered Homeless, 2010':'Unsheltered Homeless',
 'Overall Homeless Individuals, 2010':'Overall Homeless Individuals',
 'Sheltered ES Homeless Individuals, 2010':'Sheltered ES Homeless Individuals',
 'Sheltered TH Homeless Individuals, 2010':'Sheltered TH Homeless Individuals',
 'Sheltered Total Homeless Individuals, 2010':'Sheltered Total Homeless Individuals',
 'Unsheltered Homeless Individuals, 2010':'Unsheltered Homeless Individuals',
 'Overall Homeless People in Families, 2010':'Overall Homeless People in Families',
 'Sheltered ES Homeless People in Families, 2010':'Sheltered ES Homeless People in Families',
 'Sheltered TH Homeless People in Families, 2010':'Sheltered TH Homeless People in Families',
 'Sheltered Total Homeless People in Families, 2010':'Sheltered Total Homeless People in Families',
 'Unsheltered Homeless People in Families, 2010':'Unsheltered Homeless People in Families',
 'Overall Homeless Family Households, 2010':'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households, 2010':'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households, 2010':'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households, 2010':'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households, 2010':'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless Individuals, 2010':'Overall Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals, 2010':'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals, 2010':'Unsheltered Chronically Homeless Individuals',
 'Overall Homeless Veterans, 2010':'Overall Homeless Veterans',
 'Sheltered Total Homeless Veterans, 2010':'Sheltered Total Homeless Veterans',
 'Unsheltered Homeless Veterans, 2010':'Unsheltered Homeless Veterans'
       }
data_2010_df.rename(columns=dict, inplace=True)

In [60]:
# Export df to sql table
data_2010_df.to_sql(name='data_2010', con=engine, if_exists='replace')

# 2011

In [85]:
# Import csv into pandas dataframe 2011
data_2011 = pd.read_csv("Resources/2011-PIT-Counts-by-State.csv")
data_2011_df = pd.DataFrame(data_2011)
data_2011_df.head()

,State,Number of CoCs,"Overall Homeless, 2011","Sheltered ES Homeless, 2011","Sheltered TH Homeless, 2011","Sheltered SH Homeless, 2011","Sheltered Total Homeless, 2011","Unsheltered Homeless, 2011","Overall Homeless Individuals, 2011","Overall Homeless Individuals - Under 18, 2011",...,"Sheltered SH Chronically Homeless Individuals, 2011","Sheltered Total Chronically Homeless Individuals, 2011","Unsheltered Chronically Homeless Individuals, 2011","Overall Chronically Homeless People in Families, 2011","Sheltered ES Chronically Homeless People in Families, 2011","Sheltered Total Chronically Homeless People in Families, 2011","Unsheltered Chronically Homeless People in Families, 2011","Overall Homeless Veterans, 2011","Sheltered Total Homeless Veterans, 2011","Unsheltered Homeless Veterans, 2011"
0,AK,2.0,"2,128","1,035",725,0,"1,760",368,"1,286",21,...,0,169,57,27,25,25,2,288,236,52
1,AL,8.0,"5,558","1,615","2,100",34,"3,749","1,809","4,325",114,...,34,396,650,68,22,22,46,659,387,272
2,AR,7.0,"3,424","1,018",784,0,"1,802","1,622","2,505",158,...,0,267,233,107,61,61,46,411,268,143
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,"10,504","3,571","3,691",40,"7,302","3,202","6,403",117,...,40,738,"1,201",344,290,290,54,"1,528","1,018",510

In [86]:
# Create column for the year and set to 2010
data_2011_df["Year"] = 2011
data_2011_df.head()

,State,Number of CoCs,"Overall Homeless, 2011","Sheltered ES Homeless, 2011","Sheltered TH Homeless, 2011","Sheltered SH Homeless, 2011","Sheltered Total Homeless, 2011","Unsheltered Homeless, 2011","Overall Homeless Individuals, 2011","Overall Homeless Individuals - Under 18, 2011",...,"Sheltered Total Chronically Homeless Individuals, 2011","Unsheltered Chronically Homeless Individuals, 2011","Overall Chronically Homeless People in Families, 2011","Sheltered ES Chronically Homeless People in Families, 2011","Sheltered Total Chronically Homeless People in Families, 2011","Unsheltered Chronically Homeless People in Families, 2011","Overall Homeless Veterans, 2011","Sheltered Total Homeless Veterans, 2011","Unsheltered Homeless Veterans, 2011",Year
0,AK,2.0,"2,128","1,035",725,0,"1,760",368,"1,286",21,...,169,57,27,25,25,2,288,236,52,2011
1,AL,8.0,"5,558","1,615","2,100",34,"3,749","1,809","4,325",114,...,396,650,68,22,22,46,659,387,272,2011
2,AR,7.0,"3,424","1,018",784,0,"1,802","1,622","2,505",158,...,267,233,107,61,61,46,411,268,143,2011
3,AS,0.0,,,,,,,,,...,,,,,,,,,,2011
4,AZ,3.0,"10,504","3,571","3,691",40,"7,302","3,202","6,403",117,...,738,"1,201",344,290,290,54,"1,528","1,018",510,2011

In [87]:
# Get Column Names
cols_2011 = data_2011_df.columns.tolist()
cols_2011

['State',
 'Number of CoCs',
 'Overall Homeless, 2011',
 'Sheltered ES Homeless, 2011',
 'Sheltered TH Homeless, 2011',
 'Sheltered SH Homeless, 2011',
 'Sheltered Total Homeless, 2011',
 'Unsheltered Homeless, 2011',
 'Overall Homeless Individuals, 2011',
 'Overall Homeless Individuals - Under 18, 2011',
 'Sheltered ES Homeless Individuals, 2011',
 'Sheltered ES Homeless Individuals - Under 18, 2011',
 'Sheltered TH Homeless Individuals, 2011',
 'Sheltered TH Homeless Individuals - Under 18, 2011',
 'Sheltered SH Homeless Individuals, 2011',
 'Sheltered Total Homeless Individuals, 2011',
 'Sheltered Total Homeless Individuals - Under 18, 2011',
 'Unsheltered Homeless Individuals, 2011',
 'Unsheltered Homeless Individuals - Under 18, 2011',
 'Overall Homeless People in Families, 2011',
 'Sheltered ES Homeless People in Families, 2011',
 'Sheltered TH Homeless People in Families, 2011',
 'Sheltered Total Homeless People in Families, 2011',
 'Unsheltered Homeless People in Families, 2011',
 'Overall Homeless Family Households, 2011',
 'Sheltered ES Homeless Family Households, 2011',
 'Sheltered TH Homeless Family Households, 2011',
 'Sheltered Total Homeless Family Households, 2011',
 'Unsheltered Homeless Family Households, 2011',
 'Overall Chronically Homeless, 2011',
 'Sheltered ES Chronically Homeless, 2011',
 'Sheltered SH Chronically Homeless, 2011',
 'Sheltered Total Chronically Homeless, 2011',
 'Unsheltered Chronically Homeless, 2011',
 'Overall Chronically Homeless Individuals, 2011',
 'Sheltered ES Chronically Homeless Individuals, 2011',
 'Sheltered SH Chronically Homeless Individuals, 2011',
 'Sheltered Total Chronically Homeless Individuals, 2011',
 'Unsheltered Chronically Homeless Individuals, 2011',
 'Overall Chronically Homeless People in Families, 2011',
 'Sheltered ES Chronically Homeless People in Families, 2011',
 'Sheltered Total Chronically Homeless People in Families, 2011',
 'Unsheltered Chronically Homeless People in Families, 2011',
 'Overall Homeless Veterans, 2011',
 'Sheltered Total Homeless Veterans, 2011',
 'Unsheltered Homeless Veterans, 2011',
 'Year']

In [88]:
# Rearrange column names so year is second
new_cols_2011 = ['State', 'Year',
 'Number of CoCs',
 'Overall Homeless, 2011',
 'Sheltered ES Homeless, 2011',
 'Sheltered TH Homeless, 2011',
 'Sheltered SH Homeless, 2011',
 'Sheltered Total Homeless, 2011',
 'Unsheltered Homeless, 2011',
 'Overall Homeless Individuals, 2011',
 'Overall Homeless Individuals - Under 18, 2011',
 'Sheltered ES Homeless Individuals, 2011',
 'Sheltered ES Homeless Individuals - Under 18, 2011',
 'Sheltered TH Homeless Individuals, 2011',
 'Sheltered TH Homeless Individuals - Under 18, 2011',
 'Sheltered SH Homeless Individuals, 2011',
 'Sheltered Total Homeless Individuals, 2011',
 'Sheltered Total Homeless Individuals - Under 18, 2011',
 'Unsheltered Homeless Individuals, 2011',
 'Unsheltered Homeless Individuals - Under 18, 2011',
 'Overall Homeless People in Families, 2011',
 'Sheltered ES Homeless People in Families, 2011',
 'Sheltered TH Homeless People in Families, 2011',
 'Sheltered Total Homeless People in Families, 2011',
 'Unsheltered Homeless People in Families, 2011',
 'Overall Homeless Family Households, 2011',
 'Sheltered ES Homeless Family Households, 2011',
 'Sheltered TH Homeless Family Households, 2011',
 'Sheltered Total Homeless Family Households, 2011',
 'Unsheltered Homeless Family Households, 2011',
 'Overall Chronically Homeless, 2011',
 'Sheltered ES Chronically Homeless, 2011',
 'Sheltered SH Chronically Homeless, 2011',
 'Sheltered Total Chronically Homeless, 2011',
 'Unsheltered Chronically Homeless, 2011',
 'Overall Chronically Homeless Individuals, 2011',
 'Sheltered ES Chronically Homeless Individuals, 2011',
 'Sheltered SH Chronically Homeless Individuals, 2011',
 'Sheltered Total Chronically Homeless Individuals, 2011',
 'Unsheltered Chronically Homeless Individuals, 2011',
 'Overall Chronically Homeless People in Families, 2011',
 'Sheltered ES Chronically Homeless People in Families, 2011',
 'Sheltered Total Chronically Homeless People in Families, 2011',
 'Unsheltered Chronically Homeless People in Families, 2011',
 'Overall Homeless Veterans, 2011',
 'Sheltered Total Homeless Veterans, 2011',
 'Unsheltered Homeless Veterans, 2011'
 ]

In [89]:
# Apply rearranged column names
data_2011_df = data_2011_df[new_cols_2011]
data_2011_df.head()

,State,Year,Number of CoCs,"Overall Homeless, 2011","Sheltered ES Homeless, 2011","Sheltered TH Homeless, 2011","Sheltered SH Homeless, 2011","Sheltered Total Homeless, 2011","Unsheltered Homeless, 2011","Overall Homeless Individuals, 2011",...,"Sheltered SH Chronically Homeless Individuals, 2011","Sheltered Total Chronically Homeless Individuals, 2011","Unsheltered Chronically Homeless Individuals, 2011","Overall Chronically Homeless People in Families, 2011","Sheltered ES Chronically Homeless People in Families, 2011","Sheltered Total Chronically Homeless People in Families, 2011","Unsheltered Chronically Homeless People in Families, 2011","Overall Homeless Veterans, 2011","Sheltered Total Homeless Veterans, 2011","Unsheltered Homeless Veterans, 2011"
0,AK,2011,2.0,"2,128","1,035",725,0,"1,760",368,"1,286",...,0,169,57,27,25,25,2,288,236,52
1,AL,2011,8.0,"5,558","1,615","2,100",34,"3,749","1,809","4,325",...,34,396,650,68,22,22,46,659,387,272
2,AR,2011,7.0,"3,424","1,018",784,0,"1,802","1,622","2,505",...,0,267,233,107,61,61,46,411,268,143
3,AS,2011,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2011,3.0,"10,504","3,571","3,691",40,"7,302","3,202","6,403",...,40,738,"1,201",344,290,290,54,"1,528","1,018",510

In [90]:
# rename columns to remove year from each column title
dict = {
 'Overall Homeless, 2011':'Overall Homeless',
 'Sheltered ES Homeless, 2011':'Sheltered ES Homeless',
 'Sheltered TH Homeless, 2011':'Sheltered TH Homeless',
 'Sheltered SH Homeless, 2011':'Sheltered SH Homeless',
 'Sheltered Total Homeless, 2011':'Sheltered Total Homeless',
 'Unsheltered Homeless, 2011':'Unsheltered Homeless',
 'Overall Homeless Individuals, 2011':'Overall Homeless Individuals',
 'Overall Homeless Individuals - Under 18, 2011':'Overall Homeless Individuals - Under 18',
 'Sheltered ES Homeless Individuals, 2011':'Sheltered ES Homeless Individuals',
 'Sheltered ES Homeless Individuals - Under 18, 2011':'Sheltered ES Homeless Individuals - Under 18',
 'Sheltered TH Homeless Individuals, 2011':'Sheltered TH Homeless Individuals',
 'Sheltered TH Homeless Individuals - Under 18, 2011':'Sheltered TH Homeless Individuals - Under 18',
 'Sheltered SH Homeless Individuals, 2011':'Sheltered SH Homeless Individuals',
 'Sheltered Total Homeless Individuals, 2011':'Sheltered Total Homeless Individuals',
 'Sheltered Total Homeless Individuals - Under 18, 2011':'Sheltered Total Homeless Individuals - Under 18',
 'Unsheltered Homeless Individuals, 2011':'Unsheltered Homeless Individuals',
 'Unsheltered Homeless Individuals - Under 18, 2011':'Unsheltered Homeless Individuals - Under 18',
 'Overall Homeless People in Families, 2011':'Overall Homeless People in Families',
 'Sheltered ES Homeless People in Families, 2011':'Sheltered ES Homeless People in Families',
 'Sheltered TH Homeless People in Families, 2011':'Sheltered TH Homeless People in Families',
 'Sheltered Total Homeless People in Families, 2011':'Sheltered Total Homeless People in Families',
 'Unsheltered Homeless People in Families, 2011':'Unsheltered Homeless People in Families',
 'Overall Homeless Family Households, 2011':'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households, 2011':'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households, 2011':'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households, 2011':'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households, 2011':'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless, 2011':'Overall Chronically Homeless',
 'Sheltered ES Chronically Homeless, 2011':'Sheltered ES Chronically Homeless',
 'Sheltered SH Chronically Homeless, 2011':'Sheltered SH Chronically Homeless',
 'Sheltered Total Chronically Homeless, 2011':'Sheltered Total Chronically Homeless',
 'Unsheltered Chronically Homeless, 2011':'Unsheltered Chronically Homeless',
 'Overall Chronically Homeless Individuals, 2011':'Overall Chronically Homeless Individuals',
 'Sheltered ES Chronically Homeless Individuals, 2011':'Sheltered ES Chronically Homeless Individuals',
 'Sheltered SH Chronically Homeless Individuals, 2011':'Sheltered SH Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals, 2011':'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals, 2011':'Unsheltered Chronically Homeless Individuals',
 'Overall Chronically Homeless People in Families, 2011':'Overall Chronically Homeless People in Families',
 'Sheltered ES Chronically Homeless People in Families, 2011':'Sheltered ES Chronically Homeless People in Families',
 'Sheltered Total Chronically Homeless People in Families, 2011':'Sheltered Total Chronically Homeless People in Families',
 'Unsheltered Chronically Homeless People in Families, 2011':'Unsheltered Chronically Homeless People in Families',
 'Overall Homeless Veterans, 2011':'Overall Homeless Veterans',
 'Sheltered Total Homeless Veterans, 2011':'Sheltered Total Homeless Veterans',
 'Unsheltered Homeless Veterans, 2011':'Unsheltered Homeless Veterans'
       }
data_2011_df.rename(columns=dict, inplace=True)

In [91]:
# Export df to sql table
data_2011_df.to_sql(name='data_2011', con=engine, if_exists='replace')

# 2012

In [68]:
# Import csv into pandas dataframe 2012
data_2012 = pd.read_csv("Resources/2012-PIT-Counts-by-State.csv")
data_2012_df = pd.DataFrame(data_2012)
data_2012_df.head()

,State,Number of CoCs,"Overall Homeless, 2012","Sheltered ES Homeless, 2012","Sheltered TH Homeless, 2012","Sheltered SH Homeless, 2012","Sheltered Total Homeless, 2012","Unsheltered Homeless, 2012","Overall Homeless Individuals, 2012","Overall Homeless Individuals - Under 18, 2012",...,"Sheltered SH Chronically Homeless Individuals, 2012","Sheltered Total Chronically Homeless Individuals, 2012","Unsheltered Chronically Homeless Individuals, 2012","Overall Chronically Homeless People in Families, 2012","Sheltered ES Chronically Homeless People in Families, 2012","Sheltered Total Chronically Homeless People in Families, 2012","Unsheltered Chronically Homeless People in Families, 2012","Overall Homeless Veterans, 2012","Sheltered Total Homeless Veterans, 2012","Unsheltered Homeless Veterans, 2012"
0,AK,2.0,"1,913","1,139",577,0,"1,716",197,"1,298",33,...,0,257,16,6,6,6,0,256,227,29
1,AL,8.0,"5,209","1,663","1,969",32,"3,664","1,545","3,825",49,...,32,331,579,59,22,22,37,526,377,149
2,AR,6.0,"4,214",886,716,0,"1,602","2,612","3,428",80,...,0,142,219,76,29,29,47,362,205,157
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,"11,302","4,291","3,884",40,"8,215","3,087","6,310",129,...,34,389,"1,216",290,226,226,64,"1,478","1,007",471

In [69]:
# Create column for the year and set to 2010
data_2012_df["Year"] = 2012
data_2012_df.head()

,State,Number of CoCs,"Overall Homeless, 2012","Sheltered ES Homeless, 2012","Sheltered TH Homeless, 2012","Sheltered SH Homeless, 2012","Sheltered Total Homeless, 2012","Unsheltered Homeless, 2012","Overall Homeless Individuals, 2012","Overall Homeless Individuals - Under 18, 2012",...,"Sheltered Total Chronically Homeless Individuals, 2012","Unsheltered Chronically Homeless Individuals, 2012","Overall Chronically Homeless People in Families, 2012","Sheltered ES Chronically Homeless People in Families, 2012","Sheltered Total Chronically Homeless People in Families, 2012","Unsheltered Chronically Homeless People in Families, 2012","Overall Homeless Veterans, 2012","Sheltered Total Homeless Veterans, 2012","Unsheltered Homeless Veterans, 2012",Year
0,AK,2.0,"1,913","1,139",577,0,"1,716",197,"1,298",33,...,257,16,6,6,6,0,256,227,29,2012
1,AL,8.0,"5,209","1,663","1,969",32,"3,664","1,545","3,825",49,...,331,579,59,22,22,37,526,377,149,2012
2,AR,6.0,"4,214",886,716,0,"1,602","2,612","3,428",80,...,142,219,76,29,29,47,362,205,157,2012
3,AS,0.0,,,,,,,,,...,,,,,,,,,,2012
4,AZ,3.0,"11,302","4,291","3,884",40,"8,215","3,087","6,310",129,...,389,"1,216",290,226,226,64,"1,478","1,007",471,2012

In [70]:
# Get Column Names
cols_2012 = data_2012_df.columns.tolist()
cols_2012

['State',
 'Number of CoCs',
 'Overall Homeless, 2012',
 'Sheltered ES Homeless, 2012',
 'Sheltered TH Homeless, 2012',
 'Sheltered SH Homeless, 2012',
 'Sheltered Total Homeless, 2012',
 'Unsheltered Homeless, 2012',
 'Overall Homeless Individuals, 2012',
 'Overall Homeless Individuals - Under 18, 2012',
 'Sheltered ES Homeless Individuals, 2012',
 'Sheltered ES Homeless Individuals - Under 18, 2012',
 'Sheltered TH Homeless Individuals, 2012',
 'Sheltered TH Homeless Individuals - Under 18, 2012',
 'Sheltered SH Homeless Individuals, 2012',
 'Sheltered Total Homeless Individuals, 2012',
 'Sheltered Total Homeless Individuals - Under 18, 2012',
 'Unsheltered Homeless Individuals, 2012',
 'Unsheltered Homeless Individuals - Under 18, 2012',
 'Overall Homeless People in Families, 2012',
 'Sheltered ES Homeless People in Families, 2012',
 'Sheltered TH Homeless People in Families, 2012',
 'Sheltered Total Homeless People in Families, 2012',
 'Unsheltered Homeless People in Families, 2012',
 'Overall Homeless Family Households, 2012',
 'Sheltered ES Homeless Family Households, 2012',
 'Sheltered TH Homeless Family Households, 2012',
 'Sheltered Total Homeless Family Households, 2012',
 'Unsheltered Homeless Family Households, 2012',
 'Overall Chronically Homeless, 2012',
 'Sheltered ES Chronically Homeless, 2012',
 'Sheltered SH Chronically Homeless, 2012',
 'Sheltered Total Chronically Homeless, 2012',
 'Unsheltered Chronically Homeless, 2012',
 'Overall Chronically Homeless Individuals, 2012',
 'Sheltered ES Chronically Homeless Individuals, 2012',
 'Sheltered SH Chronically Homeless Individuals, 2012',
 'Sheltered Total Chronically Homeless Individuals, 2012',
 'Unsheltered Chronically Homeless Individuals, 2012',
 'Overall Chronically Homeless People in Families, 2012',
 'Sheltered ES Chronically Homeless People in Families, 2012',
 'Sheltered Total Chronically Homeless People in Families, 2012',
 'Unsheltered Chronically Homeless People in Families, 2012',
 'Overall Homeless Veterans, 2012',
 'Sheltered Total Homeless Veterans, 2012',
 'Unsheltered Homeless Veterans, 2012',
 'Year']

In [73]:
# Rearrange column names so year is second
new_cols_2012 = ['State', 'Year',
 'Number of CoCs',
 'Overall Homeless, 2012',
 'Sheltered ES Homeless, 2012',
 'Sheltered TH Homeless, 2012',
 'Sheltered SH Homeless, 2012',
 'Sheltered Total Homeless, 2012',
 'Unsheltered Homeless, 2012',
 'Overall Homeless Individuals, 2012',
 'Overall Homeless Individuals - Under 18, 2012',
 'Sheltered ES Homeless Individuals, 2012',
 'Sheltered ES Homeless Individuals - Under 18, 2012',
 'Sheltered TH Homeless Individuals, 2012',
 'Sheltered TH Homeless Individuals - Under 18, 2012',
 'Sheltered SH Homeless Individuals, 2012',
 'Sheltered Total Homeless Individuals, 2012',
 'Sheltered Total Homeless Individuals - Under 18, 2012',
 'Unsheltered Homeless Individuals, 2012',
 'Unsheltered Homeless Individuals - Under 18, 2012',
 'Overall Homeless People in Families, 2012',
 'Sheltered ES Homeless People in Families, 2012',
 'Sheltered TH Homeless People in Families, 2012',
 'Sheltered Total Homeless People in Families, 2012',
 'Unsheltered Homeless People in Families, 2012',
 'Overall Homeless Family Households, 2012',
 'Sheltered ES Homeless Family Households, 2012',
 'Sheltered TH Homeless Family Households, 2012',
 'Sheltered Total Homeless Family Households, 2012',
 'Unsheltered Homeless Family Households, 2012',
 'Overall Chronically Homeless, 2012',
 'Sheltered ES Chronically Homeless, 2012',
 'Sheltered SH Chronically Homeless, 2012',
 'Sheltered Total Chronically Homeless, 2012',
 'Unsheltered Chronically Homeless, 2012',
 'Overall Chronically Homeless Individuals, 2012',
 'Sheltered ES Chronically Homeless Individuals, 2012',
 'Sheltered SH Chronically Homeless Individuals, 2012',
 'Sheltered Total Chronically Homeless Individuals, 2012',
 'Unsheltered Chronically Homeless Individuals, 2012',
 'Overall Chronically Homeless People in Families, 2012',
 'Sheltered ES Chronically Homeless People in Families, 2012',
 'Sheltered Total Chronically Homeless People in Families, 2012',
 'Unsheltered Chronically Homeless People in Families, 2012',
 'Overall Homeless Veterans, 2012',
 'Sheltered Total Homeless Veterans, 2012',
 'Unsheltered Homeless Veterans, 2012'
 ]

In [74]:
# Apply rearranged column names
data_2012_df = data_2012_df[new_cols_2012]
data_2012_df.head()

,State,Year,Number of CoCs,"Overall Homeless, 2012","Sheltered ES Homeless, 2012","Sheltered TH Homeless, 2012","Sheltered SH Homeless, 2012","Sheltered Total Homeless, 2012","Unsheltered Homeless, 2012","Overall Homeless Individuals, 2012",...,"Sheltered SH Chronically Homeless Individuals, 2012","Sheltered Total Chronically Homeless Individuals, 2012","Unsheltered Chronically Homeless Individuals, 2012","Overall Chronically Homeless People in Families, 2012","Sheltered ES Chronically Homeless People in Families, 2012","Sheltered Total Chronically Homeless People in Families, 2012","Unsheltered Chronically Homeless People in Families, 2012","Overall Homeless Veterans, 2012","Sheltered Total Homeless Veterans, 2012","Unsheltered Homeless Veterans, 2012"
0,AK,2012,2.0,"1,913","1,139",577,0,"1,716",197,"1,298",...,0,257,16,6,6,6,0,256,227,29
1,AL,2012,8.0,"5,209","1,663","1,969",32,"3,664","1,545","3,825",...,32,331,579,59,22,22,37,526,377,149
2,AR,2012,6.0,"4,214",886,716,0,"1,602","2,612","3,428",...,0,142,219,76,29,29,47,362,205,157
3,AS,2012,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2012,3.0,"11,302","4,291","3,884",40,"8,215","3,087","6,310",...,34,389,"1,216",290,226,226,64,"1,478","1,007",471

In [82]:
# rename columns to remove year from each column title
dict = {
 'Overall Homeless, 2012':'Overall Homeless',
 'Sheltered ES Homeless, 2012':'Sheltered ES Homeless',
 'Sheltered TH Homeless, 2012':'Sheltered TH Homeless',
 'Sheltered SH Homeless, 2012':'Sheltered SH Homeless',
 'Sheltered Total Homeless, 2012':'Sheltered Total Homeless',
 'Unsheltered Homeless, 2012':'Unsheltered Homeless',
 'Overall Homeless Individuals, 2012':'Overall Homeless Individuals',
 'Overall Homeless Individuals - Under 18, 2012':'Overall Homeless Individuals - Under 18',
 'Sheltered ES Homeless Individuals, 2012':'Sheltered ES Homeless Individuals',
 'Sheltered ES Homeless Individuals - Under 18, 2012':'Sheltered ES Homeless Individuals - Under 18',
 'Sheltered TH Homeless Individuals, 2012':'Sheltered TH Homeless Individuals',
 'Sheltered TH Homeless Individuals - Under 18, 2012':'Sheltered TH Homeless Individuals - Under 18',
 'Sheltered SH Homeless Individuals, 2012':'Sheltered SH Homeless Individuals',
 'Sheltered Total Homeless Individuals, 2012':'Sheltered Total Homeless Individuals',
 'Sheltered Total Homeless Individuals - Under 18, 2012':'Sheltered Total Homeless Individuals - Under 18',
 'Unsheltered Homeless Individuals, 2012':'Unsheltered Homeless Individuals',
 'Unsheltered Homeless Individuals - Under 18, 2012':'Unsheltered Homeless Individuals - Under 18',
 'Overall Homeless People in Families, 2012':'Overall Homeless People in Families',
 'Sheltered ES Homeless People in Families, 2012':'Sheltered ES Homeless People in Families',
 'Sheltered TH Homeless People in Families, 2012':'Sheltered TH Homeless People in Families',
 'Sheltered Total Homeless People in Families, 2012':'Sheltered Total Homeless People in Families',
 'Unsheltered Homeless People in Families, 2012':'Unsheltered Homeless People in Families',
 'Overall Homeless Family Households, 2012':'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households, 2012':'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households, 2012':'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households, 2012':'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households, 2012':'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless, 2012':'Overall Chronically Homeless',
 'Sheltered ES Chronically Homeless, 2012':'Sheltered ES Chronically Homeless',
 'Sheltered SH Chronically Homeless, 2012':'Sheltered SH Chronically Homeless',
 'Sheltered Total Chronically Homeless, 2012':'Sheltered Total Chronically Homeless',
 'Unsheltered Chronically Homeless, 2012':'Unsheltered Chronically Homeless',
 'Overall Chronically Homeless Individuals, 2012':'Overall Chronically Homeless Individuals',
 'Sheltered ES Chronically Homeless Individuals, 2012':'Sheltered ES Chronically Homeless Individuals',
 'Sheltered SH Chronically Homeless Individuals, 2012':'Sheltered SH Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals, 2012':'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals, 2012':'Unsheltered Chronically Homeless Individuals',
 'Overall Chronically Homeless People in Families, 2012':'Overall Chronically Homeless People in Families',
 'Sheltered ES Chronically Homeless People in Families, 2012':'Sheltered ES Chronically Homeless People in Families',
 'Sheltered Total Chronically Homeless People in Families, 2012':'Sheltered Total Chronically Homeless People in Families',
 'Unsheltered Chronically Homeless People in Families, 2012':'Unsheltered Chronically Homeless People in Families',
 'Overall Homeless Veterans, 2012':'Overall Homeless Veterans',
 'Sheltered Total Homeless Veterans, 2012':'Sheltered Total Homeless Veterans',
 'Unsheltered Homeless Veterans, 2012':'Unsheltered Homeless Veterans'
       }
data_2012_df.rename(columns=dict, inplace=True)

In [83]:
data_2012_df.head()

,State,Year,Number of CoCs,Overall Homeless,Sheltered ES Homeless,Sheltered TH Homeless,Sheltered SH Homeless,Sheltered Total Homeless,Unsheltered Homeless,Overall Homeless Individuals,...,Sheltered SH Chronically Homeless Individuals,Sheltered Total Chronically Homeless Individuals,Unsheltered Chronically Homeless Individuals,Overall Chronically Homeless People in Families,Sheltered ES Chronically Homeless People in Families,Sheltered Total Chronically Homeless People in Families,Unsheltered Chronically Homeless People in Families,Overall Homeless Veterans,Sheltered Total Homeless Veterans,Unsheltered Homeless Veterans
0,AK,2012,2.0,"1,913","1,139",577,0,"1,716",197,"1,298",...,0,257,16,6,6,6,0,256,227,29
1,AL,2012,8.0,"5,209","1,663","1,969",32,"3,664","1,545","3,825",...,32,331,579,59,22,22,37,526,377,149
2,AR,2012,6.0,"4,214",886,716,0,"1,602","2,612","3,428",...,0,142,219,76,29,29,47,362,205,157
3,AS,2012,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2012,3.0,"11,302","4,291","3,884",40,"8,215","3,087","6,310",...,34,389,"1,216",290,226,226,64,"1,478","1,007",471

In [84]:
# Export df to sql table
data_2012_df.to_sql(name='data_2012', con=engine, if_exists='replace')

# 2013

In [92]:
# Import csv into pandas dataframe 2012
data_2013 = pd.read_csv("Resources/2013-PIT-Counts-by-State.csv")
data_2013_df = pd.DataFrame(data_2013)
data_2013_df.head()

,State,Number of CoCs,"Overall Homeless, 2013","Overall Homeless - Under 18, 2013","Overall Homeless - Age 18 to 24, 2013","Overall Homeless - Over 24, 2013","Sheltered ES Homeless, 2013","Sheltered ES Homeless - Under 18, 2013","Sheltered ES Homeless - Age 18 to 24, 2013","Sheltered ES Homeless - Over 24, 2013",...,"Overall Chronically Homeless People in Families, 2013","Sheltered ES Chronically Homeless People in Families, 2013","Sheltered Total Chronically Homeless People in Families, 2013","Unsheltered Chronically Homeless People in Families, 2013","Overall Homeless Veterans, 2013","Overall Homeless Veterans - Female, 2013","Sheltered Total Homeless Veterans, 2013","Sheltered Total Homeless Veterans - Female, 2013","Unsheltered Homeless Veterans, 2013","Unsheltered Homeless Veterans - Female, 2013"
0,AK,2.0,"1,946",369,189,"1,388","1,137",195,103,839,...,18,14,14,4,210,9,188,8,22,1
1,AL,8.0,"4,689",694,506,"3,489","1,555",215,165,"1,175",...,90,46,46,44,511,25,363,16,148,9
2,AR,6.0,"3,812",429,350,"3,033","1,037",275,96,666,...,37,29,29,8,462,11,326,9,136,2
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,"10,562","2,598",942,"7,022","3,893",945,298,"2,650",...,124,70,70,54,"1,222",75,901,58,321,17

In [93]:
# Create column for the year and set to 2010
data_2013_df["Year"] = 2013
data_2013_df.head()

,State,Number of CoCs,"Overall Homeless, 2013","Overall Homeless - Under 18, 2013","Overall Homeless - Age 18 to 24, 2013","Overall Homeless - Over 24, 2013","Sheltered ES Homeless, 2013","Sheltered ES Homeless - Under 18, 2013","Sheltered ES Homeless - Age 18 to 24, 2013","Sheltered ES Homeless - Over 24, 2013",...,"Sheltered ES Chronically Homeless People in Families, 2013","Sheltered Total Chronically Homeless People in Families, 2013","Unsheltered Chronically Homeless People in Families, 2013","Overall Homeless Veterans, 2013","Overall Homeless Veterans - Female, 2013","Sheltered Total Homeless Veterans, 2013","Sheltered Total Homeless Veterans - Female, 2013","Unsheltered Homeless Veterans, 2013","Unsheltered Homeless Veterans - Female, 2013",Year
0,AK,2.0,"1,946",369,189,"1,388","1,137",195,103,839,...,14,14,4,210,9,188,8,22,1,2013
1,AL,8.0,"4,689",694,506,"3,489","1,555",215,165,"1,175",...,46,46,44,511,25,363,16,148,9,2013
2,AR,6.0,"3,812",429,350,"3,033","1,037",275,96,666,...,29,29,8,462,11,326,9,136,2,2013
3,AS,0.0,,,,,,,,,...,,,,,,,,,,2013
4,AZ,3.0,"10,562","2,598",942,"7,022","3,893",945,298,"2,650",...,70,70,54,"1,222",75,901,58,321,17,2013

In [94]:
# Get Column Names
cols_2013 = data_2013_df.columns.tolist()
cols_2013

['State',
 'Number of CoCs',
 'Overall Homeless, 2013',
 'Overall Homeless - Under 18, 2013',
 'Overall Homeless - Age 18 to 24, 2013',
 'Overall Homeless - Over 24, 2013',
 'Sheltered ES Homeless, 2013',
 'Sheltered ES Homeless - Under 18, 2013',
 'Sheltered ES Homeless - Age 18 to 24, 2013',
 'Sheltered ES Homeless - Over 24, 2013',
 'Sheltered TH Homeless, 2013',
 'Sheltered TH Homeless - Under 18, 2013',
 'Sheltered TH Homeless - Age 18 to 24, 2013',
 'Sheltered TH Homeless - Over 24, 2013',
 'Sheltered SH Homeless, 2013',
 'Sheltered SH Homeless - Age 18 to 24, 2013',
 'Sheltered SH Homeless - Over 24, 2013',
 'Sheltered Total Homeless, 2013',
 'Sheltered Total Homeless - Under 18, 2013',
 'Sheltered Total Homeless - Age 18 to 24, 2013',
 'Sheltered Total Homeless - Over 24, 2013',
 'Unsheltered Homeless, 2013',
 'Unsheltered Homeless - Under 18, 2013',
 'Unsheltered Homeless - Age 18 to 24, 2013',
 'Unsheltered Homeless - Over 24, 2013',
 'Overall Homeless Individuals, 2013',
 'Overall Homeless Individuals - Under 18, 2013',
 'Overall Homeless Individuals - Age 18 to 24, 2013',
 'Overall Homeless Individuals - Over 24, 2013',
 'Sheltered ES Homeless Individuals, 2013',
 'Sheltered ES Homeless Individuals - Under 18, 2013',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2013',
 'Sheltered ES Homeless Individuals - Over 24, 2013',
 'Sheltered TH Homeless Individuals, 2013',
 'Sheltered TH Homeless Individuals - Under 18, 2013',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2013',
 'Sheltered TH Homeless Individuals - Over 24, 2013',
 'Sheltered SH Homeless Individuals, 2013',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2013',
 'Sheltered SH Homeless Individuals - Over 24, 2013',
 'Sheltered Total Homeless Individuals, 2013',
 'Sheltered Total Homeless Individuals - Under 18, 2013',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2013',
 'Sheltered Total Homeless Individuals - Over 24, 2013',
 'Unsheltered Homeless Individuals, 2013',
 'Unsheltered Homeless Individuals - Under 18, 2013',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2013',
 'Unsheltered Homeless Individuals - Over 24, 2013',
 'Overall Homeless People in Families, 2013',
 'Overall Homeless People in Families - Under 18, 2013',
 'Overall Homeless People in Families - Age 18 to 24, 2013',
 'Overall Homeless People in Families - Over 24, 2013',
 'Sheltered ES Homeless People in Families, 2013',
 'Sheltered ES Homeless People in Families - Under 18, 2013',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2013',
 'Sheltered ES Homeless People in Families - Over 24, 2013',
 'Sheltered TH Homeless People in Families, 2013',
 'Sheltered TH Homeless People in Families - Under 18, 2013',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2013',
 'Sheltered TH Homeless People in Families - Over 24, 2013',
 'Sheltered Total Homeless People in Families, 2013',
 'Sheltered Total Homeless People in Families - Under 18, 2013',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2013',
 'Sheltered Total Homeless People in Families - Over 24, 2013',
 'Unsheltered Homeless People in Families, 2013',
 'Unsheltered Homeless People in Families - Under 18, 2013',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2013',
 'Unsheltered Homeless People in Families - Over 24, 2013',
 'Overall Homeless Family Households, 2013',
 'Sheltered ES Homeless Family Households, 2013',
 'Sheltered TH Homeless Family Households, 2013',
 'Sheltered Total Homeless Family Households, 2013',
 'Unsheltered Homeless Family Households, 2013',
 'Overall Chronically Homeless, 2013',
 'Sheltered ES Chronically Homeless, 2013',
 'Sheltered SH Chronically Homeless, 2013',
 'Sheltered Total Chronically Homeless, 2013',
 'Unsheltered Chronically Homeless, 2013',
 'Overall Chronically Homeless Individuals, 2013',
 'Sheltered ES Chronically Homeless Individuals, 2013',
 'Sheltered SH Chronically Homeless Individuals, 2013',
 'Sheltered Total Chronically Homeless Individuals, 2013',
 'Unsheltered Chronically Homeless Individuals, 2013',
 'Overall Chronically Homeless People in Families, 2013',
 'Sheltered ES Chronically Homeless People in Families, 2013',
 'Sheltered Total Chronically Homeless People in Families, 2013',
 'Unsheltered Chronically Homeless People in Families, 2013',
 'Overall Homeless Veterans, 2013',
 'Overall Homeless Veterans - Female, 2013',
 'Sheltered Total Homeless Veterans, 2013',
 'Sheltered Total Homeless Veterans - Female, 2013',
 'Unsheltered Homeless Veterans, 2013',
 'Unsheltered Homeless Veterans - Female, 2013',
 'Year']

In [95]:
# Rearrange column names so year is second
new_cols_2013 = ['State', 'Year',
 'Number of CoCs',
 'Overall Homeless, 2013',
 'Overall Homeless - Under 18, 2013',
 'Overall Homeless - Age 18 to 24, 2013',
 'Overall Homeless - Over 24, 2013',
 'Sheltered ES Homeless, 2013',
 'Sheltered ES Homeless - Under 18, 2013',
 'Sheltered ES Homeless - Age 18 to 24, 2013',
 'Sheltered ES Homeless - Over 24, 2013',
 'Sheltered TH Homeless, 2013',
 'Sheltered TH Homeless - Under 18, 2013',
 'Sheltered TH Homeless - Age 18 to 24, 2013',
 'Sheltered TH Homeless - Over 24, 2013',
 'Sheltered SH Homeless, 2013',
 'Sheltered SH Homeless - Age 18 to 24, 2013',
 'Sheltered SH Homeless - Over 24, 2013',
 'Sheltered Total Homeless, 2013',
 'Sheltered Total Homeless - Under 18, 2013',
 'Sheltered Total Homeless - Age 18 to 24, 2013',
 'Sheltered Total Homeless - Over 24, 2013',
 'Unsheltered Homeless, 2013',
 'Unsheltered Homeless - Under 18, 2013',
 'Unsheltered Homeless - Age 18 to 24, 2013',
 'Unsheltered Homeless - Over 24, 2013',
 'Overall Homeless Individuals, 2013',
 'Overall Homeless Individuals - Under 18, 2013',
 'Overall Homeless Individuals - Age 18 to 24, 2013',
 'Overall Homeless Individuals - Over 24, 2013',
 'Sheltered ES Homeless Individuals, 2013',
 'Sheltered ES Homeless Individuals - Under 18, 2013',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2013',
 'Sheltered ES Homeless Individuals - Over 24, 2013',
 'Sheltered TH Homeless Individuals, 2013',
 'Sheltered TH Homeless Individuals - Under 18, 2013',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2013',
 'Sheltered TH Homeless Individuals - Over 24, 2013',
 'Sheltered SH Homeless Individuals, 2013',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2013',
 'Sheltered SH Homeless Individuals - Over 24, 2013',
 'Sheltered Total Homeless Individuals, 2013',
 'Sheltered Total Homeless Individuals - Under 18, 2013',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2013',
 'Sheltered Total Homeless Individuals - Over 24, 2013',
 'Unsheltered Homeless Individuals, 2013',
 'Unsheltered Homeless Individuals - Under 18, 2013',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2013',
 'Unsheltered Homeless Individuals - Over 24, 2013',
 'Overall Homeless People in Families, 2013',
 'Overall Homeless People in Families - Under 18, 2013',
 'Overall Homeless People in Families - Age 18 to 24, 2013',
 'Overall Homeless People in Families - Over 24, 2013',
 'Sheltered ES Homeless People in Families, 2013',
 'Sheltered ES Homeless People in Families - Under 18, 2013',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2013',
 'Sheltered ES Homeless People in Families - Over 24, 2013',
 'Sheltered TH Homeless People in Families, 2013',
 'Sheltered TH Homeless People in Families - Under 18, 2013',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2013',
 'Sheltered TH Homeless People in Families - Over 24, 2013',
 'Sheltered Total Homeless People in Families, 2013',
 'Sheltered Total Homeless People in Families - Under 18, 2013',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2013',
 'Sheltered Total Homeless People in Families - Over 24, 2013',
 'Unsheltered Homeless People in Families, 2013',
 'Unsheltered Homeless People in Families - Under 18, 2013',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2013',
 'Unsheltered Homeless People in Families - Over 24, 2013',
 'Overall Homeless Family Households, 2013',
 'Sheltered ES Homeless Family Households, 2013',
 'Sheltered TH Homeless Family Households, 2013',
 'Sheltered Total Homeless Family Households, 2013',
 'Unsheltered Homeless Family Households, 2013',
 'Overall Chronically Homeless, 2013',
 'Sheltered ES Chronically Homeless, 2013',
 'Sheltered SH Chronically Homeless, 2013',
 'Sheltered Total Chronically Homeless, 2013',
 'Unsheltered Chronically Homeless, 2013',
 'Overall Chronically Homeless Individuals, 2013',
 'Sheltered ES Chronically Homeless Individuals, 2013',
 'Sheltered SH Chronically Homeless Individuals, 2013',
 'Sheltered Total Chronically Homeless Individuals, 2013',
 'Unsheltered Chronically Homeless Individuals, 2013',
 'Overall Chronically Homeless People in Families, 2013',
 'Sheltered ES Chronically Homeless People in Families, 2013',
 'Sheltered Total Chronically Homeless People in Families, 2013',
 'Unsheltered Chronically Homeless People in Families, 2013',
 'Overall Homeless Veterans, 2013',
 'Overall Homeless Veterans - Female, 2013',
 'Sheltered Total Homeless Veterans, 2013',
 'Sheltered Total Homeless Veterans - Female, 2013',
 'Unsheltered Homeless Veterans, 2013',
 'Unsheltered Homeless Veterans - Female, 2013'
 ]

In [96]:
# Apply rearranged column names
data_2013_df = data_2013_df[new_cols_2013]
data_2013_df.head()

,State,Year,Number of CoCs,"Overall Homeless, 2013","Overall Homeless - Under 18, 2013","Overall Homeless - Age 18 to 24, 2013","Overall Homeless - Over 24, 2013","Sheltered ES Homeless, 2013","Sheltered ES Homeless - Under 18, 2013","Sheltered ES Homeless - Age 18 to 24, 2013",...,"Overall Chronically Homeless People in Families, 2013","Sheltered ES Chronically Homeless People in Families, 2013","Sheltered Total Chronically Homeless People in Families, 2013","Unsheltered Chronically Homeless People in Families, 2013","Overall Homeless Veterans, 2013","Overall Homeless Veterans - Female, 2013","Sheltered Total Homeless Veterans, 2013","Sheltered Total Homeless Veterans - Female, 2013","Unsheltered Homeless Veterans, 2013","Unsheltered Homeless Veterans - Female, 2013"
0,AK,2013,2.0,"1,946",369,189,"1,388","1,137",195,103,...,18,14,14,4,210,9,188,8,22,1
1,AL,2013,8.0,"4,689",694,506,"3,489","1,555",215,165,...,90,46,46,44,511,25,363,16,148,9
2,AR,2013,6.0,"3,812",429,350,"3,033","1,037",275,96,...,37,29,29,8,462,11,326,9,136,2
3,AS,2013,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2013,3.0,"10,562","2,598",942,"7,022","3,893",945,298,...,124,70,70,54,"1,222",75,901,58,321,17

In [97]:
# rename columns to remove year from each column title
dict = {
 'Overall Homeless, 2013':'Overall Homeless',
 'Overall Homeless - Under 18, 2013':'Overall Homeless - Under 18',
 'Overall Homeless - Age 18 to 24, 2013':'Overall Homeless - Age 18 to 24',
 'Overall Homeless - Over 24, 2013':'Overall Homeless - Over 24',
 'Sheltered ES Homeless, 2013':'Sheltered ES Homeless',
 'Sheltered ES Homeless - Under 18, 2013':'Sheltered ES Homeless - Under 18',
 'Sheltered ES Homeless - Age 18 to 24, 2013':'Sheltered ES Homeless - Age 18 to 24',
 'Sheltered ES Homeless - Over 24, 2013':'Sheltered ES Homeless - Over 24',
 'Sheltered TH Homeless, 2013':'Sheltered TH Homeless',
 'Sheltered TH Homeless - Under 18, 2013':'Sheltered TH Homeless - Under 18',
 'Sheltered TH Homeless - Age 18 to 24, 2013':'Sheltered TH Homeless - Age 18 to 24',
 'Sheltered TH Homeless - Over 24, 2013':'Sheltered TH Homeless - Over 24',
 'Sheltered SH Homeless, 2013':'Sheltered SH Homeless',
 'Sheltered SH Homeless - Age 18 to 24, 2013':'Sheltered SH Homeless - Age 18 to 24',
 'Sheltered SH Homeless - Over 24, 2013':'Sheltered SH Homeless - Over 24',
 'Sheltered Total Homeless, 2013':'Sheltered Total Homeless',
 'Sheltered Total Homeless - Under 18, 2013':'Sheltered Total Homeless - Under 18',
 'Sheltered Total Homeless - Age 18 to 24, 2013':'Sheltered Total Homeless - Age 18 to 24',
 'Sheltered Total Homeless - Over 24, 2013':'Sheltered Total Homeless - Over 24',
 'Unsheltered Homeless, 2013':'Unsheltered Homeless',
 'Unsheltered Homeless - Under 18, 2013':'Unsheltered Homeless - Under 18',
 'Unsheltered Homeless - Age 18 to 24, 2013':'Unsheltered Homeless - Age 18 to 24',
 'Unsheltered Homeless - Over 24, 2013':'Unsheltered Homeless - Over 24',
 'Overall Homeless Individuals, 2013':'Overall Homeless Individuals',
 'Overall Homeless Individuals - Under 18, 2013':'Overall Homeless Individuals - Under 18',
 'Overall Homeless Individuals - Age 18 to 24, 2013':'Overall Homeless Individuals - Age 18 to 24',
 'Overall Homeless Individuals - Over 24, 2013':'Overall Homeless Individuals - Over 24',
 'Sheltered ES Homeless Individuals, 2013':'Sheltered ES Homeless Individuals',
 'Sheltered ES Homeless Individuals - Under 18, 2013':'Sheltered ES Homeless Individuals - Under 18',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2013':'Sheltered ES Homeless Individuals - Age 18 to 24',
 'Sheltered ES Homeless Individuals - Over 24, 2013':'Sheltered ES Homeless Individuals - Over 24',
 'Sheltered TH Homeless Individuals, 2013':'Sheltered TH Homeless Individuals',
 'Sheltered TH Homeless Individuals - Under 18, 2013':'Sheltered TH Homeless Individuals - Under 18',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2013':'Sheltered TH Homeless Individuals - Age 18 to 24',
 'Sheltered TH Homeless Individuals - Over 24, 2013':'Sheltered TH Homeless Individuals - Over 24',
 'Sheltered SH Homeless Individuals, 2013':'Sheltered SH Homeless Individuals',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2013':'Sheltered SH Homeless Individuals - Age 18 to 24',
 'Sheltered SH Homeless Individuals - Over 24, 2013':'Sheltered SH Homeless Individuals - Over 24',
 'Sheltered Total Homeless Individuals, 2013':'Sheltered Total Homeless Individuals',
 'Sheltered Total Homeless Individuals - Under 18, 2013':'Sheltered Total Homeless Individuals - Under 18',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2013':'Sheltered Total Homeless Individuals - Age 18 to 24',
 'Sheltered Total Homeless Individuals - Over 24, 2013':'Sheltered Total Homeless Individuals - Over 24',
 'Unsheltered Homeless Individuals, 2013':'Unsheltered Homeless Individuals',
 'Unsheltered Homeless Individuals - Under 18, 2013':'Unsheltered Homeless Individuals - Under 18',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2013':'Unsheltered Homeless Individuals - Age 18 to 24',
 'Unsheltered Homeless Individuals - Over 24, 2013':'Unsheltered Homeless Individuals - Over 24',
 'Overall Homeless People in Families, 2013':'Overall Homeless People in Families',
 'Overall Homeless People in Families - Under 18, 2013':'Overall Homeless People in Families - Under 18',
 'Overall Homeless People in Families - Age 18 to 24, 2013':'Overall Homeless People in Families - Age 18 to 24',
 'Overall Homeless People in Families - Over 24, 2013':'Overall Homeless People in Families - Over 24',
 'Sheltered ES Homeless People in Families, 2013':'Sheltered ES Homeless People in Families',
 'Sheltered ES Homeless People in Families - Under 18, 2013':'Sheltered ES Homeless People in Families - Under 18',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2013':'Sheltered ES Homeless People in Families - Age 18 to 24',
 'Sheltered ES Homeless People in Families - Over 24, 2013':'Sheltered ES Homeless People in Families - Over 24',
 'Sheltered TH Homeless People in Families, 2013':'Sheltered TH Homeless People in Families',
 'Sheltered TH Homeless People in Families - Under 18, 2013':'Sheltered TH Homeless People in Families - Under 18',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2013':'Sheltered TH Homeless People in Families - Age 18 to 24',
 'Sheltered TH Homeless People in Families - Over 24, 2013':'Sheltered TH Homeless People in Families - Over 24',
 'Sheltered Total Homeless People in Families, 2013':'Sheltered Total Homeless People in Families',
 'Sheltered Total Homeless People in Families - Under 18, 2013':'Sheltered Total Homeless People in Families - Under 18',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2013':'Sheltered Total Homeless People in Families - Age 18 to 24',
 'Sheltered Total Homeless People in Families - Over 24, 2013':'Sheltered Total Homeless People in Families - Over 24',
 'Unsheltered Homeless People in Families, 2013':'Unsheltered Homeless People in Families',
 'Unsheltered Homeless People in Families - Under 18, 2013':'Unsheltered Homeless People in Families - Under 18',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2013':'Unsheltered Homeless People in Families - Age 18 to 24',
 'Unsheltered Homeless People in Families - Over 24, 2013':'Unsheltered Homeless People in Families - Over 24',
 'Overall Homeless Family Households, 2013':'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households, 2013':'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households, 2013':'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households, 2013':'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households, 2013':'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless, 2013':'Overall Chronically Homeless',
 'Sheltered ES Chronically Homeless, 2013':'Sheltered ES Chronically Homeless',
 'Sheltered SH Chronically Homeless, 2013':'Sheltered SH Chronically Homeless',
 'Sheltered Total Chronically Homeless, 2013':'Sheltered Total Chronically Homeless',
 'Unsheltered Chronically Homeless, 2013':'Unsheltered Chronically Homeless',
 'Overall Chronically Homeless Individuals, 2013':'Overall Chronically Homeless Individuals',
 'Sheltered ES Chronically Homeless Individuals, 2013':'Sheltered ES Chronically Homeless Individuals',
 'Sheltered SH Chronically Homeless Individuals, 2013':'Sheltered SH Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals, 2013':'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals, 2013':'Unsheltered Chronically Homeless Individuals',
 'Overall Chronically Homeless People in Families, 2013':'Overall Chronically Homeless People in Families',
 'Sheltered ES Chronically Homeless People in Families, 2013':'Sheltered ES Chronically Homeless People in Families',
 'Sheltered Total Chronically Homeless People in Families, 2013':'Sheltered Total Chronically Homeless People in Families',
 'Unsheltered Chronically Homeless People in Families, 2013':'Unsheltered Chronically Homeless People in Families',
 'Overall Homeless Veterans, 2013':'Overall Homeless Veterans',
 'Overall Homeless Veterans - Female, 2013':'Overall Homeless Veterans - Female',
 'Sheltered Total Homeless Veterans, 2013':'Sheltered Total Homeless Veterans',
 'Sheltered Total Homeless Veterans - Female, 2013':'Sheltered Total Homeless Veterans - Female',
 'Unsheltered Homeless Veterans, 2013':'Unsheltered Homeless Veterans',
 'Unsheltered Homeless Veterans - Female, 2013':'Unsheltered Homeless Veterans - Female'
       }
data_2013_df.rename(columns=dict, inplace=True)

In [98]:
data_2013_df.head()

,State,Year,Number of CoCs,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Sheltered ES Homeless,Sheltered ES Homeless - Under 18,Sheltered ES Homeless - Age 18 to 24,...,Overall Chronically Homeless People in Families,Sheltered ES Chronically Homeless People in Families,Sheltered Total Chronically Homeless People in Families,Unsheltered Chronically Homeless People in Families,Overall Homeless Veterans,Overall Homeless Veterans - Female,Sheltered Total Homeless Veterans,Sheltered Total Homeless Veterans - Female,Unsheltered Homeless Veterans,Unsheltered Homeless Veterans - Female
0,AK,2013,2.0,"1,946",369,189,"1,388","1,137",195,103,...,18,14,14,4,210,9,188,8,22,1
1,AL,2013,8.0,"4,689",694,506,"3,489","1,555",215,165,...,90,46,46,44,511,25,363,16,148,9
2,AR,2013,6.0,"3,812",429,350,"3,033","1,037",275,96,...,37,29,29,8,462,11,326,9,136,2
3,AS,2013,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2013,3.0,"10,562","2,598",942,"7,022","3,893",945,298,...,124,70,70,54,"1,222",75,901,58,321,17

In [99]:
# Export df to sql table
data_2013_df.to_sql(name='data_2013', con=engine, if_exists='replace')

# 2014

In [100]:
# Import csv into pandas dataframe 2014
data_2014 = pd.read_csv("Resources/2014-PIT-Counts-by-State.csv")
data_2014_df = pd.DataFrame(data_2014)
data_2014_df.head()

,State,Number of CoCs,"Overall Homeless, 2014","Overall Homeless - Under 18, 2014","Overall Homeless - Age 18 to 24, 2014","Overall Homeless - Over 24, 2014","Sheltered ES Homeless, 2014","Sheltered ES Homeless - Under 18, 2014","Sheltered ES Homeless - Age 18 to 24, 2014","Sheltered ES Homeless - Over 24, 2014",...,"Overall Chronically Homeless People in Families, 2014","Sheltered ES Chronically Homeless People in Families, 2014","Sheltered Total Chronically Homeless People in Families, 2014","Unsheltered Chronically Homeless People in Families, 2014","Overall Homeless Veterans, 2014","Overall Homeless Veterans - Female, 2014","Sheltered Total Homeless Veterans, 2014","Sheltered Total Homeless Veterans - Female, 2014","Unsheltered Homeless Veterans, 2014","Unsheltered Homeless Veterans - Female, 2014"
0,AK,2.0,"1,784",397,202,"1,185","1,139",205,118,816,...,24,18,18,6,178,7,160,7,18,0
1,AL,8.0,"4,561",772,366,"3,423","1,851",228,157,"1,466",...,111,38,38,73,542,49,450,38,92,11
2,AR,6.0,"2,936",355,315,"2,266","1,021",125,117,779,...,3,3,3,0,361,71,220,68,141,3
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,"10,495","2,679","1,024","6,792","4,291","1,052",372,"2,867",...,55,13,13,42,858,62,635,50,223,12

In [101]:
# Create column for the year and set to 2010
data_2014_df["Year"] = 2014
data_2014_df.head()

,State,Number of CoCs,"Overall Homeless, 2014","Overall Homeless - Under 18, 2014","Overall Homeless - Age 18 to 24, 2014","Overall Homeless - Over 24, 2014","Sheltered ES Homeless, 2014","Sheltered ES Homeless - Under 18, 2014","Sheltered ES Homeless - Age 18 to 24, 2014","Sheltered ES Homeless - Over 24, 2014",...,"Sheltered ES Chronically Homeless People in Families, 2014","Sheltered Total Chronically Homeless People in Families, 2014","Unsheltered Chronically Homeless People in Families, 2014","Overall Homeless Veterans, 2014","Overall Homeless Veterans - Female, 2014","Sheltered Total Homeless Veterans, 2014","Sheltered Total Homeless Veterans - Female, 2014","Unsheltered Homeless Veterans, 2014","Unsheltered Homeless Veterans - Female, 2014",Year
0,AK,2.0,"1,784",397,202,"1,185","1,139",205,118,816,...,18,18,6,178,7,160,7,18,0,2014
1,AL,8.0,"4,561",772,366,"3,423","1,851",228,157,"1,466",...,38,38,73,542,49,450,38,92,11,2014
2,AR,6.0,"2,936",355,315,"2,266","1,021",125,117,779,...,3,3,0,361,71,220,68,141,3,2014
3,AS,0.0,,,,,,,,,...,,,,,,,,,,2014
4,AZ,3.0,"10,495","2,679","1,024","6,792","4,291","1,052",372,"2,867",...,13,13,42,858,62,635,50,223,12,2014

In [102]:
# Get Column Names
cols_2014 = data_2014_df.columns.tolist()
cols_2014

['State',
 'Number of CoCs',
 'Overall Homeless, 2014',
 'Overall Homeless - Under 18, 2014',
 'Overall Homeless - Age 18 to 24, 2014',
 'Overall Homeless - Over 24, 2014',
 'Sheltered ES Homeless, 2014',
 'Sheltered ES Homeless - Under 18, 2014',
 'Sheltered ES Homeless - Age 18 to 24, 2014',
 'Sheltered ES Homeless - Over 24, 2014',
 'Sheltered TH Homeless, 2014',
 'Sheltered TH Homeless - Under 18, 2014',
 'Sheltered TH Homeless - Age 18 to 24, 2014',
 'Sheltered TH Homeless - Over 24, 2014',
 'Sheltered SH Homeless, 2014',
 'Sheltered SH Homeless - Age 18 to 24, 2014',
 'Sheltered SH Homeless - Over 24, 2014',
 'Sheltered Total Homeless, 2014',
 'Sheltered Total Homeless - Under 18, 2014',
 'Sheltered Total Homeless - Age 18 to 24, 2014',
 'Sheltered Total Homeless - Over 24, 2014',
 'Unsheltered Homeless, 2014',
 'Unsheltered Homeless - Under 18, 2014',
 'Unsheltered Homeless - Age 18 to 24, 2014',
 'Unsheltered Homeless - Over 24, 2014',
 'Overall Homeless Individuals, 2014',
 'Overall Homeless Individuals - Under 18, 2014',
 'Overall Homeless Individuals - Age 18 to 24, 2014',
 'Overall Homeless Individuals - Over 24, 2014',
 'Sheltered ES Homeless Individuals, 2014',
 'Sheltered ES Homeless Individuals - Under 18, 2014',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2014',
 'Sheltered ES Homeless Individuals - Over 24, 2014',
 'Sheltered TH Homeless Individuals, 2014',
 'Sheltered TH Homeless Individuals - Under 18, 2014',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2014',
 'Sheltered TH Homeless Individuals - Over 24, 2014',
 'Sheltered SH Homeless Individuals, 2014',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2014',
 'Sheltered SH Homeless Individuals - Over 24, 2014',
 'Sheltered Total Homeless Individuals, 2014',
 'Sheltered Total Homeless Individuals - Under 18, 2014',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2014',
 'Sheltered Total Homeless Individuals - Over 24, 2014',
 'Unsheltered Homeless Individuals, 2014',
 'Unsheltered Homeless Individuals - Under 18, 2014',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2014',
 'Unsheltered Homeless Individuals - Over 24, 2014',
 'Overall Homeless People in Families, 2014',
 'Overall Homeless People in Families - Under 18, 2014',
 'Overall Homeless People in Families - Age 18 to 24, 2014',
 'Overall Homeless People in Families - Over 24, 2014',
 'Sheltered ES Homeless People in Families, 2014',
 'Sheltered ES Homeless People in Families - Under 18, 2014',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2014',
 'Sheltered ES Homeless People in Families - Over 24, 2014',
 'Sheltered TH Homeless People in Families, 2014',
 'Sheltered TH Homeless People in Families - Under 18, 2014',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2014',
 'Sheltered TH Homeless People in Families - Over 24, 2014',
 'Sheltered Total Homeless People in Families, 2014',
 'Sheltered Total Homeless People in Families - Under 18, 2014',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2014',
 'Sheltered Total Homeless People in Families - Over 24, 2014',
 'Unsheltered Homeless People in Families, 2014',
 'Unsheltered Homeless People in Families - Under 18, 2014',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2014',
 'Unsheltered Homeless People in Families - Over 24, 2014',
 'Overall Homeless Family Households, 2014',
 'Sheltered ES Homeless Family Households, 2014',
 'Sheltered TH Homeless Family Households, 2014',
 'Sheltered Total Homeless Family Households, 2014',
 'Unsheltered Homeless Family Households, 2014',
 'Overall Chronically Homeless, 2014',
 'Sheltered ES Chronically Homeless, 2014',
 'Sheltered SH Chronically Homeless, 2014',
 'Sheltered Total Chronically Homeless, 2014',
 'Unsheltered Chronically Homeless, 2014',
 'Overall Chronically Homeless Individuals, 2014',
 'Sheltered ES Chronically Homeless Individuals, 2014',
 'Sheltered SH Chronically Homeless Individuals, 2014',
 'Sheltered Total Chronically Homeless Individuals, 2014',
 'Unsheltered Chronically Homeless Individuals, 2014',
 'Overall Chronically Homeless People in Families, 2014',
 'Sheltered ES Chronically Homeless People in Families, 2014',
 'Sheltered Total Chronically Homeless People in Families, 2014',
 'Unsheltered Chronically Homeless People in Families, 2014',
 'Overall Homeless Veterans, 2014',
 'Overall Homeless Veterans - Female, 2014',
 'Sheltered Total Homeless Veterans, 2014',
 'Sheltered Total Homeless Veterans - Female, 2014',
 'Unsheltered Homeless Veterans, 2014',
 'Unsheltered Homeless Veterans - Female, 2014',
 'Year']

In [103]:
# Rearrange column names so year is second
new_cols_2014 = ['State', 'Year',
 'Number of CoCs',
 'Overall Homeless, 2014',
 'Overall Homeless - Under 18, 2014',
 'Overall Homeless - Age 18 to 24, 2014',
 'Overall Homeless - Over 24, 2014',
 'Sheltered ES Homeless, 2014',
 'Sheltered ES Homeless - Under 18, 2014',
 'Sheltered ES Homeless - Age 18 to 24, 2014',
 'Sheltered ES Homeless - Over 24, 2014',
 'Sheltered TH Homeless, 2014',
 'Sheltered TH Homeless - Under 18, 2014',
 'Sheltered TH Homeless - Age 18 to 24, 2014',
 'Sheltered TH Homeless - Over 24, 2014',
 'Sheltered SH Homeless, 2014',
 'Sheltered SH Homeless - Age 18 to 24, 2014',
 'Sheltered SH Homeless - Over 24, 2014',
 'Sheltered Total Homeless, 2014',
 'Sheltered Total Homeless - Under 18, 2014',
 'Sheltered Total Homeless - Age 18 to 24, 2014',
 'Sheltered Total Homeless - Over 24, 2014',
 'Unsheltered Homeless, 2014',
 'Unsheltered Homeless - Under 18, 2014',
 'Unsheltered Homeless - Age 18 to 24, 2014',
 'Unsheltered Homeless - Over 24, 2014',
 'Overall Homeless Individuals, 2014',
 'Overall Homeless Individuals - Under 18, 2014',
 'Overall Homeless Individuals - Age 18 to 24, 2014',
 'Overall Homeless Individuals - Over 24, 2014',
 'Sheltered ES Homeless Individuals, 2014',
 'Sheltered ES Homeless Individuals - Under 18, 2014',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2014',
 'Sheltered ES Homeless Individuals - Over 24, 2014',
 'Sheltered TH Homeless Individuals, 2014',
 'Sheltered TH Homeless Individuals - Under 18, 2014',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2014',
 'Sheltered TH Homeless Individuals - Over 24, 2014',
 'Sheltered SH Homeless Individuals, 2014',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2014',
 'Sheltered SH Homeless Individuals - Over 24, 2014',
 'Sheltered Total Homeless Individuals, 2014',
 'Sheltered Total Homeless Individuals - Under 18, 2014',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2014',
 'Sheltered Total Homeless Individuals - Over 24, 2014',
 'Unsheltered Homeless Individuals, 2014',
 'Unsheltered Homeless Individuals - Under 18, 2014',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2014',
 'Unsheltered Homeless Individuals - Over 24, 2014',
 'Overall Homeless People in Families, 2014',
 'Overall Homeless People in Families - Under 18, 2014',
 'Overall Homeless People in Families - Age 18 to 24, 2014',
 'Overall Homeless People in Families - Over 24, 2014',
 'Sheltered ES Homeless People in Families, 2014',
 'Sheltered ES Homeless People in Families - Under 18, 2014',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2014',
 'Sheltered ES Homeless People in Families - Over 24, 2014',
 'Sheltered TH Homeless People in Families, 2014',
 'Sheltered TH Homeless People in Families - Under 18, 2014',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2014',
 'Sheltered TH Homeless People in Families - Over 24, 2014',
 'Sheltered Total Homeless People in Families, 2014',
 'Sheltered Total Homeless People in Families - Under 18, 2014',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2014',
 'Sheltered Total Homeless People in Families - Over 24, 2014',
 'Unsheltered Homeless People in Families, 2014',
 'Unsheltered Homeless People in Families - Under 18, 2014',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2014',
 'Unsheltered Homeless People in Families - Over 24, 2014',
 'Overall Homeless Family Households, 2014',
 'Sheltered ES Homeless Family Households, 2014',
 'Sheltered TH Homeless Family Households, 2014',
 'Sheltered Total Homeless Family Households, 2014',
 'Unsheltered Homeless Family Households, 2014',
 'Overall Chronically Homeless, 2014',
 'Sheltered ES Chronically Homeless, 2014',
 'Sheltered SH Chronically Homeless, 2014',
 'Sheltered Total Chronically Homeless, 2014',
 'Unsheltered Chronically Homeless, 2014',
 'Overall Chronically Homeless Individuals, 2014',
 'Sheltered ES Chronically Homeless Individuals, 2014',
 'Sheltered SH Chronically Homeless Individuals, 2014',
 'Sheltered Total Chronically Homeless Individuals, 2014',
 'Unsheltered Chronically Homeless Individuals, 2014',
 'Overall Chronically Homeless People in Families, 2014',
 'Sheltered ES Chronically Homeless People in Families, 2014',
 'Sheltered Total Chronically Homeless People in Families, 2014',
 'Unsheltered Chronically Homeless People in Families, 2014',
 'Overall Homeless Veterans, 2014',
 'Overall Homeless Veterans - Female, 2014',
 'Sheltered Total Homeless Veterans, 2014',
 'Sheltered Total Homeless Veterans - Female, 2014',
 'Unsheltered Homeless Veterans, 2014',
 'Unsheltered Homeless Veterans - Female, 2014'
 ]

In [104]:
# Apply rearranged column names
data_2014_df = data_2014_df[new_cols_2014]
data_2014_df.head()

,State,Year,Number of CoCs,"Overall Homeless, 2014","Overall Homeless - Under 18, 2014","Overall Homeless - Age 18 to 24, 2014","Overall Homeless - Over 24, 2014","Sheltered ES Homeless, 2014","Sheltered ES Homeless - Under 18, 2014","Sheltered ES Homeless - Age 18 to 24, 2014",...,"Overall Chronically Homeless People in Families, 2014","Sheltered ES Chronically Homeless People in Families, 2014","Sheltered Total Chronically Homeless People in Families, 2014","Unsheltered Chronically Homeless People in Families, 2014","Overall Homeless Veterans, 2014","Overall Homeless Veterans - Female, 2014","Sheltered Total Homeless Veterans, 2014","Sheltered Total Homeless Veterans - Female, 2014","Unsheltered Homeless Veterans, 2014","Unsheltered Homeless Veterans - Female, 2014"
0,AK,2014,2.0,"1,784",397,202,"1,185","1,139",205,118,...,24,18,18,6,178,7,160,7,18,0
1,AL,2014,8.0,"4,561",772,366,"3,423","1,851",228,157,...,111,38,38,73,542,49,450,38,92,11
2,AR,2014,6.0,"2,936",355,315,"2,266","1,021",125,117,...,3,3,3,0,361,71,220,68,141,3
3,AS,2014,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2014,3.0,"10,495","2,679","1,024","6,792","4,291","1,052",372,...,55,13,13,42,858,62,635,50,223,12

In [105]:
# rename columns to remove year from each column title
dict = {
 'Overall Homeless, 2014':'Overall Homeless',
 'Overall Homeless - Under 18, 2014':'Overall Homeless - Under 18',
 'Overall Homeless - Age 18 to 24, 2014':'Overall Homeless - Age 18 to 24',
 'Overall Homeless - Over 24, 2014':'Overall Homeless - Over 24',
 'Sheltered ES Homeless, 2014':'Sheltered ES Homeless',
 'Sheltered ES Homeless - Under 18, 2014':'Sheltered ES Homeless - Under 18',
 'Sheltered ES Homeless - Age 18 to 24, 2014':'Sheltered ES Homeless - Age 18 to 24',
 'Sheltered ES Homeless - Over 24, 2014':'Sheltered ES Homeless - Over 24',
 'Sheltered TH Homeless, 2014':'Sheltered TH Homeless',
 'Sheltered TH Homeless - Under 18, 2014':'Sheltered TH Homeless - Under 18',
 'Sheltered TH Homeless - Age 18 to 24, 2014':'Sheltered TH Homeless - Age 18 to 24',
 'Sheltered TH Homeless - Over 24, 2014':'Sheltered TH Homeless - Over 24',
 'Sheltered SH Homeless, 2014':'Sheltered SH Homeless',
 'Sheltered SH Homeless - Age 18 to 24, 2014':'Sheltered SH Homeless - Age 18 to 24',
 'Sheltered SH Homeless - Over 24, 2014':'Sheltered SH Homeless - Over 24',
 'Sheltered Total Homeless, 2014':'Sheltered Total Homeless',
 'Sheltered Total Homeless - Under 18, 2014':'Sheltered Total Homeless - Under 18',
 'Sheltered Total Homeless - Age 18 to 24, 2014':'Sheltered Total Homeless - Age 18 to 24',
 'Sheltered Total Homeless - Over 24, 2014':'Sheltered Total Homeless - Over 24',
 'Unsheltered Homeless, 2014':'Unsheltered Homeless',
 'Unsheltered Homeless - Under 18, 2014':'Unsheltered Homeless - Under 18',
 'Unsheltered Homeless - Age 18 to 24, 2014':'Unsheltered Homeless - Age 18 to 24',
 'Unsheltered Homeless - Over 24, 2014':'Unsheltered Homeless - Over 24',
 'Overall Homeless Individuals, 2014':'Overall Homeless Individuals',
 'Overall Homeless Individuals - Under 18, 2014':'Overall Homeless Individuals - Under 18',
 'Overall Homeless Individuals - Age 18 to 24, 2014':'Overall Homeless Individuals - Age 18 to 24',
 'Overall Homeless Individuals - Over 24, 2014':'Overall Homeless Individuals - Over 24',
 'Sheltered ES Homeless Individuals, 2014':'Sheltered ES Homeless Individuals',
 'Sheltered ES Homeless Individuals - Under 18, 2014':'Sheltered ES Homeless Individuals - Under 18',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2014':'Sheltered ES Homeless Individuals - Age 18 to 24',
 'Sheltered ES Homeless Individuals - Over 24, 2014':'Sheltered ES Homeless Individuals - Over 24',
 'Sheltered TH Homeless Individuals, 2014':'Sheltered TH Homeless Individuals',
 'Sheltered TH Homeless Individuals - Under 18, 2014':'Sheltered TH Homeless Individuals - Under 18',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2014':'Sheltered TH Homeless Individuals - Age 18 to 24',
 'Sheltered TH Homeless Individuals - Over 24, 2014':'Sheltered TH Homeless Individuals - Over 24',
 'Sheltered SH Homeless Individuals, 2014':'Sheltered SH Homeless Individuals',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2014':'Sheltered SH Homeless Individuals - Age 18 to 24',
 'Sheltered SH Homeless Individuals - Over 24, 2014':'Sheltered SH Homeless Individuals - Over 24',
 'Sheltered Total Homeless Individuals, 2014':'Sheltered Total Homeless Individuals',
 'Sheltered Total Homeless Individuals - Under 18, 2014':'Sheltered Total Homeless Individuals - Under 18',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2014':'Sheltered Total Homeless Individuals - Age 18 to 24',
 'Sheltered Total Homeless Individuals - Over 24, 2014':'Sheltered Total Homeless Individuals - Over 24',
 'Unsheltered Homeless Individuals, 2014':'Unsheltered Homeless Individuals',
 'Unsheltered Homeless Individuals - Under 18, 2014':'Unsheltered Homeless Individuals - Under 18',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2014':'Unsheltered Homeless Individuals - Age 18 to 24',
 'Unsheltered Homeless Individuals - Over 24, 2014':'Unsheltered Homeless Individuals - Over 24',
 'Overall Homeless People in Families, 2014':'Overall Homeless People in Families',
 'Overall Homeless People in Families - Under 18, 2014':'Overall Homeless People in Families - Under 18',
 'Overall Homeless People in Families - Age 18 to 24, 2014':'Overall Homeless People in Families - Age 18 to 24',
 'Overall Homeless People in Families - Over 24, 2014':'Overall Homeless People in Families - Over 24',
 'Sheltered ES Homeless People in Families, 2014':'Sheltered ES Homeless People in Families',
 'Sheltered ES Homeless People in Families - Under 18, 2014':'Sheltered ES Homeless People in Families - Under 18',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2014':'Sheltered ES Homeless People in Families - Age 18 to 24',
 'Sheltered ES Homeless People in Families - Over 24, 2014':'Sheltered ES Homeless People in Families - Over 24',
 'Sheltered TH Homeless People in Families, 2014':'Sheltered TH Homeless People in Families',
 'Sheltered TH Homeless People in Families - Under 18, 2014':'Sheltered TH Homeless People in Families - Under 18',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2014':'Sheltered TH Homeless People in Families - Age 18 to 24',
 'Sheltered TH Homeless People in Families - Over 24, 2014':'Sheltered TH Homeless People in Families - Over 24',
 'Sheltered Total Homeless People in Families, 2014':'Sheltered Total Homeless People in Families',
 'Sheltered Total Homeless People in Families - Under 18, 2014':'Sheltered Total Homeless People in Families - Under 18',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2014':'Sheltered Total Homeless People in Families - Age 18 to 24',
 'Sheltered Total Homeless People in Families - Over 24, 2014':'Sheltered Total Homeless People in Families - Over 24',
 'Unsheltered Homeless People in Families, 2014':'Unsheltered Homeless People in Families',
 'Unsheltered Homeless People in Families - Under 18, 2014':'Unsheltered Homeless People in Families - Under 18',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2014':'Unsheltered Homeless People in Families - Age 18 to 24',
 'Unsheltered Homeless People in Families - Over 24, 2014':'Unsheltered Homeless People in Families - Over 24',
 'Overall Homeless Family Households, 2014':'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households, 2014':'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households, 2014':'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households, 2014':'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households, 2014':'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless, 2014':'Overall Chronically Homeless',
 'Sheltered ES Chronically Homeless, 2014':'Sheltered ES Chronically Homeless',
 'Sheltered SH Chronically Homeless, 2014':'Sheltered SH Chronically Homeless',
 'Sheltered Total Chronically Homeless, 2014':'Sheltered Total Chronically Homeless',
 'Unsheltered Chronically Homeless, 2014':'Unsheltered Chronically Homeless',
 'Overall Chronically Homeless Individuals, 2014':'Overall Chronically Homeless Individuals',
 'Sheltered ES Chronically Homeless Individuals, 2014':'Sheltered ES Chronically Homeless Individuals',
 'Sheltered SH Chronically Homeless Individuals, 2014':'Sheltered SH Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals, 2014':'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals, 2014':'Unsheltered Chronically Homeless Individuals',
 'Overall Chronically Homeless People in Families, 2014':'Overall Chronically Homeless People in Families',
 'Sheltered ES Chronically Homeless People in Families, 2014':'Sheltered ES Chronically Homeless People in Families',
 'Sheltered Total Chronically Homeless People in Families, 2014':'Sheltered Total Chronically Homeless People in Families',
 'Unsheltered Chronically Homeless People in Families, 2014':'Unsheltered Chronically Homeless People in Families',
 'Overall Homeless Veterans, 2014':'Overall Homeless Veterans',
 'Overall Homeless Veterans - Female, 2014':'Overall Homeless Veterans - Female',
 'Sheltered Total Homeless Veterans, 2014':'Sheltered Total Homeless Veterans',
 'Sheltered Total Homeless Veterans - Female, 2014':'Sheltered Total Homeless Veterans - Female',
 'Unsheltered Homeless Veterans, 2014':'Unsheltered Homeless Veterans',
 'Unsheltered Homeless Veterans - Female, 2014':'Unsheltered Homeless Veterans - Female'
       }
data_2014_df.rename(columns=dict, inplace=True)

In [107]:
data_2014_df.head()

,State,Year,Number of CoCs,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Sheltered ES Homeless,Sheltered ES Homeless - Under 18,Sheltered ES Homeless - Age 18 to 24,...,Overall Chronically Homeless People in Families,Sheltered ES Chronically Homeless People in Families,Sheltered Total Chronically Homeless People in Families,Unsheltered Chronically Homeless People in Families,Overall Homeless Veterans,Overall Homeless Veterans - Female,Sheltered Total Homeless Veterans,Sheltered Total Homeless Veterans - Female,Unsheltered Homeless Veterans,Unsheltered Homeless Veterans - Female
0,AK,2014,2.0,"1,784",397,202,"1,185","1,139",205,118,...,24,18,18,6,178,7,160,7,18,0
1,AL,2014,8.0,"4,561",772,366,"3,423","1,851",228,157,...,111,38,38,73,542,49,450,38,92,11
2,AR,2014,6.0,"2,936",355,315,"2,266","1,021",125,117,...,3,3,3,0,361,71,220,68,141,3
3,AS,2014,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2014,3.0,"10,495","2,679","1,024","6,792","4,291","1,052",372,...,55,13,13,42,858,62,635,50,223,12

In [108]:
# Export df to sql table
data_2014_df.to_sql(name='data_2014', con=engine, if_exists='replace')

# 2015

In [109]:
# Import csv into pandas dataframe 2014
data_2015 = pd.read_csv("Resources/2015-PIT-Counts-by-State.csv")
data_2015_df = pd.DataFrame(data_2015)
data_2015_df.head()

,State,Number of CoCs,"Overall Homeless, 2015","Overall Homeless - Under 18, 2015","Overall Homeless - Age 18 to 24, 2015","Overall Homeless - Over 24, 2015","Overall Homeless - Female, 2015","Overall Homeless - Male, 2015","Overall Homeless - Transgender, 2015","Overall Homeless - Non-Hispanic/Non-Latino, 2015",...,"Overall Homeless Parenting Youth Age 18-24, 2015","Sheltered ES Homeless Parenting Youth Age 18-24, 2015","Sheltered TH Homeless Parenting Youth Age 18-24, 2015","Sheltered Total Homeless Parenting Youth Age 18-24, 2015","Unsheltered Homeless Parenting Youth Age 18-24, 2015","Overall Homeless Children of Parenting Youth, 2015","Sheltered ES Homeless Children of Parenting Youth, 2015","Sheltered TH Homeless Children of Parenting Youth, 2015","Sheltered Total Homeless Children of Parenting Youth, 2015","Unsheltered Homeless Children of Parenting Youth, 2015"
0,AK,2.0,"1,956",411,197,"1,348",773,"1,181",2,"1,862",...,18,8,10,18,0,21,9,12,21,0
1,AL,8.0,"3,970",716,271,"2,983","1,532","2,427",11,"3,901",...,20,7,9,16,4,35,12,17,29,6
2,AR,7.0,"2,560",417,243,"1,900",978,"1,582",0,"2,143",...,22,17,5,22,0,20,10,10,20,0
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,"9,896","2,124",824,"6,948","3,966","5,916",14,"7,516",...,160,43,107,150,10,194,51,134,185,9

In [111]:
# Create column for the year and set to 2015
data_2015_df["Year"] = 2015
data_2015_df.head()

,State,Number of CoCs,"Overall Homeless, 2015","Overall Homeless - Under 18, 2015","Overall Homeless - Age 18 to 24, 2015","Overall Homeless - Over 24, 2015","Overall Homeless - Female, 2015","Overall Homeless - Male, 2015","Overall Homeless - Transgender, 2015","Overall Homeless - Non-Hispanic/Non-Latino, 2015",...,"Sheltered ES Homeless Parenting Youth Age 18-24, 2015","Sheltered TH Homeless Parenting Youth Age 18-24, 2015","Sheltered Total Homeless Parenting Youth Age 18-24, 2015","Unsheltered Homeless Parenting Youth Age 18-24, 2015","Overall Homeless Children of Parenting Youth, 2015","Sheltered ES Homeless Children of Parenting Youth, 2015","Sheltered TH Homeless Children of Parenting Youth, 2015","Sheltered Total Homeless Children of Parenting Youth, 2015","Unsheltered Homeless Children of Parenting Youth, 2015",Year
0,AK,2.0,"1,956",411,197,"1,348",773,"1,181",2,"1,862",...,8,10,18,0,21,9,12,21,0,2015
1,AL,8.0,"3,970",716,271,"2,983","1,532","2,427",11,"3,901",...,7,9,16,4,35,12,17,29,6,2015
2,AR,7.0,"2,560",417,243,"1,900",978,"1,582",0,"2,143",...,17,5,22,0,20,10,10,20,0,2015
3,AS,0.0,,,,,,,,,...,,,,,,,,,,2015
4,AZ,3.0,"9,896","2,124",824,"6,948","3,966","5,916",14,"7,516",...,43,107,150,10,194,51,134,185,9,2015

In [112]:
# Get Column Names
cols_2015 = data_2015_df.columns.tolist()
cols_2015

['State',
 'Number of CoCs',
 'Overall Homeless, 2015',
 'Overall Homeless - Under 18, 2015',
 'Overall Homeless - Age 18 to 24, 2015',
 'Overall Homeless - Over 24, 2015',
 'Overall Homeless - Female, 2015',
 'Overall Homeless - Male, 2015',
 'Overall Homeless - Transgender, 2015',
 'Overall Homeless - Non-Hispanic/Non-Latino, 2015',
 'Overall Homeless - Hispanic/Latino, 2015',
 'Overall Homeless - White, 2015',
 'Overall Homeless - Black or African American, 2015',
 'Overall Homeless - Asian, 2015',
 'Overall Homeless - American Indian or Alaska Native, 2015',
 'Overall Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Overall Homeless - Multiple Races, 2015',
 'Sheltered ES Homeless, 2015',
 'Sheltered ES Homeless - Under 18, 2015',
 'Sheltered ES Homeless - Age 18 to 24, 2015',
 'Sheltered ES Homeless - Over 24, 2015',
 'Sheltered ES Homeless - Female, 2015',
 'Sheltered ES Homeless - Male, 2015',
 'Sheltered ES Homeless - Transgender, 2015',
 'Sheltered ES Homeless - Non-Hispanic/Non-Latino, 2015',
 'Sheltered ES Homeless - Hispanic/Latino, 2015',
 'Sheltered ES Homeless - White, 2015',
 'Sheltered ES Homeless - Black or African American, 2015',
 'Sheltered ES Homeless - Asian, 2015',
 'Sheltered ES Homeless - American Indian or Alaska Native, 2015',
 'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered ES Homeless - Multiple Races, 2015',
 'Sheltered TH Homeless, 2015',
 'Sheltered TH Homeless - Under 18, 2015',
 'Sheltered TH Homeless - Age 18 to 24, 2015',
 'Sheltered TH Homeless - Over 24, 2015',
 'Sheltered TH Homeless - Female, 2015',
 'Sheltered TH Homeless - Male, 2015',
 'Sheltered TH Homeless - Transgender, 2015',
 'Sheltered TH Homeless - Non-Hispanic/Non-Latino, 2015',
 'Sheltered TH Homeless - Hispanic/Latino, 2015',
 'Sheltered TH Homeless - White, 2015',
 'Sheltered TH Homeless - Black or African American, 2015',
 'Sheltered TH Homeless - Asian, 2015',
 'Sheltered TH Homeless - American Indian or Alaska Native, 2015',
 'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered TH Homeless - Multiple Races, 2015',
 'Sheltered SH Homeless, 2015',
 'Sheltered SH Homeless - Age 18 to 24, 2015',
 'Sheltered SH Homeless - Over 24, 2015',
 'Sheltered SH Homeless - Female, 2015',
 'Sheltered SH Homeless - Male, 2015',
 'Sheltered SH Homeless - Transgender, 2015',
 'Sheltered SH Homeless - Non-Hispanic/Non-Latino, 2015',
 'Sheltered SH Homeless - Hispanic/Latino, 2015',
 'Sheltered SH Homeless - White, 2015',
 'Sheltered SH Homeless - Black or African American, 2015',
 'Sheltered SH Homeless - Asian, 2015',
 'Sheltered SH Homeless - American Indian or Alaska Native, 2015',
 'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered SH Homeless - Multiple Races, 2015',
 'Sheltered Total Homeless, 2015',
 'Sheltered Total Homeless - Under 18, 2015',
 'Sheltered Total Homeless - Age 18 to 24, 2015',
 'Sheltered Total Homeless - Over 24, 2015',
 'Sheltered Total Homeless - Female, 2015',
 'Sheltered Total Homeless - Male, 2015',
 'Sheltered Total Homeless - Transgender, 2015',
 'Sheltered Total Homeless - Non-Hispanic/Non-Latino, 2015',
 'Sheltered Total Homeless - Hispanic/Latino, 2015',
 'Sheltered Total Homeless - White, 2015',
 'Sheltered Total Homeless - Black or African American, 2015',
 'Sheltered Total Homeless - Asian, 2015',
 'Sheltered Total Homeless - American Indian or Alaska Native, 2015',
 'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered Total Homeless - Multiple Races, 2015',
 'Unsheltered Homeless, 2015',
 'Unsheltered Homeless - Under 18, 2015',
 'Unsheltered Homeless - Age 18 to 24, 2015',
 'Unsheltered Homeless - Over 24, 2015',
 'Unsheltered Homeless - Female, 2015',
 'Unsheltered Homeless - Male, 2015',
 'Unsheltered Homeless - Transgender, 2015',
 'Unsheltered Homeless - Non-Hispanic/Non-Latino, 2015',
 'Unsheltered Homeless - Hispanic/Latino, 2015',
 'Unsheltered Homeless - White, 2015',
 'Unsheltered Homeless - Black or African American, 2015',
 'Unsheltered Homeless - Asian, 2015',
 'Unsheltered Homeless - American Indian or Alaska Native, 2015',
 'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Unsheltered Homeless - Multiple Races, 2015',
 'Overall Homeless Individuals, 2015',
 'Overall Homeless Individuals - Under 18, 2015',
 'Overall Homeless Individuals - Age 18 to 24, 2015',
 'Overall Homeless Individuals - Over 24, 2015',
 'Overall Homeless Individuals - Female, 2015',
 'Overall Homeless Individuals - Male, 2015',
 'Overall Homeless Individuals - Transgender, 2015',
 'Overall Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Overall Homeless Individuals - Hispanic/Latino, 2015',
 'Overall Homeless Individuals - White, 2015',
 'Overall Homeless Individuals - Black or African American, 2015',
 'Overall Homeless Individuals - Asian, 2015',
 'Overall Homeless Individuals - American Indian or Alaska Native, 2015',
 'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Overall Homeless Individuals - Multiple Races, 2015',
 'Sheltered ES Homeless Individuals, 2015',
 'Sheltered ES Homeless Individuals - Under 18, 2015',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2015',
 'Sheltered ES Homeless Individuals - Over 24, 2015',
 'Sheltered ES Homeless Individuals - Female, 2015',
 'Sheltered ES Homeless Individuals - Male, 2015',
 'Sheltered ES Homeless Individuals - Transgender, 2015',
 'Sheltered ES Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Sheltered ES Homeless Individuals - Hispanic/Latino, 2015',
 'Sheltered ES Homeless Individuals - White, 2015',
 'Sheltered ES Homeless Individuals - Black or African American, 2015',
 'Sheltered ES Homeless Individuals - Asian, 2015',
 'Sheltered ES Homeless Individuals - American Indian or Alaska Native, 2015',
 'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered ES Homeless Individuals - Multiple Races, 2015',
 'Sheltered TH Homeless Individuals, 2015',
 'Sheltered TH Homeless Individuals - Under 18, 2015',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2015',
 'Sheltered TH Homeless Individuals - Over 24, 2015',
 'Sheltered TH Homeless Individuals - Female, 2015',
 'Sheltered TH Homeless Individuals - Male, 2015',
 'Sheltered TH Homeless Individuals - Transgender, 2015',
 'Sheltered TH Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Sheltered TH Homeless Individuals - Hispanic/Latino, 2015',
 'Sheltered TH Homeless Individuals - White, 2015',
 'Sheltered TH Homeless Individuals - Black or African American, 2015',
 'Sheltered TH Homeless Individuals - Asian, 2015',
 'Sheltered TH Homeless Individuals - American Indian or Alaska Native, 2015',
 'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered TH Homeless Individuals - Multiple Races, 2015',
 'Sheltered SH Homeless Individuals, 2015',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2015',
 'Sheltered SH Homeless Individuals - Over 24, 2015',
 'Sheltered SH Homeless Individuals - Female, 2015',
 'Sheltered SH Homeless Individuals - Male, 2015',
 'Sheltered SH Homeless Individuals - Transgender, 2015',
 'Sheltered SH Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Sheltered SH Homeless Individuals - Hispanic/Latino, 2015',
 'Sheltered SH Homeless Individuals - White, 2015',
 'Sheltered SH Homeless Individuals - Black or African American, 2015',
 'Sheltered SH Homeless Individuals - Asian, 2015',
 'Sheltered SH Homeless Individuals - American Indian or Alaska Native, 2015',
 'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered SH Homeless Individuals - Multiple Races, 2015',
 'Sheltered Total Homeless Individuals, 2015',
 'Sheltered Total Homeless Individuals - Under 18, 2015',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2015',
 'Sheltered Total Homeless Individuals - Over 24, 2015',
 'Sheltered Total Homeless Individuals - Female, 2015',
 'Sheltered Total Homeless Individuals - Male, 2015',
 'Sheltered Total Homeless Individuals - Transgender, 2015',
 'Sheltered Total Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Sheltered Total Homeless Individuals - Hispanic/Latino, 2015',
 'Sheltered Total Homeless Individuals - White, 2015',
 'Sheltered Total Homeless Individuals - Black or African American, 2015',
 'Sheltered Total Homeless Individuals - Asian, 2015',
 'Sheltered Total Homeless Individuals - American Indian or Alaska Native, 2015',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered Total Homeless Individuals - Multiple Races, 2015',
 'Unsheltered Homeless Individuals, 2015',
 'Unsheltered Homeless Individuals - Under 18, 2015',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2015',
 'Unsheltered Homeless Individuals - Over 24, 2015',
 'Unsheltered Homeless Individuals - Female, 2015',
 'Unsheltered Homeless Individuals - Male, 2015',
 'Unsheltered Homeless Individuals - Transgender, 2015',
 'Unsheltered Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Unsheltered Homeless Individuals - Hispanic/Latino, 2015',
 'Unsheltered Homeless Individuals - White, 2015',
 'Unsheltered Homeless Individuals - Black or African American, 2015',
 'Unsheltered Homeless Individuals - Asian, 2015',
 'Unsheltered Homeless Individuals - American Indian or Alaska Native, 2015',
 'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Unsheltered Homeless Individuals - Multiple Races, 2015',
 'Overall Homeless People in Families, 2015',
 'Overall Homeless People in Families - Under 18, 2015',
 'Overall Homeless People in Families - Age 18 to 24, 2015',
 'Overall Homeless People in Families - Over 24, 2015',
 'Overall Homeless People in Families - Female, 2015',
 'Overall Homeless People in Families - Male, 2015',
 'Overall Homeless People in Families - Transgender, 2015',
 'Overall Homeless People in Families - Non-Hispanic/Non-Latino, 2015',
 'Overall Homeless People in Families - Hispanic/Latino, 2015',
 'Overall Homeless People in Families - White, 2015',
 'Overall Homeless People in Families - Black or African American, 2015',
 'Overall Homeless People in Families - Asian, 2015',
 'Overall Homeless People in Families - American Indian or Alaska Native, 2015',
 'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015',
 'Overall Homeless People in Families - Multiple Races, 2015',
 'Sheltered ES Homeless People in Families, 2015',
 'Sheltered ES Homeless People in Families - Under 18, 2015',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2015',
 'Sheltered ES Homeless People in Families - Over 24, 2015',
 'Sheltered ES Homeless People in Families - Female, 2015',
 'Sheltered ES Homeless People in Families - Male, 2015',
 'Sheltered ES Homeless People in Families - Transgender, 2015',
 'Sheltered ES Homeless People in Families - Non-Hispanic/Non-Latino, 2015',
 'Sheltered ES Homeless People in Families - Hispanic/Latino, 2015',
 'Sheltered ES Homeless People in Families - White, 2015',
 'Sheltered ES Homeless People in Families - Black or African American, 2015',
 'Sheltered ES Homeless People in Families - Asian, 2015',
 'Sheltered ES Homeless People in Families - American Indian or Alaska Native, 2015',
 'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered ES Homeless People in Families - Multiple Races, 2015',
 'Sheltered TH Homeless People in Families, 2015',
 'Sheltered TH Homeless People in Families - Under 18, 2015',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2015',
 'Sheltered TH Homeless People in Families - Over 24, 2015',
 'Sheltered TH Homeless People in Families - Female, 2015',
 'Sheltered TH Homeless People in Families - Male, 2015',
 'Sheltered TH Homeless People in Families - Transgender, 2015',
 'Sheltered TH Homeless People in Families - Non-Hispanic/Non-Latino, 2015',
 'Sheltered TH Homeless People in Families - Hispanic/Latino, 2015',
 'Sheltered TH Homeless People in Families - White, 2015',
 'Sheltered TH Homeless People in Families - Black or African American, 2015',
 'Sheltered TH Homeless People in Families - Asian, 2015',
 'Sheltered TH Homeless People in Families - American Indian or Alaska Native, 2015',
 'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered TH Homeless People in Families - Multiple Races, 2015',
 'Sheltered Total Homeless People in Families, 2015',
 'Sheltered Total Homeless People in Families - Under 18, 2015',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2015',
 'Sheltered Total Homeless People in Families - Over 24, 2015',
 'Sheltered Total Homeless People in Families - Female, 2015',
 'Sheltered Total Homeless People in Families - Male, 2015',
 'Sheltered Total Homeless People in Families - Transgender, 2015',
 'Sheltered Total Homeless People in Families - Non-Hispanic/Non-Latino, 2015',
 'Sheltered Total Homeless People in Families - Hispanic/Latino, 2015',
 'Sheltered Total Homeless People in Families - White, 2015',
 'Sheltered Total Homeless People in Families - Black or African American, 2015',
 'Sheltered Total Homeless People in Families - Asian, 2015',
 'Sheltered Total Homeless People in Families - American Indian or Alaska Native, 2015',
 'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered Total Homeless People in Families - Multiple Races, 2015',
 'Unsheltered Homeless People in Families, 2015',
 'Unsheltered Homeless People in Families - Under 18, 2015',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2015',
 'Unsheltered Homeless People in Families - Over 24, 2015',
 'Unsheltered Homeless People in Families - Female, 2015',
 'Unsheltered Homeless People in Families - Male, 2015',
 'Unsheltered Homeless People in Families - Transgender, 2015',
 'Unsheltered Homeless People in Families - Non-Hispanic/Non-Latino, 2015',
 'Unsheltered Homeless People in Families - Hispanic/Latino, 2015',
 'Unsheltered Homeless People in Families - White, 2015',
 'Unsheltered Homeless People in Families - Black or African American, 2015',
 'Unsheltered Homeless People in Families - Asian, 2015',
 'Unsheltered Homeless People in Families - American Indian or Alaska Native, 2015',
 'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015',
 'Unsheltered Homeless People in Families - Multiple Races, 2015',
 'Overall Homeless Family Households, 2015',
 'Sheltered ES Homeless Family Households, 2015',
 'Sheltered TH Homeless Family Households, 2015',
 'Sheltered Total Homeless Family Households, 2015',
 'Unsheltered Homeless Family Households, 2015',
 'Overall Chronically Homeless, 2015',
 'Sheltered ES Chronically Homeless, 2015',
 'Sheltered SH Chronically Homeless, 2015',
 'Sheltered Total Chronically Homeless, 2015',
 'Unsheltered Chronically Homeless, 2015',
 'Overall Chronically Homeless Individuals, 2015',
 'Sheltered ES Chronically Homeless Individuals, 2015',
 'Sheltered SH Chronically Homeless Individuals, 2015',
 'Sheltered Total Chronically Homeless Individuals, 2015',
 'Unsheltered Chronically Homeless Individuals, 2015',
 'Overall Chronically Homeless People in Families, 2015',
 'Sheltered ES Chronically Homeless People in Families, 2015',
 'Sheltered Total Chronically Homeless People in Families, 2015',
 'Unsheltered Chronically Homeless People in Families, 2015',
 'Overall Homeless Veterans, 2015',
 'Overall Homeless Veterans - Female, 2015',
 'Overall Homeless Veterans - Male, 2015',
 'Overall Homeless Veterans - Transgender, 2015',
 'Overall Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Overall Homeless Veterans - Hispanic/Latino, 2015',
 'Overall Homeless Veterans - White, 2015',
 'Overall Homeless Veterans - Black or African American, 2015',
 'Overall Homeless Veterans - Asian, 2015',
 'Overall Homeless Veterans - American Indian or Alaska Native, 2015',
 'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Overall Homeless Veterans - Multiple Races, 2015',
 'Sheltered ES Homeless Veterans, 2015',
 'Sheltered ES Homeless Veterans - Female, 2015',
 'Sheltered ES Homeless Veterans - Male, 2015',
 'Sheltered ES Homeless Veterans - Transgender, 2015',
 'Sheltered ES Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Sheltered ES Homeless Veterans - Hispanic/Latino, 2015',
 'Sheltered ES Homeless Veterans - White, 2015',
 'Sheltered ES Homeless Veterans - Black or African American, 2015',
 'Sheltered ES Homeless Veterans - Asian, 2015',
 'Sheltered ES Homeless Veterans - American Indian or Alaska Native, 2015',
 'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered ES Homeless Veterans - Multiple Races, 2015',
 'Sheltered TH Homeless Veterans, 2015',
 'Sheltered TH Homeless Veterans - Female, 2015',
 'Sheltered TH Homeless Veterans - Male, 2015',
 'Sheltered TH Homeless Veterans - Transgender, 2015',
 'Sheltered TH Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Sheltered TH Homeless Veterans - Hispanic/Latino, 2015',
 'Sheltered TH Homeless Veterans - White, 2015',
 'Sheltered TH Homeless Veterans - Black or African American, 2015',
 'Sheltered TH Homeless Veterans - Asian, 2015',
 'Sheltered TH Homeless Veterans - American Indian or Alaska Native, 2015',
 'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered TH Homeless Veterans - Multiple Races, 2015',
 'Sheltered SH Homeless Veterans, 2015',
 'Sheltered SH Homeless Veterans - Female, 2015',
 'Sheltered SH Homeless Veterans - Male, 2015',
 'Sheltered SH Homeless Veterans - Transgender, 2015',
 'Sheltered SH Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Sheltered SH Homeless Veterans - Hispanic/Latino, 2015',
 'Sheltered SH Homeless Veterans - White, 2015',
 'Sheltered SH Homeless Veterans - Black or African American, 2015',
 'Sheltered SH Homeless Veterans - Asian, 2015',
 'Sheltered SH Homeless Veterans - American Indian or Alaska Native, 2015',
 'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered SH Homeless Veterans - Multiple Races, 2015',
 'Sheltered Total Homeless Veterans, 2015',
 'Sheltered Total Homeless Veterans - Female, 2015',
 'Sheltered Total Homeless Veterans - Male, 2015',
 'Sheltered Total Homeless Veterans - Transgender, 2015',
 'Sheltered Total Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Sheltered Total Homeless Veterans - Hispanic/Latino, 2015',
 'Sheltered Total Homeless Veterans - White, 2015',
 'Sheltered Total Homeless Veterans - Black or African American, 2015',
 'Sheltered Total Homeless Veterans - Asian, 2015',
 'Sheltered Total Homeless Veterans - American Indian or Alaska Native, 2015',
 'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered Total Homeless Veterans - Multiple Races, 2015',
 'Unsheltered Homeless Veterans, 2015',
 'Unsheltered Homeless Veterans - Female, 2015',
 'Unsheltered Homeless Veterans - Male, 2015',
 'Unsheltered Homeless Veterans - Transgender, 2015',
 'Unsheltered Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Unsheltered Homeless Veterans - Hispanic/Latino, 2015',
 'Unsheltered Homeless Veterans - White, 2015',
 'Unsheltered Homeless Veterans - Black or African American, 2015',
 'Unsheltered Homeless Veterans - Asian, 2015',
 'Unsheltered Homeless Veterans - American Indian or Alaska Native, 2015',
 'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Unsheltered Homeless Veterans - Multiple Races, 2015',
 'Overall Homeless Unaccompanied Youth (Under 25), 2015',

In [113]:
# Rearrange column names so year is second
new_cols_2015 = ['State', 'Year',
 'Number of CoCs',
 'Overall Homeless, 2015',
 'Overall Homeless - Under 18, 2015',
 'Overall Homeless - Age 18 to 24, 2015',
 'Overall Homeless - Over 24, 2015',
 'Overall Homeless - Female, 2015',
 'Overall Homeless - Male, 2015',
 'Overall Homeless - Transgender, 2015',
 'Overall Homeless - Non-Hispanic/Non-Latino, 2015',
 'Overall Homeless - Hispanic/Latino, 2015',
 'Overall Homeless - White, 2015',
 'Overall Homeless - Black or African American, 2015',
 'Overall Homeless - Asian, 2015',
 'Overall Homeless - American Indian or Alaska Native, 2015',
 'Overall Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Overall Homeless - Multiple Races, 2015',
 'Sheltered ES Homeless, 2015',
 'Sheltered ES Homeless - Under 18, 2015',
 'Sheltered ES Homeless - Age 18 to 24, 2015',
 'Sheltered ES Homeless - Over 24, 2015',
 'Sheltered ES Homeless - Female, 2015',
 'Sheltered ES Homeless - Male, 2015',
 'Sheltered ES Homeless - Transgender, 2015',
 'Sheltered ES Homeless - Non-Hispanic/Non-Latino, 2015',
 'Sheltered ES Homeless - Hispanic/Latino, 2015',
 'Sheltered ES Homeless - White, 2015',
 'Sheltered ES Homeless - Black or African American, 2015',
 'Sheltered ES Homeless - Asian, 2015',
 'Sheltered ES Homeless - American Indian or Alaska Native, 2015',
 'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered ES Homeless - Multiple Races, 2015',
 'Sheltered TH Homeless, 2015',
 'Sheltered TH Homeless - Under 18, 2015',
 'Sheltered TH Homeless - Age 18 to 24, 2015',
 'Sheltered TH Homeless - Over 24, 2015',
 'Sheltered TH Homeless - Female, 2015',
 'Sheltered TH Homeless - Male, 2015',
 'Sheltered TH Homeless - Transgender, 2015',
 'Sheltered TH Homeless - Non-Hispanic/Non-Latino, 2015',
 'Sheltered TH Homeless - Hispanic/Latino, 2015',
 'Sheltered TH Homeless - White, 2015',
 'Sheltered TH Homeless - Black or African American, 2015',
 'Sheltered TH Homeless - Asian, 2015',
 'Sheltered TH Homeless - American Indian or Alaska Native, 2015',
 'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered TH Homeless - Multiple Races, 2015',
 'Sheltered SH Homeless, 2015',
 'Sheltered SH Homeless - Age 18 to 24, 2015',
 'Sheltered SH Homeless - Over 24, 2015',
 'Sheltered SH Homeless - Female, 2015',
 'Sheltered SH Homeless - Male, 2015',
 'Sheltered SH Homeless - Transgender, 2015',
 'Sheltered SH Homeless - Non-Hispanic/Non-Latino, 2015',
 'Sheltered SH Homeless - Hispanic/Latino, 2015',
 'Sheltered SH Homeless - White, 2015',
 'Sheltered SH Homeless - Black or African American, 2015',
 'Sheltered SH Homeless - Asian, 2015',
 'Sheltered SH Homeless - American Indian or Alaska Native, 2015',
 'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered SH Homeless - Multiple Races, 2015',
 'Sheltered Total Homeless, 2015',
 'Sheltered Total Homeless - Under 18, 2015',
 'Sheltered Total Homeless - Age 18 to 24, 2015',
 'Sheltered Total Homeless - Over 24, 2015',
 'Sheltered Total Homeless - Female, 2015',
 'Sheltered Total Homeless - Male, 2015',
 'Sheltered Total Homeless - Transgender, 2015',
 'Sheltered Total Homeless - Non-Hispanic/Non-Latino, 2015',
 'Sheltered Total Homeless - Hispanic/Latino, 2015',
 'Sheltered Total Homeless - White, 2015',
 'Sheltered Total Homeless - Black or African American, 2015',
 'Sheltered Total Homeless - Asian, 2015',
 'Sheltered Total Homeless - American Indian or Alaska Native, 2015',
 'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered Total Homeless - Multiple Races, 2015',
 'Unsheltered Homeless, 2015',
 'Unsheltered Homeless - Under 18, 2015',
 'Unsheltered Homeless - Age 18 to 24, 2015',
 'Unsheltered Homeless - Over 24, 2015',
 'Unsheltered Homeless - Female, 2015',
 'Unsheltered Homeless - Male, 2015',
 'Unsheltered Homeless - Transgender, 2015',
 'Unsheltered Homeless - Non-Hispanic/Non-Latino, 2015',
 'Unsheltered Homeless - Hispanic/Latino, 2015',
 'Unsheltered Homeless - White, 2015',
 'Unsheltered Homeless - Black or African American, 2015',
 'Unsheltered Homeless - Asian, 2015',
 'Unsheltered Homeless - American Indian or Alaska Native, 2015',
 'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander, 2015',
 'Unsheltered Homeless - Multiple Races, 2015',
 'Overall Homeless Individuals, 2015',
 'Overall Homeless Individuals - Under 18, 2015',
 'Overall Homeless Individuals - Age 18 to 24, 2015',
 'Overall Homeless Individuals - Over 24, 2015',
 'Overall Homeless Individuals - Female, 2015',
 'Overall Homeless Individuals - Male, 2015',
 'Overall Homeless Individuals - Transgender, 2015',
 'Overall Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Overall Homeless Individuals - Hispanic/Latino, 2015',
 'Overall Homeless Individuals - White, 2015',
 'Overall Homeless Individuals - Black or African American, 2015',
 'Overall Homeless Individuals - Asian, 2015',
 'Overall Homeless Individuals - American Indian or Alaska Native, 2015',
 'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Overall Homeless Individuals - Multiple Races, 2015',
 'Sheltered ES Homeless Individuals, 2015',
 'Sheltered ES Homeless Individuals - Under 18, 2015',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2015',
 'Sheltered ES Homeless Individuals - Over 24, 2015',
 'Sheltered ES Homeless Individuals - Female, 2015',
 'Sheltered ES Homeless Individuals - Male, 2015',
 'Sheltered ES Homeless Individuals - Transgender, 2015',
 'Sheltered ES Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Sheltered ES Homeless Individuals - Hispanic/Latino, 2015',
 'Sheltered ES Homeless Individuals - White, 2015',
 'Sheltered ES Homeless Individuals - Black or African American, 2015',
 'Sheltered ES Homeless Individuals - Asian, 2015',
 'Sheltered ES Homeless Individuals - American Indian or Alaska Native, 2015',
 'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered ES Homeless Individuals - Multiple Races, 2015',
 'Sheltered TH Homeless Individuals, 2015',
 'Sheltered TH Homeless Individuals - Under 18, 2015',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2015',
 'Sheltered TH Homeless Individuals - Over 24, 2015',
 'Sheltered TH Homeless Individuals - Female, 2015',
 'Sheltered TH Homeless Individuals - Male, 2015',
 'Sheltered TH Homeless Individuals - Transgender, 2015',
 'Sheltered TH Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Sheltered TH Homeless Individuals - Hispanic/Latino, 2015',
 'Sheltered TH Homeless Individuals - White, 2015',
 'Sheltered TH Homeless Individuals - Black or African American, 2015',
 'Sheltered TH Homeless Individuals - Asian, 2015',
 'Sheltered TH Homeless Individuals - American Indian or Alaska Native, 2015',
 'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered TH Homeless Individuals - Multiple Races, 2015',
 'Sheltered SH Homeless Individuals, 2015',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2015',
 'Sheltered SH Homeless Individuals - Over 24, 2015',
 'Sheltered SH Homeless Individuals - Female, 2015',
 'Sheltered SH Homeless Individuals - Male, 2015',
 'Sheltered SH Homeless Individuals - Transgender, 2015',
 'Sheltered SH Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Sheltered SH Homeless Individuals - Hispanic/Latino, 2015',
 'Sheltered SH Homeless Individuals - White, 2015',
 'Sheltered SH Homeless Individuals - Black or African American, 2015',
 'Sheltered SH Homeless Individuals - Asian, 2015',
 'Sheltered SH Homeless Individuals - American Indian or Alaska Native, 2015',
 'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered SH Homeless Individuals - Multiple Races, 2015',
 'Sheltered Total Homeless Individuals, 2015',
 'Sheltered Total Homeless Individuals - Under 18, 2015',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2015',
 'Sheltered Total Homeless Individuals - Over 24, 2015',
 'Sheltered Total Homeless Individuals - Female, 2015',
 'Sheltered Total Homeless Individuals - Male, 2015',
 'Sheltered Total Homeless Individuals - Transgender, 2015',
 'Sheltered Total Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Sheltered Total Homeless Individuals - Hispanic/Latino, 2015',
 'Sheltered Total Homeless Individuals - White, 2015',
 'Sheltered Total Homeless Individuals - Black or African American, 2015',
 'Sheltered Total Homeless Individuals - Asian, 2015',
 'Sheltered Total Homeless Individuals - American Indian or Alaska Native, 2015',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered Total Homeless Individuals - Multiple Races, 2015',
 'Unsheltered Homeless Individuals, 2015',
 'Unsheltered Homeless Individuals - Under 18, 2015',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2015',
 'Unsheltered Homeless Individuals - Over 24, 2015',
 'Unsheltered Homeless Individuals - Female, 2015',
 'Unsheltered Homeless Individuals - Male, 2015',
 'Unsheltered Homeless Individuals - Transgender, 2015',
 'Unsheltered Homeless Individuals - Non-Hispanic/Non-Latino, 2015',
 'Unsheltered Homeless Individuals - Hispanic/Latino, 2015',
 'Unsheltered Homeless Individuals - White, 2015',
 'Unsheltered Homeless Individuals - Black or African American, 2015',
 'Unsheltered Homeless Individuals - Asian, 2015',
 'Unsheltered Homeless Individuals - American Indian or Alaska Native, 2015',
 'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015',
 'Unsheltered Homeless Individuals - Multiple Races, 2015',
 'Overall Homeless People in Families, 2015',
 'Overall Homeless People in Families - Under 18, 2015',
 'Overall Homeless People in Families - Age 18 to 24, 2015',
 'Overall Homeless People in Families - Over 24, 2015',
 'Overall Homeless People in Families - Female, 2015',
 'Overall Homeless People in Families - Male, 2015',
 'Overall Homeless People in Families - Transgender, 2015',
 'Overall Homeless People in Families - Non-Hispanic/Non-Latino, 2015',
 'Overall Homeless People in Families - Hispanic/Latino, 2015',
 'Overall Homeless People in Families - White, 2015',
 'Overall Homeless People in Families - Black or African American, 2015',
 'Overall Homeless People in Families - Asian, 2015',
 'Overall Homeless People in Families - American Indian or Alaska Native, 2015',
 'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015',
 'Overall Homeless People in Families - Multiple Races, 2015',
 'Sheltered ES Homeless People in Families, 2015',
 'Sheltered ES Homeless People in Families - Under 18, 2015',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2015',
 'Sheltered ES Homeless People in Families - Over 24, 2015',
 'Sheltered ES Homeless People in Families - Female, 2015',
 'Sheltered ES Homeless People in Families - Male, 2015',
 'Sheltered ES Homeless People in Families - Transgender, 2015',
 'Sheltered ES Homeless People in Families - Non-Hispanic/Non-Latino, 2015',
 'Sheltered ES Homeless People in Families - Hispanic/Latino, 2015',
 'Sheltered ES Homeless People in Families - White, 2015',
 'Sheltered ES Homeless People in Families - Black or African American, 2015',
 'Sheltered ES Homeless People in Families - Asian, 2015',
 'Sheltered ES Homeless People in Families - American Indian or Alaska Native, 2015',
 'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered ES Homeless People in Families - Multiple Races, 2015',
 'Sheltered TH Homeless People in Families, 2015',
 'Sheltered TH Homeless People in Families - Under 18, 2015',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2015',
 'Sheltered TH Homeless People in Families - Over 24, 2015',
 'Sheltered TH Homeless People in Families - Female, 2015',
 'Sheltered TH Homeless People in Families - Male, 2015',
 'Sheltered TH Homeless People in Families - Transgender, 2015',
 'Sheltered TH Homeless People in Families - Non-Hispanic/Non-Latino, 2015',
 'Sheltered TH Homeless People in Families - Hispanic/Latino, 2015',
 'Sheltered TH Homeless People in Families - White, 2015',
 'Sheltered TH Homeless People in Families - Black or African American, 2015',
 'Sheltered TH Homeless People in Families - Asian, 2015',
 'Sheltered TH Homeless People in Families - American Indian or Alaska Native, 2015',
 'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered TH Homeless People in Families - Multiple Races, 2015',
 'Sheltered Total Homeless People in Families, 2015',
 'Sheltered Total Homeless People in Families - Under 18, 2015',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2015',
 'Sheltered Total Homeless People in Families - Over 24, 2015',
 'Sheltered Total Homeless People in Families - Female, 2015',
 'Sheltered Total Homeless People in Families - Male, 2015',
 'Sheltered Total Homeless People in Families - Transgender, 2015',
 'Sheltered Total Homeless People in Families - Non-Hispanic/Non-Latino, 2015',
 'Sheltered Total Homeless People in Families - Hispanic/Latino, 2015',
 'Sheltered Total Homeless People in Families - White, 2015',
 'Sheltered Total Homeless People in Families - Black or African American, 2015',
 'Sheltered Total Homeless People in Families - Asian, 2015',
 'Sheltered Total Homeless People in Families - American Indian or Alaska Native, 2015',
 'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered Total Homeless People in Families - Multiple Races, 2015',
 'Unsheltered Homeless People in Families, 2015',
 'Unsheltered Homeless People in Families - Under 18, 2015',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2015',
 'Unsheltered Homeless People in Families - Over 24, 2015',
 'Unsheltered Homeless People in Families - Female, 2015',
 'Unsheltered Homeless People in Families - Male, 2015',
 'Unsheltered Homeless People in Families - Transgender, 2015',
 'Unsheltered Homeless People in Families - Non-Hispanic/Non-Latino, 2015',
 'Unsheltered Homeless People in Families - Hispanic/Latino, 2015',
 'Unsheltered Homeless People in Families - White, 2015',
 'Unsheltered Homeless People in Families - Black or African American, 2015',
 'Unsheltered Homeless People in Families - Asian, 2015',
 'Unsheltered Homeless People in Families - American Indian or Alaska Native, 2015',
 'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015',
 'Unsheltered Homeless People in Families - Multiple Races, 2015',
 'Overall Homeless Family Households, 2015',
 'Sheltered ES Homeless Family Households, 2015',
 'Sheltered TH Homeless Family Households, 2015',
 'Sheltered Total Homeless Family Households, 2015',
 'Unsheltered Homeless Family Households, 2015',
 'Overall Chronically Homeless, 2015',
 'Sheltered ES Chronically Homeless, 2015',
 'Sheltered SH Chronically Homeless, 2015',
 'Sheltered Total Chronically Homeless, 2015',
 'Unsheltered Chronically Homeless, 2015',
 'Overall Chronically Homeless Individuals, 2015',
 'Sheltered ES Chronically Homeless Individuals, 2015',
 'Sheltered SH Chronically Homeless Individuals, 2015',
 'Sheltered Total Chronically Homeless Individuals, 2015',
 'Unsheltered Chronically Homeless Individuals, 2015',
 'Overall Chronically Homeless People in Families, 2015',
 'Sheltered ES Chronically Homeless People in Families, 2015',
 'Sheltered Total Chronically Homeless People in Families, 2015',
 'Unsheltered Chronically Homeless People in Families, 2015',
 'Overall Homeless Veterans, 2015',
 'Overall Homeless Veterans - Female, 2015',
 'Overall Homeless Veterans - Male, 2015',
 'Overall Homeless Veterans - Transgender, 2015',
 'Overall Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Overall Homeless Veterans - Hispanic/Latino, 2015',
 'Overall Homeless Veterans - White, 2015',
 'Overall Homeless Veterans - Black or African American, 2015',
 'Overall Homeless Veterans - Asian, 2015',
 'Overall Homeless Veterans - American Indian or Alaska Native, 2015',
 'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Overall Homeless Veterans - Multiple Races, 2015',
 'Sheltered ES Homeless Veterans, 2015',
 'Sheltered ES Homeless Veterans - Female, 2015',
 'Sheltered ES Homeless Veterans - Male, 2015',
 'Sheltered ES Homeless Veterans - Transgender, 2015',
 'Sheltered ES Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Sheltered ES Homeless Veterans - Hispanic/Latino, 2015',
 'Sheltered ES Homeless Veterans - White, 2015',
 'Sheltered ES Homeless Veterans - Black or African American, 2015',
 'Sheltered ES Homeless Veterans - Asian, 2015',
 'Sheltered ES Homeless Veterans - American Indian or Alaska Native, 2015',
 'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered ES Homeless Veterans - Multiple Races, 2015',
 'Sheltered TH Homeless Veterans, 2015',
 'Sheltered TH Homeless Veterans - Female, 2015',
 'Sheltered TH Homeless Veterans - Male, 2015',
 'Sheltered TH Homeless Veterans - Transgender, 2015',
 'Sheltered TH Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Sheltered TH Homeless Veterans - Hispanic/Latino, 2015',
 'Sheltered TH Homeless Veterans - White, 2015',
 'Sheltered TH Homeless Veterans - Black or African American, 2015',
 'Sheltered TH Homeless Veterans - Asian, 2015',
 'Sheltered TH Homeless Veterans - American Indian or Alaska Native, 2015',
 'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered TH Homeless Veterans - Multiple Races, 2015',
 'Sheltered SH Homeless Veterans, 2015',
 'Sheltered SH Homeless Veterans - Female, 2015',
 'Sheltered SH Homeless Veterans - Male, 2015',
 'Sheltered SH Homeless Veterans - Transgender, 2015',
 'Sheltered SH Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Sheltered SH Homeless Veterans - Hispanic/Latino, 2015',
 'Sheltered SH Homeless Veterans - White, 2015',
 'Sheltered SH Homeless Veterans - Black or African American, 2015',
 'Sheltered SH Homeless Veterans - Asian, 2015',
 'Sheltered SH Homeless Veterans - American Indian or Alaska Native, 2015',
 'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered SH Homeless Veterans - Multiple Races, 2015',
 'Sheltered Total Homeless Veterans, 2015',
 'Sheltered Total Homeless Veterans - Female, 2015',
 'Sheltered Total Homeless Veterans - Male, 2015',
 'Sheltered Total Homeless Veterans - Transgender, 2015',
 'Sheltered Total Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Sheltered Total Homeless Veterans - Hispanic/Latino, 2015',
 'Sheltered Total Homeless Veterans - White, 2015',
 'Sheltered Total Homeless Veterans - Black or African American, 2015',
 'Sheltered Total Homeless Veterans - Asian, 2015',
 'Sheltered Total Homeless Veterans - American Indian or Alaska Native, 2015',
 'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Sheltered Total Homeless Veterans - Multiple Races, 2015',
 'Unsheltered Homeless Veterans, 2015',
 'Unsheltered Homeless Veterans - Female, 2015',
 'Unsheltered Homeless Veterans - Male, 2015',
 'Unsheltered Homeless Veterans - Transgender, 2015',
 'Unsheltered Homeless Veterans - Non-Hispanic/Non-Latino, 2015',
 'Unsheltered Homeless Veterans - Hispanic/Latino, 2015',
 'Unsheltered Homeless Veterans - White, 2015',
 'Unsheltered Homeless Veterans - Black or African American, 2015',
 'Unsheltered Homeless Veterans - Asian, 2015',
 'Unsheltered Homeless Veterans - American Indian or Alaska Native, 2015',
 'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015',
 'Unsheltered Homeless Veterans - Multiple Races, 2015',
 'Overall Homeless Unaccompanied Youth (Under 25), 2015',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25), 2015',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25), 2015',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25), 2015',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25), 2015',
 'Unsheltered Homeless Unaccompanied Youth (Under 25), 2015',
 'Overall Homeless Unaccompanied Youth Under 18, 2015',
 'Sheltered ES Homeless Unaccompanied Youth Under 18, 2015',
 'Sheltered TH Homeless Unaccompanied Youth Under 18, 2015',
 'Sheltered SH Homeless Unaccompanied Youth Under 18, 2015',
 'Sheltered Total Homeless Unaccompanied Youth Under 18, 2015',
 'Unsheltered Homeless Unaccompanied Youth Under 18, 2015',
 'Overall Homeless Unaccompanied Youth Age 18-24, 2015',
 'Sheltered ES Homeless Unaccompanied Youth Age 18-24, 2015',
 'Sheltered TH Homeless Unaccompanied Youth Age 18-24, 2015',
 'Sheltered SH Homeless Unaccompanied Youth Age 18-24, 2015',
 'Sheltered Total Homeless Unaccompanied Youth Age 18-24, 2015',
 'Unsheltered Homeless Unaccompanied Youth Age 18-24, 2015',
 'Overall Homeless Parenting Youth (Under 25), 2015',
 'Sheltered ES Homeless Parenting Youth (Under 25), 2015',
 'Sheltered TH Homeless Parenting Youth (Under 25), 2015',
 'Sheltered Total Homeless Parenting Youth (Under 25), 2015',
 'Unsheltered Homeless Parenting Youth (Under 25), 2015',
 'Overall Homeless Parenting Youth Under 18, 2015',
 'Sheltered ES Homeless Parenting Youth Under 18, 2015',
 'Sheltered TH Homeless Parenting Youth Under 18, 2015',
 'Sheltered Total Homeless Parenting Youth Under 18, 2015',
 'Unsheltered Homeless Parenting Youth Under 18, 2015',
 'Overall Homeless Parenting Youth Age 18-24, 2015',
 'Sheltered ES Homeless Parenting Youth Age 18-24, 2015',
 'Sheltered TH Homeless Parenting Youth Age 18-24, 2015',
 'Sheltered Total Homeless Parenting Youth Age 18-24, 2015',
 'Unsheltered Homeless Parenting Youth Age 18-24, 2015',
 'Overall Homeless Children of Parenting Youth, 2015',
 'Sheltered ES Homeless Children of Parenting Youth, 2015',
 'Sheltered TH Homeless Children of Parenting Youth, 2015',
 'Sheltered Total Homeless Children of Parenting Youth, 2015',
 'Unsheltered Homeless Children of Parenting Youth, 2015'
 ]

In [114]:
# Apply rearranged column names
data_2015_df = data_2015_df[new_cols_2015]
data_2015_df.head()

,State,Year,Number of CoCs,"Overall Homeless, 2015","Overall Homeless - Under 18, 2015","Overall Homeless - Age 18 to 24, 2015","Overall Homeless - Over 24, 2015","Overall Homeless - Female, 2015","Overall Homeless - Male, 2015","Overall Homeless - Transgender, 2015",...,"Overall Homeless Parenting Youth Age 18-24, 2015","Sheltered ES Homeless Parenting Youth Age 18-24, 2015","Sheltered TH Homeless Parenting Youth Age 18-24, 2015","Sheltered Total Homeless Parenting Youth Age 18-24, 2015","Unsheltered Homeless Parenting Youth Age 18-24, 2015","Overall Homeless Children of Parenting Youth, 2015","Sheltered ES Homeless Children of Parenting Youth, 2015","Sheltered TH Homeless Children of Parenting Youth, 2015","Sheltered Total Homeless Children of Parenting Youth, 2015","Unsheltered Homeless Children of Parenting Youth, 2015"
0,AK,2015,2.0,"1,956",411,197,"1,348",773,"1,181",2,...,18,8,10,18,0,21,9,12,21,0
1,AL,2015,8.0,"3,970",716,271,"2,983","1,532","2,427",11,...,20,7,9,16,4,35,12,17,29,6
2,AR,2015,7.0,"2,560",417,243,"1,900",978,"1,582",0,...,22,17,5,22,0,20,10,10,20,0
3,AS,2015,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2015,3.0,"9,896","2,124",824,"6,948","3,966","5,916",14,...,160,43,107,150,10,194,51,134,185,9

In [116]:
# rename columns to remove year from each column title
dict = {
 'Overall Homeless, 2015':'Overall Homeless',
 'Overall Homeless - Under 18, 2015':'Overall Homeless - Under 18',
 'Overall Homeless - Age 18 to 24, 2015':'Overall Homeless - Age 18 to 24',
 'Overall Homeless - Over 24, 2015':'Overall Homeless - Over 24',
 'Overall Homeless - Female, 2015':'Overall Homeless - Female',
 'Overall Homeless - Male, 2015':'Overall Homeless - Male',
 'Overall Homeless - Transgender, 2015':'Overall Homeless - Transgender',
 'Overall Homeless - Non-Hispanic/Non-Latino, 2015':'Overall Homeless - Non-Hispanic/Non-Latino',
 'Overall Homeless - Hispanic/Latino, 2015':'Overall Homeless - Hispanic/Latino',
 'Overall Homeless - White, 2015':'Overall Homeless - White',
 'Overall Homeless - Black or African American, 2015':'Overall Homeless - Black or African American',
 'Overall Homeless - Asian, 2015':'Overall Homeless - Asian',
 'Overall Homeless - American Indian or Alaska Native, 2015':'Overall Homeless - American Indian or Alaska Native',
 'Overall Homeless - Native Hawaiian or Other Pacific Islander, 2015':'Overall Homeless - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless - Multiple Races, 2015':'Overall Homeless - Multiple Races',
 
 'Sheltered ES Homeless, 2015':'Sheltered ES Homeless', 
 'Sheltered ES Homeless - Under 18, 2015':'Sheltered ES Homeless - Under 18',
 'Sheltered ES Homeless - Age 18 to 24, 2015':'Sheltered ES Homeless - Age 18 to 24',
 'Sheltered ES Homeless - Over 24, 2015':'Sheltered ES Homeless - Over 24',
 'Sheltered ES Homeless - Female, 2015':'Sheltered ES Homeless - Female',
 'Sheltered ES Homeless - Male, 2015':'Sheltered ES Homeless - Male',
 'Sheltered ES Homeless - Transgender, 2015':'Sheltered ES Homeless - Transgender',
 'Sheltered ES Homeless - Non-Hispanic/Non-Latino, 2015':'Sheltered ES Homeless - Non-Hispanic/Non-Latino',
 'Sheltered ES Homeless - Hispanic/Latino, 2015':'Sheltered ES Homeless - Hispanic/Latino',
 'Sheltered ES Homeless - White, 2015':'Sheltered ES Homeless - White',
 'Sheltered ES Homeless - Black or African American, 2015':'Sheltered ES Homeless - Black or African American',
 'Sheltered ES Homeless - Asian, 2015':'Sheltered ES Homeless - Asian',
 'Sheltered ES Homeless - American Indian or Alaska Native, 2015':'Sheltered ES Homeless - American Indian or Alaska Native',
 'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless - Multiple Races, 2015':'Sheltered ES Homeless - Multiple Races',
    
 'Sheltered TH Homeless, 2015':'Sheltered TH Homeless', 
 'Sheltered TH Homeless - Under 18, 2015':'Sheltered TH Homeless - Under 18',
 'Sheltered TH Homeless - Age 18 to 24, 2015':'Sheltered TH Homeless - Age 18 to 24',
 'Sheltered TH Homeless - Over 24, 2015':'Sheltered TH Homeless - Over 24',
 'Sheltered TH Homeless - Female, 2015':'Sheltered TH Homeless - Female',
 'Sheltered TH Homeless - Male, 2015':'Sheltered TH Homeless - Male',
 'Sheltered TH Homeless - Transgender, 2015':'Sheltered TH Homeless - Transgender',
 'Sheltered TH Homeless - Non-Hispanic/Non-Latino, 2015':'Sheltered TH Homeless - Non-Hispanic/Non-Latino',
 'Sheltered TH Homeless - Hispanic/Latino, 2015':'Sheltered TH Homeless - Hispanic/Latino',
 'Sheltered TH Homeless - White, 2015':'Sheltered TH Homeless - White',
 'Sheltered TH Homeless - Black or African American, 2015':'Sheltered TH Homeless - Black or African American',
 'Sheltered TH Homeless - Asian, 2015':'Sheltered TH Homeless - Asian',
 'Sheltered TH Homeless - American Indian or Alaska Native, 2015':'Sheltered TH Homeless - American Indian or Alaska Native',
 'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless - Multiple Races, 2015':'Sheltered TH Homeless - Multiple Races',
    
 'Sheltered SH Homeless, 2015':'Sheltered SH Homeless', 
 'Sheltered SH Homeless - Under 18, 2015':'Sheltered SH Homeless - Under 18',
 'Sheltered SH Homeless - Age 18 to 24, 2015':'Sheltered SH Homeless - Age 18 to 24',
 'Sheltered SH Homeless - Over 24, 2015':'Sheltered SH Homeless - Over 24',
 'Sheltered SH Homeless - Female, 2015':'Sheltered SH Homeless - Female',
 'Sheltered SH Homeless - Male, 2015':'Sheltered SH Homeless - Male',
 'Sheltered SH Homeless - Transgender, 2015':'Sheltered SH Homeless - Transgender',
 'Sheltered SH Homeless - Non-Hispanic/Non-Latino, 2015':'Sheltered SH Homeless - Non-Hispanic/Non-Latino',
 'Sheltered SH Homeless - Hispanic/Latino, 2015':'Sheltered SH Homeless - Hispanic/Latino',
 'Sheltered SH Homeless - White, 2015':'Sheltered SH Homeless - White',
 'Sheltered SH Homeless - Black or African American, 2015':'Sheltered SH Homeless - Black or African American',
 'Sheltered SH Homeless - Asian, 2015':'Sheltered SH Homeless - Asian',
 'Sheltered SH Homeless - American Indian or Alaska Native, 2015':'Sheltered SH Homeless - American Indian or Alaska Native',
 'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered SH Homeless - Multiple Races, 2015':'Sheltered SH Homeless - Multiple Races',
    
 'Sheltered Total Homeless, 2015':'Sheltered Total Homeless',
 'Sheltered Total Homeless - Under 18, 2015':'Sheltered Total Homeless - Under 18',
 'Sheltered Total Homeless - Age 18 to 24, 2015':'Sheltered Total Homeless - Age 18 to 24',
 'Sheltered Total Homeless - Over 24, 2015':'Sheltered Total Homeless - Over 24',
 'Sheltered Total Homeless - Female, 2015':'Sheltered Total Homeless - Female',
 'Sheltered Total Homeless - Male, 2015':'Sheltered Total Homeless - Male',
 'Sheltered Total Homeless - Transgender, 2015':'Sheltered Total Homeless - Transgender',
 'Sheltered Total Homeless - Non-Hispanic/Non-Latino, 2015':'Sheltered Total Homeless - Non-Hispanic/Non-Latino',
 'Sheltered Total Homeless - Hispanic/Latino, 2015':'Sheltered Total Homeless - Hispanic/Latino',
 'Sheltered Total Homeless - White, 2015':'Sheltered Total Homeless - White',
 'Sheltered Total Homeless - Black or African American, 2015':'Sheltered Total Homeless - Black or African American',
 'Sheltered Total Homeless - Asian, 2015':'Sheltered Total Homeless - Asian',
 'Sheltered Total Homeless - American Indian or Alaska Native, 2015':'Sheltered Total Homeless - American Indian or Alaska Native',
 'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless - Multiple Races, 2015':'Sheltered Total Homeless - Multiple Races',
    
 'Unsheltered Homeless, 2015':'Unsheltered Homeless',
 'Unsheltered Homeless - Under 18, 2015':'Unsheltered Homeless - Under 18',
 'Unsheltered Homeless - Age 18 to 24, 2015':'Unsheltered Homeless - Age 18 to 24',
 'Unsheltered Homeless - Over 24, 2015':'Unsheltered Homeless - Over 24',
 'Unsheltered Homeless - Female, 2015':'Unsheltered Homeless - Female',
 'Unsheltered Homeless - Male, 2015':'Unsheltered Homeless - Male',
 'Unsheltered Homeless - Transgender, 2015':'Unsheltered Homeless - Transgender',
 'Unsheltered Homeless - Non-Hispanic/Non-Latino, 2015':'Unsheltered Homeless - Non-Hispanic/Non-Latino',
 'Unsheltered Homeless - Hispanic/Latino, 2015':'Unsheltered Homeless - Hispanic/Latino',
 'Unsheltered Homeless - White, 2015':'Unsheltered Homeless - White',
 'Unsheltered Homeless - Black or African American, 2015':'Unsheltered Homeless - Black or African American',
 'Unsheltered Homeless - Asian, 2015':'Unsheltered Homeless - Asian',
 'Unsheltered Homeless - American Indian or Alaska Native, 2015':'Unsheltered Homeless - American Indian or Alaska Native',
 'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander, 2015':'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless - Multiple Races, 2015':'Unsheltered Homeless - Multiple Races',
    
 'Overall Homeless Individuals, 2015':'Overall Homeless Individuals',
 'Overall Homeless Individuals - Under 18, 2015':'Overall Homeless Individuals - Under 18',
 'Overall Homeless Individuals - Age 18 to 24, 2015':'Overall Homeless Individuals - Age 18 to 24',
 'Overall Homeless Individuals - Over 24, 2015':'Overall Homeless Individuals - Over 24',
 'Overall Homeless Individuals - Female, 2015':'Overall Homeless Individuals - Female',
 'Overall Homeless Individuals - Male, 2015':'Overall Homeless Individuals - Male',
 'Overall Homeless Individuals - Transgender, 2015':'Overall Homeless Individuals - Transgender',
 'Overall Homeless Individuals - Non-Hispanic/Non-Latino, 2015':'Overall Homeless Individuals - Non-Hispanic/Non-Latino',
 'Overall Homeless Individuals - Hispanic/Latino, 2015':'Overall Homeless Individuals - Hispanic/Latino',
 'Overall Homeless Individuals - White, 2015':'Overall Homeless Individuals - White',
 'Overall Homeless Individuals - Black or African American, 2015':'Overall Homeless Individuals - Black or African American',
 'Overall Homeless Individuals - Asian, 2015':'Overall Homeless Individuals - Asian',
 'Overall Homeless Individuals - American Indian or Alaska Native, 2015':'Overall Homeless Individuals - American Indian or Alaska Native',
 'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015':'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless Individuals - Multiple Races, 2015':'Overall Homeless Individuals - Multiple Races',
    
 'Sheltered ES Homeless Individuals, 2015':'Sheltered ES Homeless Individuals',
 'Sheltered ES Homeless Individuals - Under 18, 2015':'Sheltered ES Homeless Individuals - Under 18',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2015':'Sheltered ES Homeless Individuals - Age 18 to 24',
 'Sheltered ES Homeless Individuals - Over 24, 2015':'Sheltered ES Homeless Individuals - Over 24',
 'Sheltered ES Homeless Individuals - Female, 2015':'Sheltered ES Homeless Individuals - Female',
 'Sheltered ES Homeless Individuals - Male, 2015':'Sheltered ES Homeless Individuals - Male',
 'Sheltered ES Homeless Individuals - Transgender, 2015':'Sheltered ES Homeless Individuals - Transgender',
 'Sheltered ES Homeless Individuals - Non-Hispanic/Non-Latino, 2015':'Sheltered ES Homeless Individuals - Non-Hispanic/Non-Latino',
 'Sheltered ES Homeless Individuals - Hispanic/Latino, 2015':'Sheltered ES Homeless Individuals - Hispanic/Latino',
 'Sheltered ES Homeless Individuals - White, 2015':'Sheltered ES Homeless Individuals - White',
 'Sheltered ES Homeless Individuals - Black or African American, 2015':'Sheltered ES Homeless Individuals - Black or African American',
 'Sheltered ES Homeless Individuals - Asian, 2015':'Sheltered ES Homeless Individuals - Asian',
 'Sheltered ES Homeless Individuals - American Indian or Alaska Native, 2015':'Sheltered ES Homeless Individuals - American Indian or Alaska Native',
 'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless Individuals - Multiple Races, 2015':'Sheltered ES Homeless Individuals - Multiple Races',

    
 'Sheltered TH Homeless Individuals, 2015':'Sheltered TH Homeless Individuals',
 'Sheltered TH Homeless Individuals - Under 18, 2015':'Sheltered TH Homeless Individuals - Under 18',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2015':'Sheltered TH Homeless Individuals - Age 18 to 24',
 'Sheltered TH Homeless Individuals - Over 24, 2015':'Sheltered TH Homeless Individuals - Over 24',
 'Sheltered TH Homeless Individuals - Female, 2015':'Sheltered TH Homeless Individuals - Female',
 'Sheltered TH Homeless Individuals - Male, 2015':'Sheltered TH Homeless Individuals - Male',
 'Sheltered TH Homeless Individuals - Transgender, 2015':'Sheltered TH Homeless Individuals - Transgender',
 'Sheltered TH Homeless Individuals - Non-Hispanic/Non-Latino, 2015':'Sheltered TH Homeless Individuals - Non-Hispanic/Non-Latino',
 'Sheltered TH Homeless Individuals - Hispanic/Latino, 2015':'Sheltered TH Homeless Individuals - Hispanic/Latino',
 'Sheltered TH Homeless Individuals - White, 2015':'Sheltered TH Homeless Individuals - White',
 'Sheltered TH Homeless Individuals - Black or African American, 2015':'Sheltered TH Homeless Individuals - Black or African American',
 'Sheltered TH Homeless Individuals - Asian, 2015':'Sheltered TH Homeless Individuals - Asian',
 'Sheltered TH Homeless Individuals - American Indian or Alaska Native, 2015':'Sheltered TH Homeless Individuals - American Indian or Alaska Native',
 'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless Individuals - Multiple Races, 2015':'Sheltered TH Homeless Individuals - Multiple Races',
    
 'Sheltered SH Homeless Individuals, 2015':'Sheltered SH Homeless Individuals',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2015':'Sheltered SH Homeless Individuals - Age 18 to 24',
 'Sheltered SH Homeless Individuals - Over 24, 2015':'Sheltered SH Homeless Individuals - Over 24',
 'Sheltered SH Homeless Individuals - Female, 2015':'Sheltered SH Homeless Individuals - Female',
 'Sheltered SH Homeless Individuals - Male, 2015':'Sheltered SH Homeless Individuals - Male',
 'Sheltered SH Homeless Individuals - Transgender, 2015':'Sheltered SH Homeless Individuals - Transgender',
 'Sheltered SH Homeless Individuals - Non-Hispanic/Non-Latino, 2015':'Sheltered SH Homeless Individuals - Non-Hispanic/Non-Latino',
 'Sheltered SH Homeless Individuals - Hispanic/Latino, 2015':'Sheltered SH Homeless Individuals - Hispanic/Latino',
 'Sheltered SH Homeless Individuals - White, 2015':'Sheltered SH Homeless Individuals - White',
 'Sheltered SH Homeless Individuals - Black or African American, 2015':'Sheltered SH Homeless Individuals - Black or African American',
 'Sheltered SH Homeless Individuals - Asian, 2015':'Sheltered SH Homeless Individuals - Asian',
 'Sheltered SH Homeless Individuals - American Indian or Alaska Native, 2015':'Sheltered SH Homeless Individuals - American Indian or Alaska Native',
 'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered SH Homeless Individuals - Multiple Races, 2015':'Sheltered SH Homeless Individuals - Multiple Races',
    
 'Sheltered Total Homeless Individuals, 2015':'Sheltered Total Homeless Individuals',
 'Sheltered Total Homeless Individuals - Under 18, 2015':'Sheltered Total Homeless Individuals - Under 18',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2015':'Sheltered Total Homeless Individuals - Age 18 to 24',
 'Sheltered Total Homeless Individuals - Over 24, 2015':'Sheltered Total Homeless Individuals - Over 24',
 'Sheltered Total Homeless Individuals - Female, 2015':'Sheltered Total Homeless Individuals - Female',
 'Sheltered Total Homeless Individuals - Male, 2015':'Sheltered Total Homeless Individuals - Male',
 'Sheltered Total Homeless Individuals - Transgender, 2015':'Sheltered Total Homeless Individuals - Transgender',
 'Sheltered Total Homeless Individuals - Non-Hispanic/Non-Latino, 2015':'Sheltered Total Homeless Individuals - Non-Hispanic/Non-Latino',
 'Sheltered Total Homeless Individuals - Hispanic/Latino, 2015':'Sheltered Total Homeless Individuals - Hispanic/Latino',
 'Sheltered Total Homeless Individuals - White, 2015':'Sheltered Total Homeless Individuals - White',
 'Sheltered Total Homeless Individuals - Black or African American, 2015':'Sheltered Total Homeless Individuals - Black or African American',
 'Sheltered Total Homeless Individuals - Asian, 2015':'Sheltered Total Homeless Individuals - Asian',
 'Sheltered Total Homeless Individuals - American Indian or Alaska Native, 2015':'Sheltered Total Homeless Individuals - American Indian or Alaska Native',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless Individuals - Multiple Races, 2015':'Sheltered Total Homeless Individuals - Multiple Races',
    
 'Unsheltered Homeless Individuals, 2015':'Unsheltered Homeless Individuals',
 'Unsheltered Homeless Individuals - Under 18, 2015':'Unsheltered Homeless Individuals - Under 18',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2015':'Unsheltered Homeless Individuals - Age 18 to 24',
 'Unsheltered Homeless Individuals - Over 24, 2015':'Unsheltered Homeless Individuals - Over 24',
 'Unsheltered Homeless Individuals - Female, 2015':'Unsheltered Homeless Individuals - Female',
 'Unsheltered Homeless Individuals - Male, 2015':'Unsheltered Homeless Individuals - Male',
 'Unsheltered Homeless Individuals - Transgender, 2015':'Unsheltered Homeless Individuals - Transgender',
 'Unsheltered Homeless Individuals - Non-Hispanic/Non-Latino, 2015':'Unsheltered Homeless Individuals - Non-Hispanic/Non-Latino',
 'Unsheltered Homeless Individuals - Hispanic/Latino, 2015':'Unsheltered Homeless Individuals - Hispanic/Latino',
 'Unsheltered Homeless Individuals - White, 2015':'Unsheltered Homeless Individuals - White',
 'Unsheltered Homeless Individuals - Black or African American, 2015':'Unsheltered Homeless Individuals - Black or African American',
 'Unsheltered Homeless Individuals - Asian, 2015':'Unsheltered Homeless Individuals - Asian',
 'Unsheltered Homeless Individuals - American Indian or Alaska Native, 2015':'Unsheltered Homeless Individuals - American Indian or Alaska Native',
 'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2015':'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless Individuals - Multiple Races, 2015':'Unsheltered Homeless Individuals - Multiple Races',
    
 'Overall Homeless People in Families, 2015':'Overall Homeless People in Families',
 'Overall Homeless People in Families - Under 18, 2015':'Overall Homeless People in Families - Under 18',
 'Overall Homeless People in Families - Age 18 to 24, 2015':'Overall Homeless People in Families - Age 18 to 24',
 'Overall Homeless People in Families - Over 24, 2015':'Overall Homeless People in Families - Over 24',
 'Overall Homeless People in Families - Female, 2015':'Overall Homeless People in Families',
 'Overall Homeless People in Families - Male, 2015':'Overall Homeless People in Families - Male',
 'Overall Homeless People in Families - Transgender, 2015':'Overall Homeless People in Families - Transgender',
 'Overall Homeless People in Families - Non-Hispanic/Non-Latino, 2015':'Overall Homeless People in Families - Non-Hispanic/Non-Latino',
 'Overall Homeless People in Families - Hispanic/Latino, 2015':'Overall Homeless People in Families - Hispanic/Latino',
 'Overall Homeless People in Families - White, 2015':'Overall Homeless People in Families - White',
 'Overall Homeless People in Families - Black or African American, 2015':'Overall Homeless People in Families - Black or African American',
 'Overall Homeless People in Families - Asian, 2015':'Overall Homeless People in Families - Asian',
 'Overall Homeless People in Families - American Indian or Alaska Native, 2015':'Overall Homeless People in Families - American Indian or Alaska Native',
 'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015':'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless People in Families - Multiple Races, 2015':'Overall Homeless People in Families - Multiple Races',
    
 'Sheltered ES Homeless People in Families, 2015':'Sheltered ES Homeless People in Families',
 'Sheltered ES Homeless People in Families - Under 18, 2015':'Sheltered ES Homeless People in Families - Under 18',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2015':'Sheltered ES Homeless People in Families - Age 18 to 24',
 'Sheltered ES Homeless People in Families - Over 24, 2015':'Sheltered ES Homeless People in Families - Over 24',
 'Sheltered ES Homeless People in Families - Female, 2015':'Sheltered ES Homeless People in Families - Female',
 'Sheltered ES Homeless People in Families - Male, 2015':'Sheltered ES Homeless People in Families - Male',
 'Sheltered ES Homeless People in Families - Transgender, 2015':'Sheltered ES Homeless People in Families - Transgender',
 'Sheltered ES Homeless People in Families - Non-Hispanic/Non-Latino, 2015':'Sheltered ES Homeless People in Families - Non-Hispanic/Non-Latino',
 'Sheltered ES Homeless People in Families - Hispanic/Latino, 2015':'Sheltered ES Homeless People in Families - Hispanic/Latino',
 'Sheltered ES Homeless People in Families - White, 2015':'Sheltered ES Homeless People in Families - White',
 'Sheltered ES Homeless People in Families - Black or African American, 2015':'Sheltered ES Homeless People in Families - Black or African American',
 'Sheltered ES Homeless People in Families - Asian, 2015':'Sheltered ES Homeless People in Families - Asian',
 'Sheltered ES Homeless People in Families - American Indian or Alaska Native, 2015':'Sheltered ES Homeless People in Families - American Indian or Alaska Native',
 'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless People in Families - Multiple Races, 2015':'Sheltered ES Homeless People in Families - Multiple Races',
    
 'Sheltered TH Homeless People in Families, 2015':'Sheltered TH Homeless People in Families',
 'Sheltered TH Homeless People in Families - Under 18, 2015':'Sheltered TH Homeless People in Families - Under 18',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2015':'Sheltered TH Homeless People in Families - Age 18 to 24',
 'Sheltered TH Homeless People in Families - Over 24, 2015':'Sheltered TH Homeless People in Families - Over 24',
 'Sheltered TH Homeless People in Families - Female, 2015':'Sheltered TH Homeless People in Families - Female',
 'Sheltered TH Homeless People in Families - Male, 2015':'Sheltered TH Homeless People in Families - Male',
 'Sheltered TH Homeless People in Families - Transgender, 2015':'Sheltered TH Homeless People in Families - Transgender',
 'Sheltered TH Homeless People in Families - Non-Hispanic/Non-Latino, 2015':'Sheltered TH Homeless People in Families - Non-Hispanic/Non-Latino',
 'Sheltered TH Homeless People in Families - Hispanic/Latino, 2015':'Sheltered TH Homeless People in Families - Hispanic/Latino',
 'Sheltered TH Homeless People in Families - White, 2015':'Sheltered TH Homeless People in Families - White',
 'Sheltered TH Homeless People in Families - Black or African American, 2015':'Sheltered TH Homeless People in Families - Black or African American',
 'Sheltered TH Homeless People in Families - Asian, 2015':'Sheltered TH Homeless People in Families - Asian',
 'Sheltered TH Homeless People in Families - American Indian or Alaska Native, 2015':'Sheltered TH Homeless People in Families - American Indian or Alaska Native',
 'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless People in Families - Multiple Races, 2015':'Sheltered TH Homeless People in Families - Multiple Races',
    
    
 'Sheltered Total Homeless People in Families, 2015':'Sheltered Total Homeless People in Families',
 'Sheltered Total Homeless People in Families - Under 18, 2015':'Sheltered Total Homeless People in Families - Under 18',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2015':'Sheltered Total Homeless People in Families - Age 18 to 24',
 'Sheltered Total Homeless People in Families - Over 24, 2015':'Sheltered Total Homeless People in Families - Over 24',
 'Sheltered Total Homeless People in Families - Female, 2015':'Sheltered Total Homeless People in Families - Female',
 'Sheltered Total Homeless People in Families - Male, 2015':'Sheltered Total Homeless People in Families - Male',
 'Sheltered Total Homeless People in Families - Transgender, 2015':'Sheltered Total Homeless People in Families - Transgender',
 'Sheltered Total Homeless People in Families - Non-Hispanic/Non-Latino, 2015':'Sheltered Total Homeless People in Families - Non-Hispanic/Non-Latino',
 'Sheltered Total Homeless People in Families - Hispanic/Latino, 2015':'Sheltered Total Homeless People in Families - Hispanic/Latino',
 'Sheltered Total Homeless People in Families - White, 2015':'Sheltered Total Homeless People in Families - White',
 'Sheltered Total Homeless People in Families - Black or African American, 2015':'Sheltered Total Homeless People in Families - Black or African American',
 'Sheltered Total Homeless People in Families - Asian, 2015':'Sheltered Total Homeless People in Families - Asian',
 'Sheltered Total Homeless People in Families - American Indian or Alaska Native, 2015':'Sheltered Total Homeless People in Families - American Indian or Alaska Native',
 'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless People in Families - Multiple Races, 2015':'Sheltered Total Homeless People in Families - Multiple Races',
    
 'Unsheltered Homeless People in Families, 2015':'Unsheltered Homeless People in Families',
 'Unsheltered Homeless People in Families - Under 18, 2015':'Unsheltered Homeless People in Families - Under 18',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2015':'Unsheltered Homeless People in Families - Age 18 to 24',
 'Unsheltered Homeless People in Families - Over 24, 2015':'Unsheltered Homeless People in Families - Over 24',
 'Unsheltered Homeless People in Families - Female, 2015':'Unsheltered Homeless People in Families - Female',
 'Unsheltered Homeless People in Families - Male, 2015':'Unsheltered Homeless People in Families - Male',
 'Unsheltered Homeless People in Families - Transgender, 2015':'Unsheltered Homeless People in Families - Transgender',
 'Unsheltered Homeless People in Families - Non-Hispanic/Non-Latino, 2015':'Unsheltered Homeless People in Families - Non-Hispanic/Non-Latino',
 'Unsheltered Homeless People in Families - Hispanic/Latino, 2015':'Unsheltered Homeless People in Families - Hispanic/Latino',
 'Unsheltered Homeless People in Families - White, 2015':'Unsheltered Homeless People in Families - White',
 'Unsheltered Homeless People in Families - Black or African American, 2015':'Unsheltered Homeless People in Families - Black or African American',
 'Unsheltered Homeless People in Families - Asian, 2015':'Unsheltered Homeless People in Families - Asian',
 'Unsheltered Homeless People in Families - American Indian or Alaska Native, 2015':'Unsheltered Homeless People in Families - American Indian or Alaska Native',
 'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2015':'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless People in Families - Multiple Races, 2015':'Unsheltered Homeless People in Families - Multiple Races',
    
 'Overall Homeless Family Households, 2015':'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households, 2015':'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households, 2015':'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households, 2015':'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households, 2015':'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless, 2015':'Overall Chronically Homeless',
 'Sheltered ES Chronically Homeless, 2015':'Sheltered ES Chronically Homeless',
 'Sheltered SH Chronically Homeless, 2015':'Sheltered SH Chronically Homeless',
 'Sheltered Total Chronically Homeless, 2015':'Sheltered Total Chronically Homeless',
 'Unsheltered Chronically Homeless, 2015':'Unsheltered Chronically Homeless',
 'Overall Chronically Homeless Individuals, 2015':'Overall Chronically Homeless Individuals',
 'Sheltered ES Chronically Homeless Individuals, 2015':'Sheltered ES Chronically Homeless Individuals',
 'Sheltered SH Chronically Homeless Individuals, 2015':'Sheltered SH Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals, 2015':'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals, 2015':'Unsheltered Chronically Homeless Individuals',
 'Overall Chronically Homeless People in Families, 2015':'Overall Chronically Homeless People in Families',
 'Sheltered ES Chronically Homeless People in Families, 2015':'Sheltered ES Chronically Homeless People in Families',
 'Sheltered Total Chronically Homeless People in Families, 2015':'Sheltered Total Chronically Homeless People in Families',
 'Unsheltered Chronically Homeless People in Families, 2015':'Unsheltered Chronically Homeless People in Families',
    
 'Overall Homeless Veterans, 2015':'Overall Homeless Veterans',
 'Overall Homeless Veterans - Female, 2015':'Overall Homeless Veterans - Female',
 'Overall Homeless Veterans - Male, 2015':'Overall Homeless Veterans - Male',
 'Overall Homeless Veterans - Transgender, 2015':'Overall Homeless Veterans - Transgender',
 'Overall Homeless Veterans - Non-Hispanic/Non-Latino, 2015':'Overall Homeless Veterans - Non-Hispanic/Non-Latino',
 'Overall Homeless Veterans - Hispanic/Latino, 2015':'Overall Homeless Veterans - Hispanic/Latino',
 'Overall Homeless Veterans - White, 2015':'Overall Homeless Veterans - White',
 'Overall Homeless Veterans - Black or African American, 2015':'Overall Homeless Veterans - Black or African American',
 'Overall Homeless Veterans - Asian, 2015':'Overall Homeless Veterans - Asian',
 'Overall Homeless Veterans - American Indian or Alaska Native, 2015':'Overall Homeless Veterans - American Indian or Alaska Native',
 'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015':'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless Veterans - Multiple Races, 2015':'Overall Homeless Veterans - Multiple Races',
    
 'Sheltered ES Homeless Veterans, 2015':'Sheltered ES Homeless Veterans',
 'Sheltered ES Homeless Veterans - Female, 2015':'Sheltered ES Homeless Veterans - Female',
 'Sheltered ES Homeless Veterans - Male, 2015':'Sheltered ES Homeless Veterans - Male',
 'Sheltered ES Homeless Veterans - Transgender, 2015':'Sheltered ES Homeless Veterans - Transgender',
 'Sheltered ES Homeless Veterans - Non-Hispanic/Non-Latino, 2015':'Sheltered ES Homeless Veterans - Non-Hispanic/Non-Latino',
 'Sheltered ES Homeless Veterans - Hispanic/Latino, 2015':'Sheltered ES Homeless Veterans - Hispanic/Latino',
 'Sheltered ES Homeless Veterans - White, 2015':'Sheltered ES Homeless Veterans - White',
 'Sheltered ES Homeless Veterans - Black or African American, 2015':'Sheltered ES Homeless Veterans - Black or African American',
 'Sheltered ES Homeless Veterans - Asian, 2015':'Sheltered ES Homeless Veterans - Asian',
 'Sheltered ES Homeless Veterans - American Indian or Alaska Native, 2015':'Sheltered ES Homeless Veterans - American Indian or Alaska Native',
 'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless Veterans - Multiple Races, 2015':'Sheltered ES Homeless Veterans - Multiple Races',
    
 'Sheltered TH Homeless Veterans, 2015':'Sheltered TH Homeless Veterans',
 'Sheltered TH Homeless Veterans - Female, 2015':'Sheltered TH Homeless Veterans - Female',
 'Sheltered TH Homeless Veterans - Male, 2015':'Sheltered TH Homeless Veterans - Male',
 'Sheltered TH Homeless Veterans - Transgender, 2015':'Sheltered TH Homeless Veterans - Transgender',
 'Sheltered TH Homeless Veterans - Non-Hispanic/Non-Latino, 2015':'Sheltered TH Homeless Veterans - Non-Hispanic/Non-Latino',
 'Sheltered TH Homeless Veterans - Hispanic/Latino, 2015':'Sheltered TH Homeless Veterans - Hispanic/Latino',
 'Sheltered TH Homeless Veterans - White, 2015':'Sheltered TH Homeless Veterans - White',
 'Sheltered TH Homeless Veterans - Black or African American, 2015':'Sheltered TH Homeless Veterans - Black or African American',
 'Sheltered TH Homeless Veterans - Asian, 2015':'Sheltered TH Homeless Veterans - Asian',
 'Sheltered TH Homeless Veterans - American Indian or Alaska Native, 2015':'Sheltered TH Homeless Veterans - American Indian or Alaska Native',
 'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless Veterans - Multiple Races, 2015':'Sheltered TH Homeless Veterans - Multiple Races',
    
 'Sheltered SH Homeless Veterans, 2015':'Sheltered SH Homeless Veterans',
 'Sheltered SH Homeless Veterans - Female, 2015':'Sheltered SH Homeless Veterans - Female',
 'Sheltered SH Homeless Veterans - Male, 2015':'Sheltered SH Homeless Veterans - Male',
 'Sheltered SH Homeless Veterans - Transgender, 2015':'Sheltered SH Homeless Veterans - Transgender',
 'Sheltered SH Homeless Veterans - Non-Hispanic/Non-Latino, 2015':'Sheltered SH Homeless Veterans - Non-Hispanic/Non-Latino',
 'Sheltered SH Homeless Veterans - Hispanic/Latino, 2015':'Sheltered SH Homeless Veterans - Hispanic/Latino',
 'Sheltered SH Homeless Veterans - White, 2015':'Sheltered SH Homeless Veterans - White',
 'Sheltered SH Homeless Veterans - Black or African American, 2015':'Sheltered SH Homeless Veterans - Black or African American',
 'Sheltered SH Homeless Veterans - Asian, 2015':'Sheltered SH Homeless Veterans - Asian',
 'Sheltered SH Homeless Veterans - American Indian or Alaska Native, 2015':'Sheltered SH Homeless Veterans - American Indian or Alaska Native',
 'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered SH Homeless Veterans - Multiple Races, 2015':'Sheltered SH Homeless Veterans - Multiple Races',
    
 'Sheltered Total Homeless Veterans, 2015':'Sheltered Total Homeless Veterans',
 'Sheltered Total Homeless Veterans - Female, 2015':'Sheltered Total Homeless Veterans - Female',
 'Sheltered Total Homeless Veterans - Male, 2015':'Sheltered Total Homeless Veterans - Male',
 'Sheltered Total Homeless Veterans - Transgender, 2015':'Sheltered Total Homeless Veterans - Transgender',
 'Sheltered Total Homeless Veterans - Non-Hispanic/Non-Latino, 2015':'Sheltered Total Homeless Veterans - Non-Hispanic/Non-Latino',
 'Sheltered Total Homeless Veterans - Hispanic/Latino, 2015':'Sheltered Total Homeless Veterans - Hispanic/Latino',
 'Sheltered Total Homeless Veterans - White, 2015':'Sheltered Total Homeless Veterans - White',
 'Sheltered Total Homeless Veterans - Black or African American, 2015':'Sheltered Total Homeless Veterans - Black or African American',
 'Sheltered Total Homeless Veterans - Asian, 2015':'Sheltered Total Homeless Veterans - Asian',
 'Sheltered Total Homeless Veterans - American Indian or Alaska Native, 2015':'Sheltered Total Homeless Veterans - American Indian or Alaska Native',
 'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015':'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless Veterans - Multiple Races, 2015':'Sheltered Total Homeless Veterans - Multiple Races',
    
 'Unsheltered Homeless Veterans, 2015':'Unsheltered Homeless Veterans',
 'Unsheltered Homeless Veterans - Female, 2015':'Unsheltered Homeless Veterans - Female',
 'Unsheltered Homeless Veterans - Male, 2015':'Unsheltered Homeless Veterans - Male',
 'Unsheltered Homeless Veterans - Transgender, 2015':'Unsheltered Homeless Veterans - Transgender',
 'Unsheltered Homeless Veterans - Non-Hispanic/Non-Latino, 2015':'Unsheltered Homeless Veterans - Non-Hispanic/Non-Latino',
 'Unsheltered Homeless Veterans - Hispanic/Latino, 2015':'Unsheltered Homeless Veterans - Hispanic/Latino',
 'Unsheltered Homeless Veterans - White, 2015':'Unsheltered Homeless Veterans - White',
 'Unsheltered Homeless Veterans - Black or African American, 2015':'Unsheltered Homeless Veterans - Black or African American',
 'Unsheltered Homeless Veterans - Asian, 2015':'Unsheltered Homeless Veterans - Asian',
 'Unsheltered Homeless Veterans - American Indian or Alaska Native, 2015':'Unsheltered Homeless Veterans - American Indian or Alaska Native',
 'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2015':'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless Veterans - Multiple Races, 2015':'Unsheltered Homeless Veterans - Multiple Races',
    
 'Overall Homeless Unaccompanied Youth (Under 25), 2015':'Overall Homeless Unaccompanied Youth (Under 25)',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25), 2015':'Sheltered ES Homeless Unaccompanied Youth (Under 25)',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25), 2015':'Sheltered TH Homeless Unaccompanied Youth (Under 25)',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25), 2015':'Sheltered SH Homeless Unaccompanied Youth (Under 25)',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25), 2015':'Sheltered Total Homeless Unaccompanied Youth (Under 25)',
 'Unsheltered Homeless Unaccompanied Youth (Under 25), 2015':'Unsheltered Homeless Unaccompanied Youth (Under 25)',
 'Overall Homeless Unaccompanied Youth Under 18, 2015':'Overall Homeless Unaccompanied Youth Under 18',
 'Sheltered ES Homeless Unaccompanied Youth Under 18, 2015':'Sheltered ES Homeless Unaccompanied Youth Under 18',
 'Sheltered TH Homeless Unaccompanied Youth Under 18, 2015':'Sheltered TH Homeless Unaccompanied Youth Under 18',
 'Sheltered SH Homeless Unaccompanied Youth Under 18, 2015':'Sheltered SH Homeless Unaccompanied Youth Under 18',
 'Sheltered Total Homeless Unaccompanied Youth Under 18, 2015':'Sheltered Total Homeless Unaccompanied Youth Under 18',
 'Unsheltered Homeless Unaccompanied Youth Under 18, 2015':'Unsheltered Homeless Unaccompanied Youth Under 18',
 'Overall Homeless Unaccompanied Youth Age 18-24, 2015':'Overall Homeless Unaccompanied Youth Age 18-24',
 'Sheltered ES Homeless Unaccompanied Youth Age 18-24, 2015':'Sheltered ES Homeless Unaccompanied Youth Age 18-24',
 'Sheltered TH Homeless Unaccompanied Youth Age 18-24, 2015':'Sheltered TH Homeless Unaccompanied Youth Age 18-24',
 'Sheltered SH Homeless Unaccompanied Youth Age 18-24, 2015':'Sheltered SH Homeless Unaccompanied Youth Age 18-24',
 'Sheltered Total Homeless Unaccompanied Youth Age 18-24, 2015':'Sheltered Total Homeless Unaccompanied Youth Age 18-24',
 'Unsheltered Homeless Unaccompanied Youth Age 18-24, 2015':'Unsheltered Homeless Unaccompanied Youth Age 18-24',
 'Overall Homeless Parenting Youth (Under 25), 2015':'Overall Homeless Parenting Youth (Under 25)',
 'Sheltered ES Homeless Parenting Youth (Under 25), 2015':'Sheltered ES Homeless Parenting Youth (Under 25)',
 'Sheltered TH Homeless Parenting Youth (Under 25), 2015':'Sheltered TH Homeless Parenting Youth (Under 25)',
 'Sheltered Total Homeless Parenting Youth (Under 25), 2015':'Sheltered Total Homeless Parenting Youth (Under 25)',
 'Unsheltered Homeless Parenting Youth (Under 25), 2015':'Unsheltered Homeless Parenting Youth (Under 25)',
 'Overall Homeless Parenting Youth Under 18, 2015':'Overall Homeless Parenting Youth Under 18',
 'Sheltered ES Homeless Parenting Youth Under 18, 2015':'Sheltered ES Homeless Parenting Youth Under 18',
 'Sheltered TH Homeless Parenting Youth Under 18, 2015':'Sheltered TH Homeless Parenting Youth Under 18',
 'Sheltered Total Homeless Parenting Youth Under 18, 2015':'Sheltered Total Homeless Parenting Youth Under 18',
 'Unsheltered Homeless Parenting Youth Under 18, 2015':'Unsheltered Homeless Parenting Youth Under 18',
 'Overall Homeless Parenting Youth Age 18-24, 2015':'Overall Homeless Parenting Youth Age 18-24',
 'Sheltered ES Homeless Parenting Youth Age 18-24, 2015':'Sheltered ES Homeless Parenting Youth Age 18-24',
 'Sheltered TH Homeless Parenting Youth Age 18-24, 2015':'Sheltered TH Homeless Parenting Youth Age 18-24',
 'Sheltered Total Homeless Parenting Youth Age 18-24, 2015':'Sheltered Total Homeless Parenting Youth Age 18-24',
 'Unsheltered Homeless Parenting Youth Age 18-24, 2015':'Unsheltered Homeless Parenting Youth Age 18-24',
 'Overall Homeless Children of Parenting Youth, 2015':'Overall Homeless Children of Parenting Youth',
 'Sheltered ES Homeless Children of Parenting Youth, 2015':'Sheltered ES Homeless Children of Parenting Youth',
 'Sheltered TH Homeless Children of Parenting Youth, 2015':'Sheltered TH Homeless Children of Parenting Youth',
 'Sheltered Total Homeless Children of Parenting Youth, 2015':'Sheltered Total Homeless Children of Parenting Youth',
 'Unsheltered Homeless Children of Parenting Youth, 2015': 'Unsheltered Homeless Children of Parenting Youth'
       }
data_2015_df.rename(columns=dict, inplace=True)

In [117]:
data_2015_df.head()

,State,Year,Number of CoCs,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK,2015,2.0,"1,956",411,197,"1,348",773,"1,181",2,...,18,8,10,18,0,21,9,12,21,0
1,AL,2015,8.0,"3,970",716,271,"2,983","1,532","2,427",11,...,20,7,9,16,4,35,12,17,29,6
2,AR,2015,7.0,"2,560",417,243,"1,900",978,"1,582",0,...,22,17,5,22,0,20,10,10,20,0
3,AS,2015,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2015,3.0,"9,896","2,124",824,"6,948","3,966","5,916",14,...,160,43,107,150,10,194,51,134,185,9

In [118]:
# Export df to sql table
data_2015_df.to_sql(name='data_2015', con=engine, if_exists='replace')

# 2016

In [119]:
# Import csv into pandas dataframe 2016
data_2016 = pd.read_csv("Resources/2016-PIT-Counts-by-State.csv")
data_2016_df = pd.DataFrame(data_2016)
data_2016_df.head()

,State,Number of CoCs,"Overall Homeless, 2016","Overall Homeless - Under 18, 2016","Overall Homeless - Age 18 to 24, 2016","Overall Homeless - Over 24, 2016","Overall Homeless - Female, 2016","Overall Homeless - Male, 2016","Overall Homeless - Transgender, 2016","Overall Homeless - Non-Hispanic/Non-Latino, 2016",...,"Overall Homeless Parenting Youth Age 18-24, 2016","Sheltered ES Homeless Parenting Youth Age 18-24, 2016","Sheltered TH Homeless Parenting Youth Age 18-24, 2016","Sheltered Total Homeless Parenting Youth Age 18-24, 2016","Unsheltered Homeless Parenting Youth Age 18-24, 2016","Overall Homeless Children of Parenting Youth, 2016","Sheltered ES Homeless Children of Parenting Youth, 2016","Sheltered TH Homeless Children of Parenting Youth, 2016","Sheltered Total Homeless Children of Parenting Youth, 2016","Unsheltered Homeless Children of Parenting Youth, 2016"
0,AK,2.0,"1,940",274,173,"1,493",808,"1,127",5,"1,797",...,9,2,7,9,0,10,2,8,10,0
1,AL,8.0,"4,111",681,304,"3,126","1,733","2,366",12,"4,027",...,26,14,6,20,6,45,22,17,39,6
2,AR,7.0,"2,463",432,197,"1,834","1,047","1,415",1,"2,377",...,13,12,1,13,0,13,12,1,13,0
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,"9,707","2,022",733,"6,952","3,685","6,005",17,"7,342",...,149,69,80,149,0,222,96,126,222,0

In [120]:
# Create column for the year and set to 2016
data_2016_df["Year"] = 2016
data_2016_df.head()

,State,Number of CoCs,"Overall Homeless, 2016","Overall Homeless - Under 18, 2016","Overall Homeless - Age 18 to 24, 2016","Overall Homeless - Over 24, 2016","Overall Homeless - Female, 2016","Overall Homeless - Male, 2016","Overall Homeless - Transgender, 2016","Overall Homeless - Non-Hispanic/Non-Latino, 2016",...,"Sheltered ES Homeless Parenting Youth Age 18-24, 2016","Sheltered TH Homeless Parenting Youth Age 18-24, 2016","Sheltered Total Homeless Parenting Youth Age 18-24, 2016","Unsheltered Homeless Parenting Youth Age 18-24, 2016","Overall Homeless Children of Parenting Youth, 2016","Sheltered ES Homeless Children of Parenting Youth, 2016","Sheltered TH Homeless Children of Parenting Youth, 2016","Sheltered Total Homeless Children of Parenting Youth, 2016","Unsheltered Homeless Children of Parenting Youth, 2016",Year
0,AK,2.0,"1,940",274,173,"1,493",808,"1,127",5,"1,797",...,2,7,9,0,10,2,8,10,0,2016
1,AL,8.0,"4,111",681,304,"3,126","1,733","2,366",12,"4,027",...,14,6,20,6,45,22,17,39,6,2016
2,AR,7.0,"2,463",432,197,"1,834","1,047","1,415",1,"2,377",...,12,1,13,0,13,12,1,13,0,2016
3,AS,0.0,,,,,,,,,...,,,,,,,,,,2016
4,AZ,3.0,"9,707","2,022",733,"6,952","3,685","6,005",17,"7,342",...,69,80,149,0,222,96,126,222,0,2016

In [121]:
# Get Column Names
cols_2016 = data_2016_df.columns.tolist()
cols_2016

['State',
 'Number of CoCs',
 'Overall Homeless, 2016',
 'Overall Homeless - Under 18, 2016',
 'Overall Homeless - Age 18 to 24, 2016',
 'Overall Homeless - Over 24, 2016',
 'Overall Homeless - Female, 2016',
 'Overall Homeless - Male, 2016',
 'Overall Homeless - Transgender, 2016',
 'Overall Homeless - Non-Hispanic/Non-Latino, 2016',
 'Overall Homeless - Hispanic/Latino, 2016',
 'Overall Homeless - White, 2016',
 'Overall Homeless - Black or African American, 2016',
 'Overall Homeless - Asian, 2016',
 'Overall Homeless - American Indian or Alaska Native, 2016',
 'Overall Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Overall Homeless - Multiple Races, 2016',
 'Sheltered ES Homeless, 2016',
 'Sheltered ES Homeless - Under 18, 2016',
 'Sheltered ES Homeless - Age 18 to 24, 2016',
 'Sheltered ES Homeless - Over 24, 2016',
 'Sheltered ES Homeless - Female, 2016',
 'Sheltered ES Homeless - Male, 2016',
 'Sheltered ES Homeless - Transgender, 2016',
 'Sheltered ES Homeless - Non-Hispanic/Non-Latino, 2016',
 'Sheltered ES Homeless - Hispanic/Latino, 2016',
 'Sheltered ES Homeless - White, 2016',
 'Sheltered ES Homeless - Black or African American, 2016',
 'Sheltered ES Homeless - Asian, 2016',
 'Sheltered ES Homeless - American Indian or Alaska Native, 2016',
 'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered ES Homeless - Multiple Races, 2016',
 'Sheltered TH Homeless, 2016',
 'Sheltered TH Homeless - Under 18, 2016',
 'Sheltered TH Homeless - Age 18 to 24, 2016',
 'Sheltered TH Homeless - Over 24, 2016',
 'Sheltered TH Homeless - Female, 2016',
 'Sheltered TH Homeless - Male, 2016',
 'Sheltered TH Homeless - Transgender, 2016',
 'Sheltered TH Homeless - Non-Hispanic/Non-Latino, 2016',
 'Sheltered TH Homeless - Hispanic/Latino, 2016',
 'Sheltered TH Homeless - White, 2016',
 'Sheltered TH Homeless - Black or African American, 2016',
 'Sheltered TH Homeless - Asian, 2016',
 'Sheltered TH Homeless - American Indian or Alaska Native, 2016',
 'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered TH Homeless - Multiple Races, 2016',
 'Sheltered SH Homeless, 2016',
 'Sheltered SH Homeless - Age 18 to 24, 2016',
 'Sheltered SH Homeless - Over 24, 2016',
 'Sheltered SH Homeless - Female, 2016',
 'Sheltered SH Homeless - Male, 2016',
 'Sheltered SH Homeless - Transgender, 2016',
 'Sheltered SH Homeless - Non-Hispanic/Non-Latino, 2016',
 'Sheltered SH Homeless - Hispanic/Latino, 2016',
 'Sheltered SH Homeless - White, 2016',
 'Sheltered SH Homeless - Black or African American, 2016',
 'Sheltered SH Homeless - Asian, 2016',
 'Sheltered SH Homeless - American Indian or Alaska Native, 2016',
 'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered SH Homeless - Multiple Races, 2016',
 'Sheltered Total Homeless, 2016',
 'Sheltered Total Homeless - Under 18, 2016',
 'Sheltered Total Homeless - Age 18 to 24, 2016',
 'Sheltered Total Homeless - Over 24, 2016',
 'Sheltered Total Homeless - Female, 2016',
 'Sheltered Total Homeless - Male, 2016',
 'Sheltered Total Homeless - Transgender, 2016',
 'Sheltered Total Homeless - Non-Hispanic/Non-Latino, 2016',
 'Sheltered Total Homeless - Hispanic/Latino, 2016',
 'Sheltered Total Homeless - White, 2016',
 'Sheltered Total Homeless - Black or African American, 2016',
 'Sheltered Total Homeless - Asian, 2016',
 'Sheltered Total Homeless - American Indian or Alaska Native, 2016',
 'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered Total Homeless - Multiple Races, 2016',
 'Unsheltered Homeless, 2016',
 'Unsheltered Homeless - Under 18, 2016',
 'Unsheltered Homeless - Age 18 to 24, 2016',
 'Unsheltered Homeless - Over 24, 2016',
 'Unsheltered Homeless - Female, 2016',
 'Unsheltered Homeless - Male, 2016',
 'Unsheltered Homeless - Transgender, 2016',
 'Unsheltered Homeless - Non-Hispanic/Non-Latino, 2016',
 'Unsheltered Homeless - Hispanic/Latino, 2016',
 'Unsheltered Homeless - White, 2016',
 'Unsheltered Homeless - Black or African American, 2016',
 'Unsheltered Homeless - Asian, 2016',
 'Unsheltered Homeless - American Indian or Alaska Native, 2016',
 'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Unsheltered Homeless - Multiple Races, 2016',
 'Overall Homeless Individuals, 2016',
 'Overall Homeless Individuals - Under 18, 2016',
 'Overall Homeless Individuals - Age 18 to 24, 2016',
 'Overall Homeless Individuals - Over 24, 2016',
 'Overall Homeless Individuals - Female, 2016',
 'Overall Homeless Individuals - Male, 2016',
 'Overall Homeless Individuals - Transgender, 2016',
 'Overall Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Overall Homeless Individuals - Hispanic/Latino, 2016',
 'Overall Homeless Individuals - White, 2016',
 'Overall Homeless Individuals - Black or African American, 2016',
 'Overall Homeless Individuals - Asian, 2016',
 'Overall Homeless Individuals - American Indian or Alaska Native, 2016',
 'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Overall Homeless Individuals - Multiple Races, 2016',
 'Sheltered ES Homeless Individuals, 2016',
 'Sheltered ES Homeless Individuals - Under 18, 2016',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2016',
 'Sheltered ES Homeless Individuals - Over 24, 2016',
 'Sheltered ES Homeless Individuals - Female, 2016',
 'Sheltered ES Homeless Individuals - Male, 2016',
 'Sheltered ES Homeless Individuals - Transgender, 2016',
 'Sheltered ES Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Sheltered ES Homeless Individuals - Hispanic/Latino, 2016',
 'Sheltered ES Homeless Individuals - White, 2016',
 'Sheltered ES Homeless Individuals - Black or African American, 2016',
 'Sheltered ES Homeless Individuals - Asian, 2016',
 'Sheltered ES Homeless Individuals - American Indian or Alaska Native, 2016',
 'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered ES Homeless Individuals - Multiple Races, 2016',
 'Sheltered TH Homeless Individuals, 2016',
 'Sheltered TH Homeless Individuals - Under 18, 2016',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2016',
 'Sheltered TH Homeless Individuals - Over 24, 2016',
 'Sheltered TH Homeless Individuals - Female, 2016',
 'Sheltered TH Homeless Individuals - Male, 2016',
 'Sheltered TH Homeless Individuals - Transgender, 2016',
 'Sheltered TH Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Sheltered TH Homeless Individuals - Hispanic/Latino, 2016',
 'Sheltered TH Homeless Individuals - White, 2016',
 'Sheltered TH Homeless Individuals - Black or African American, 2016',
 'Sheltered TH Homeless Individuals - Asian, 2016',
 'Sheltered TH Homeless Individuals - American Indian or Alaska Native, 2016',
 'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered TH Homeless Individuals - Multiple Races, 2016',
 'Sheltered SH Homeless Individuals, 2016',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2016',
 'Sheltered SH Homeless Individuals - Over 24, 2016',
 'Sheltered SH Homeless Individuals - Female, 2016',
 'Sheltered SH Homeless Individuals - Male, 2016',
 'Sheltered SH Homeless Individuals - Transgender, 2016',
 'Sheltered SH Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Sheltered SH Homeless Individuals - Hispanic/Latino, 2016',
 'Sheltered SH Homeless Individuals - White, 2016',
 'Sheltered SH Homeless Individuals - Black or African American, 2016',
 'Sheltered SH Homeless Individuals - Asian, 2016',
 'Sheltered SH Homeless Individuals - American Indian or Alaska Native, 2016',
 'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered SH Homeless Individuals - Multiple Races, 2016',
 'Sheltered Total Homeless Individuals, 2016',
 'Sheltered Total Homeless Individuals - Under 18, 2016',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2016',
 'Sheltered Total Homeless Individuals - Over 24, 2016',
 'Sheltered Total Homeless Individuals - Female, 2016',
 'Sheltered Total Homeless Individuals - Male, 2016',
 'Sheltered Total Homeless Individuals - Transgender, 2016',
 'Sheltered Total Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Sheltered Total Homeless Individuals - Hispanic/Latino, 2016',
 'Sheltered Total Homeless Individuals - White, 2016',
 'Sheltered Total Homeless Individuals - Black or African American, 2016',
 'Sheltered Total Homeless Individuals - Asian, 2016',
 'Sheltered Total Homeless Individuals - American Indian or Alaska Native, 2016',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered Total Homeless Individuals - Multiple Races, 2016',
 'Unsheltered Homeless Individuals, 2016',
 'Unsheltered Homeless Individuals - Under 18, 2016',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2016',
 'Unsheltered Homeless Individuals - Over 24, 2016',
 'Unsheltered Homeless Individuals - Female, 2016',
 'Unsheltered Homeless Individuals - Male, 2016',
 'Unsheltered Homeless Individuals - Transgender, 2016',
 'Unsheltered Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Unsheltered Homeless Individuals - Hispanic/Latino, 2016',
 'Unsheltered Homeless Individuals - White, 2016',
 'Unsheltered Homeless Individuals - Black or African American, 2016',
 'Unsheltered Homeless Individuals - Asian, 2016',
 'Unsheltered Homeless Individuals - American Indian or Alaska Native, 2016',
 'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Unsheltered Homeless Individuals - Multiple Races, 2016',
 'Overall Homeless People in Families, 2016',
 'Overall Homeless People in Families - Under 18, 2016',
 'Overall Homeless People in Families - Age 18 to 24, 2016',
 'Overall Homeless People in Families - Over 24, 2016',
 'Overall Homeless People in Families - Female, 2016',
 'Overall Homeless People in Families - Male, 2016',
 'Overall Homeless People in Families - Transgender, 2016',
 'Overall Homeless People in Families - Non-Hispanic/Non-Latino, 2016',
 'Overall Homeless People in Families - Hispanic/Latino, 2016',
 'Overall Homeless People in Families - White, 2016',
 'Overall Homeless People in Families - Black or African American, 2016',
 'Overall Homeless People in Families - Asian, 2016',
 'Overall Homeless People in Families - American Indian or Alaska Native, 2016',
 'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016',
 'Overall Homeless People in Families - Multiple Races, 2016',
 'Sheltered ES Homeless People in Families, 2016',
 'Sheltered ES Homeless People in Families - Under 18, 2016',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2016',
 'Sheltered ES Homeless People in Families - Over 24, 2016',
 'Sheltered ES Homeless People in Families - Female, 2016',
 'Sheltered ES Homeless People in Families - Male, 2016',
 'Sheltered ES Homeless People in Families - Transgender, 2016',
 'Sheltered ES Homeless People in Families - Non-Hispanic/Non-Latino, 2016',
 'Sheltered ES Homeless People in Families - Hispanic/Latino, 2016',
 'Sheltered ES Homeless People in Families - White, 2016',
 'Sheltered ES Homeless People in Families - Black or African American, 2016',
 'Sheltered ES Homeless People in Families - Asian, 2016',
 'Sheltered ES Homeless People in Families - American Indian or Alaska Native, 2016',
 'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered ES Homeless People in Families - Multiple Races, 2016',
 'Sheltered TH Homeless People in Families, 2016',
 'Sheltered TH Homeless People in Families - Under 18, 2016',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2016',
 'Sheltered TH Homeless People in Families - Over 24, 2016',
 'Sheltered TH Homeless People in Families - Female, 2016',
 'Sheltered TH Homeless People in Families - Male, 2016',
 'Sheltered TH Homeless People in Families - Transgender, 2016',
 'Sheltered TH Homeless People in Families - Non-Hispanic/Non-Latino, 2016',
 'Sheltered TH Homeless People in Families - Hispanic/Latino, 2016',
 'Sheltered TH Homeless People in Families - White, 2016',
 'Sheltered TH Homeless People in Families - Black or African American, 2016',
 'Sheltered TH Homeless People in Families - Asian, 2016',
 'Sheltered TH Homeless People in Families - American Indian or Alaska Native, 2016',
 'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered TH Homeless People in Families - Multiple Races, 2016',
 'Sheltered Total Homeless People in Families, 2016',
 'Sheltered Total Homeless People in Families - Under 18, 2016',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2016',
 'Sheltered Total Homeless People in Families - Over 24, 2016',
 'Sheltered Total Homeless People in Families - Female, 2016',
 'Sheltered Total Homeless People in Families - Male, 2016',
 'Sheltered Total Homeless People in Families - Transgender, 2016',
 'Sheltered Total Homeless People in Families - Non-Hispanic/Non-Latino, 2016',
 'Sheltered Total Homeless People in Families - Hispanic/Latino, 2016',
 'Sheltered Total Homeless People in Families - White, 2016',
 'Sheltered Total Homeless People in Families - Black or African American, 2016',
 'Sheltered Total Homeless People in Families - Asian, 2016',
 'Sheltered Total Homeless People in Families - American Indian or Alaska Native, 2016',
 'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered Total Homeless People in Families - Multiple Races, 2016',
 'Unsheltered Homeless People in Families, 2016',
 'Unsheltered Homeless People in Families - Under 18, 2016',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2016',
 'Unsheltered Homeless People in Families - Over 24, 2016',
 'Unsheltered Homeless People in Families - Female, 2016',
 'Unsheltered Homeless People in Families - Male, 2016',
 'Unsheltered Homeless People in Families - Transgender, 2016',
 'Unsheltered Homeless People in Families - Non-Hispanic/Non-Latino, 2016',
 'Unsheltered Homeless People in Families - Hispanic/Latino, 2016',
 'Unsheltered Homeless People in Families - White, 2016',
 'Unsheltered Homeless People in Families - Black or African American, 2016',
 'Unsheltered Homeless People in Families - Asian, 2016',
 'Unsheltered Homeless People in Families - American Indian or Alaska Native, 2016',
 'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016',
 'Unsheltered Homeless People in Families - Multiple Races, 2016',
 'Overall Homeless Family Households, 2016',
 'Sheltered ES Homeless Family Households, 2016',
 'Sheltered TH Homeless Family Households, 2016',
 'Sheltered Total Homeless Family Households, 2016',
 'Unsheltered Homeless Family Households, 2016',
 'Overall Chronically Homeless, 2016',
 'Sheltered ES Chronically Homeless, 2016',
 'Sheltered SH Chronically Homeless, 2016',
 'Sheltered Total Chronically Homeless, 2016',
 'Unsheltered Chronically Homeless, 2016',
 'Overall Chronically Homeless Individuals, 2016',
 'Sheltered ES Chronically Homeless Individuals, 2016',
 'Sheltered SH Chronically Homeless Individuals, 2016',
 'Sheltered Total Chronically Homeless Individuals, 2016',
 'Unsheltered Chronically Homeless Individuals, 2016',
 'Overall Chronically Homeless People in Families, 2016',
 'Sheltered ES Chronically Homeless People in Families, 2016',
 'Sheltered Total Chronically Homeless People in Families, 2016',
 'Unsheltered Chronically Homeless People in Families, 2016',
 'Overall Homeless Veterans, 2016',
 'Overall Homeless Veterans - Female, 2016',
 'Overall Homeless Veterans - Male, 2016',
 'Overall Homeless Veterans - Transgender, 2016',
 'Overall Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Overall Homeless Veterans - Hispanic/Latino, 2016',
 'Overall Homeless Veterans - White, 2016',
 'Overall Homeless Veterans - Black or African American, 2016',
 'Overall Homeless Veterans - Asian, 2016',
 'Overall Homeless Veterans - American Indian or Alaska Native, 2016',
 'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Overall Homeless Veterans - Multiple Races, 2016',
 'Sheltered ES Homeless Veterans, 2016',
 'Sheltered ES Homeless Veterans - Female, 2016',
 'Sheltered ES Homeless Veterans - Male, 2016',
 'Sheltered ES Homeless Veterans - Transgender, 2016',
 'Sheltered ES Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Sheltered ES Homeless Veterans - Hispanic/Latino, 2016',
 'Sheltered ES Homeless Veterans - White, 2016',
 'Sheltered ES Homeless Veterans - Black or African American, 2016',
 'Sheltered ES Homeless Veterans - Asian, 2016',
 'Sheltered ES Homeless Veterans - American Indian or Alaska Native, 2016',
 'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered ES Homeless Veterans - Multiple Races, 2016',
 'Sheltered TH Homeless Veterans, 2016',
 'Sheltered TH Homeless Veterans - Female, 2016',
 'Sheltered TH Homeless Veterans - Male, 2016',
 'Sheltered TH Homeless Veterans - Transgender, 2016',
 'Sheltered TH Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Sheltered TH Homeless Veterans - Hispanic/Latino, 2016',
 'Sheltered TH Homeless Veterans - White, 2016',
 'Sheltered TH Homeless Veterans - Black or African American, 2016',
 'Sheltered TH Homeless Veterans - Asian, 2016',
 'Sheltered TH Homeless Veterans - American Indian or Alaska Native, 2016',
 'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered TH Homeless Veterans - Multiple Races, 2016',
 'Sheltered SH Homeless Veterans, 2016',
 'Sheltered SH Homeless Veterans - Female, 2016',
 'Sheltered SH Homeless Veterans - Male, 2016',
 'Sheltered SH Homeless Veterans - Transgender, 2016',
 'Sheltered SH Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Sheltered SH Homeless Veterans - Hispanic/Latino, 2016',
 'Sheltered SH Homeless Veterans - White, 2016',
 'Sheltered SH Homeless Veterans - Black or African American, 2016',
 'Sheltered SH Homeless Veterans - Asian, 2016',
 'Sheltered SH Homeless Veterans - American Indian or Alaska Native, 2016',
 'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered SH Homeless Veterans - Multiple Races, 2016',
 'Sheltered Total Homeless Veterans, 2016',
 'Sheltered Total Homeless Veterans - Female, 2016',
 'Sheltered Total Homeless Veterans - Male, 2016',
 'Sheltered Total Homeless Veterans - Transgender, 2016',
 'Sheltered Total Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Sheltered Total Homeless Veterans - Hispanic/Latino, 2016',
 'Sheltered Total Homeless Veterans - White, 2016',
 'Sheltered Total Homeless Veterans - Black or African American, 2016',
 'Sheltered Total Homeless Veterans - Asian, 2016',
 'Sheltered Total Homeless Veterans - American Indian or Alaska Native, 2016',
 'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered Total Homeless Veterans - Multiple Races, 2016',
 'Unsheltered Homeless Veterans, 2016',
 'Unsheltered Homeless Veterans - Female, 2016',
 'Unsheltered Homeless Veterans - Male, 2016',
 'Unsheltered Homeless Veterans - Transgender, 2016',
 'Unsheltered Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Unsheltered Homeless Veterans - Hispanic/Latino, 2016',
 'Unsheltered Homeless Veterans - White, 2016',
 'Unsheltered Homeless Veterans - Black or African American, 2016',
 'Unsheltered Homeless Veterans - Asian, 2016',
 'Unsheltered Homeless Veterans - American Indian or Alaska Native, 2016',
 'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Unsheltered Homeless Veterans - Multiple Races, 2016',
 'Overall Homeless Unaccompanied Youth (Under 25), 2016',

In [124]:
# Rearrange column names so year is second
new_cols_2016 = ['State', 'Year',
 'Number of CoCs',
 'Overall Homeless, 2016',
 'Overall Homeless - Under 18, 2016',
 'Overall Homeless - Age 18 to 24, 2016',
 'Overall Homeless - Over 24, 2016',
 'Overall Homeless - Female, 2016',
 'Overall Homeless - Male, 2016',
 'Overall Homeless - Transgender, 2016',
 'Overall Homeless - Non-Hispanic/Non-Latino, 2016',
 'Overall Homeless - Hispanic/Latino, 2016',
 'Overall Homeless - White, 2016',
 'Overall Homeless - Black or African American, 2016',
 'Overall Homeless - Asian, 2016',
 'Overall Homeless - American Indian or Alaska Native, 2016',
 'Overall Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Overall Homeless - Multiple Races, 2016',
 'Sheltered ES Homeless, 2016',
 'Sheltered ES Homeless - Under 18, 2016',
 'Sheltered ES Homeless - Age 18 to 24, 2016',
 'Sheltered ES Homeless - Over 24, 2016',
 'Sheltered ES Homeless - Female, 2016',
 'Sheltered ES Homeless - Male, 2016',
 'Sheltered ES Homeless - Transgender, 2016',
 'Sheltered ES Homeless - Non-Hispanic/Non-Latino, 2016',
 'Sheltered ES Homeless - Hispanic/Latino, 2016',
 'Sheltered ES Homeless - White, 2016',
 'Sheltered ES Homeless - Black or African American, 2016',
 'Sheltered ES Homeless - Asian, 2016',
 'Sheltered ES Homeless - American Indian or Alaska Native, 2016',
 'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered ES Homeless - Multiple Races, 2016',
 'Sheltered TH Homeless, 2016',
 'Sheltered TH Homeless - Under 18, 2016',
 'Sheltered TH Homeless - Age 18 to 24, 2016',
 'Sheltered TH Homeless - Over 24, 2016',
 'Sheltered TH Homeless - Female, 2016',
 'Sheltered TH Homeless - Male, 2016',
 'Sheltered TH Homeless - Transgender, 2016',
 'Sheltered TH Homeless - Non-Hispanic/Non-Latino, 2016',
 'Sheltered TH Homeless - Hispanic/Latino, 2016',
 'Sheltered TH Homeless - White, 2016',
 'Sheltered TH Homeless - Black or African American, 2016',
 'Sheltered TH Homeless - Asian, 2016',
 'Sheltered TH Homeless - American Indian or Alaska Native, 2016',
 'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered TH Homeless - Multiple Races, 2016',
 'Sheltered SH Homeless, 2016',
 'Sheltered SH Homeless - Age 18 to 24, 2016',
 'Sheltered SH Homeless - Over 24, 2016',
 'Sheltered SH Homeless - Female, 2016',
 'Sheltered SH Homeless - Male, 2016',
 'Sheltered SH Homeless - Transgender, 2016',
 'Sheltered SH Homeless - Non-Hispanic/Non-Latino, 2016',
 'Sheltered SH Homeless - Hispanic/Latino, 2016',
 'Sheltered SH Homeless - White, 2016',
 'Sheltered SH Homeless - Black or African American, 2016',
 'Sheltered SH Homeless - Asian, 2016',
 'Sheltered SH Homeless - American Indian or Alaska Native, 2016',
 'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered SH Homeless - Multiple Races, 2016',
 'Sheltered Total Homeless, 2016',
 'Sheltered Total Homeless - Under 18, 2016',
 'Sheltered Total Homeless - Age 18 to 24, 2016',
 'Sheltered Total Homeless - Over 24, 2016',
 'Sheltered Total Homeless - Female, 2016',
 'Sheltered Total Homeless - Male, 2016',
 'Sheltered Total Homeless - Transgender, 2016',
 'Sheltered Total Homeless - Non-Hispanic/Non-Latino, 2016',
 'Sheltered Total Homeless - Hispanic/Latino, 2016',
 'Sheltered Total Homeless - White, 2016',
 'Sheltered Total Homeless - Black or African American, 2016',
 'Sheltered Total Homeless - Asian, 2016',
 'Sheltered Total Homeless - American Indian or Alaska Native, 2016',
 'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered Total Homeless - Multiple Races, 2016',
 'Unsheltered Homeless, 2016',
 'Unsheltered Homeless - Under 18, 2016',
 'Unsheltered Homeless - Age 18 to 24, 2016',
 'Unsheltered Homeless - Over 24, 2016',
 'Unsheltered Homeless - Female, 2016',
 'Unsheltered Homeless - Male, 2016',
 'Unsheltered Homeless - Transgender, 2016',
 'Unsheltered Homeless - Non-Hispanic/Non-Latino, 2016',
 'Unsheltered Homeless - Hispanic/Latino, 2016',
 'Unsheltered Homeless - White, 2016',
 'Unsheltered Homeless - Black or African American, 2016',
 'Unsheltered Homeless - Asian, 2016',
 'Unsheltered Homeless - American Indian or Alaska Native, 2016',
 'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander, 2016',
 'Unsheltered Homeless - Multiple Races, 2016',
 'Overall Homeless Individuals, 2016',
 'Overall Homeless Individuals - Under 18, 2016',
 'Overall Homeless Individuals - Age 18 to 24, 2016',
 'Overall Homeless Individuals - Over 24, 2016',
 'Overall Homeless Individuals - Female, 2016',
 'Overall Homeless Individuals - Male, 2016',
 'Overall Homeless Individuals - Transgender, 2016',
 'Overall Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Overall Homeless Individuals - Hispanic/Latino, 2016',
 'Overall Homeless Individuals - White, 2016',
 'Overall Homeless Individuals - Black or African American, 2016',
 'Overall Homeless Individuals - Asian, 2016',
 'Overall Homeless Individuals - American Indian or Alaska Native, 2016',
 'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Overall Homeless Individuals - Multiple Races, 2016',
 'Sheltered ES Homeless Individuals, 2016',
 'Sheltered ES Homeless Individuals - Under 18, 2016',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2016',
 'Sheltered ES Homeless Individuals - Over 24, 2016',
 'Sheltered ES Homeless Individuals - Female, 2016',
 'Sheltered ES Homeless Individuals - Male, 2016',
 'Sheltered ES Homeless Individuals - Transgender, 2016',
 'Sheltered ES Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Sheltered ES Homeless Individuals - Hispanic/Latino, 2016',
 'Sheltered ES Homeless Individuals - White, 2016',
 'Sheltered ES Homeless Individuals - Black or African American, 2016',
 'Sheltered ES Homeless Individuals - Asian, 2016',
 'Sheltered ES Homeless Individuals - American Indian or Alaska Native, 2016',
 'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered ES Homeless Individuals - Multiple Races, 2016',
 'Sheltered TH Homeless Individuals, 2016',
 'Sheltered TH Homeless Individuals - Under 18, 2016',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2016',
 'Sheltered TH Homeless Individuals - Over 24, 2016',
 'Sheltered TH Homeless Individuals - Female, 2016',
 'Sheltered TH Homeless Individuals - Male, 2016',
 'Sheltered TH Homeless Individuals - Transgender, 2016',
 'Sheltered TH Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Sheltered TH Homeless Individuals - Hispanic/Latino, 2016',
 'Sheltered TH Homeless Individuals - White, 2016',
 'Sheltered TH Homeless Individuals - Black or African American, 2016',
 'Sheltered TH Homeless Individuals - Asian, 2016',
 'Sheltered TH Homeless Individuals - American Indian or Alaska Native, 2016',
 'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered TH Homeless Individuals - Multiple Races, 2016',
 'Sheltered SH Homeless Individuals, 2016',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2016',
 'Sheltered SH Homeless Individuals - Over 24, 2016',
 'Sheltered SH Homeless Individuals - Female, 2016',
 'Sheltered SH Homeless Individuals - Male, 2016',
 'Sheltered SH Homeless Individuals - Transgender, 2016',
 'Sheltered SH Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Sheltered SH Homeless Individuals - Hispanic/Latino, 2016',
 'Sheltered SH Homeless Individuals - White, 2016',
 'Sheltered SH Homeless Individuals - Black or African American, 2016',
 'Sheltered SH Homeless Individuals - Asian, 2016',
 'Sheltered SH Homeless Individuals - American Indian or Alaska Native, 2016',
 'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered SH Homeless Individuals - Multiple Races, 2016',
 'Sheltered Total Homeless Individuals, 2016',
 'Sheltered Total Homeless Individuals - Under 18, 2016',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2016',
 'Sheltered Total Homeless Individuals - Over 24, 2016',
 'Sheltered Total Homeless Individuals - Female, 2016',
 'Sheltered Total Homeless Individuals - Male, 2016',
 'Sheltered Total Homeless Individuals - Transgender, 2016',
 'Sheltered Total Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Sheltered Total Homeless Individuals - Hispanic/Latino, 2016',
 'Sheltered Total Homeless Individuals - White, 2016',
 'Sheltered Total Homeless Individuals - Black or African American, 2016',
 'Sheltered Total Homeless Individuals - Asian, 2016',
 'Sheltered Total Homeless Individuals - American Indian or Alaska Native, 2016',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered Total Homeless Individuals - Multiple Races, 2016',
 'Unsheltered Homeless Individuals, 2016',
 'Unsheltered Homeless Individuals - Under 18, 2016',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2016',
 'Unsheltered Homeless Individuals - Over 24, 2016',
 'Unsheltered Homeless Individuals - Female, 2016',
 'Unsheltered Homeless Individuals - Male, 2016',
 'Unsheltered Homeless Individuals - Transgender, 2016',
 'Unsheltered Homeless Individuals - Non-Hispanic/Non-Latino, 2016',
 'Unsheltered Homeless Individuals - Hispanic/Latino, 2016',
 'Unsheltered Homeless Individuals - White, 2016',
 'Unsheltered Homeless Individuals - Black or African American, 2016',
 'Unsheltered Homeless Individuals - Asian, 2016',
 'Unsheltered Homeless Individuals - American Indian or Alaska Native, 2016',
 'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016',
 'Unsheltered Homeless Individuals - Multiple Races, 2016',
 'Overall Homeless People in Families, 2016',
 'Overall Homeless People in Families - Under 18, 2016',
 'Overall Homeless People in Families - Age 18 to 24, 2016',
 'Overall Homeless People in Families - Over 24, 2016',
 'Overall Homeless People in Families - Female, 2016',
 'Overall Homeless People in Families - Male, 2016',
 'Overall Homeless People in Families - Transgender, 2016',
 'Overall Homeless People in Families - Non-Hispanic/Non-Latino, 2016',
 'Overall Homeless People in Families - Hispanic/Latino, 2016',
 'Overall Homeless People in Families - White, 2016',
 'Overall Homeless People in Families - Black or African American, 2016',
 'Overall Homeless People in Families - Asian, 2016',
 'Overall Homeless People in Families - American Indian or Alaska Native, 2016',
 'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016',
 'Overall Homeless People in Families - Multiple Races, 2016',
 'Sheltered ES Homeless People in Families, 2016',
 'Sheltered ES Homeless People in Families - Under 18, 2016',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2016',
 'Sheltered ES Homeless People in Families - Over 24, 2016',
 'Sheltered ES Homeless People in Families - Female, 2016',
 'Sheltered ES Homeless People in Families - Male, 2016',
 'Sheltered ES Homeless People in Families - Transgender, 2016',
 'Sheltered ES Homeless People in Families - Non-Hispanic/Non-Latino, 2016',
 'Sheltered ES Homeless People in Families - Hispanic/Latino, 2016',
 'Sheltered ES Homeless People in Families - White, 2016',
 'Sheltered ES Homeless People in Families - Black or African American, 2016',
 'Sheltered ES Homeless People in Families - Asian, 2016',
 'Sheltered ES Homeless People in Families - American Indian or Alaska Native, 2016',
 'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered ES Homeless People in Families - Multiple Races, 2016',
 'Sheltered TH Homeless People in Families, 2016',
 'Sheltered TH Homeless People in Families - Under 18, 2016',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2016',
 'Sheltered TH Homeless People in Families - Over 24, 2016',
 'Sheltered TH Homeless People in Families - Female, 2016',
 'Sheltered TH Homeless People in Families - Male, 2016',
 'Sheltered TH Homeless People in Families - Transgender, 2016',
 'Sheltered TH Homeless People in Families - Non-Hispanic/Non-Latino, 2016',
 'Sheltered TH Homeless People in Families - Hispanic/Latino, 2016',
 'Sheltered TH Homeless People in Families - White, 2016',
 'Sheltered TH Homeless People in Families - Black or African American, 2016',
 'Sheltered TH Homeless People in Families - Asian, 2016',
 'Sheltered TH Homeless People in Families - American Indian or Alaska Native, 2016',
 'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered TH Homeless People in Families - Multiple Races, 2016',
 'Sheltered Total Homeless People in Families, 2016',
 'Sheltered Total Homeless People in Families - Under 18, 2016',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2016',
 'Sheltered Total Homeless People in Families - Over 24, 2016',
 'Sheltered Total Homeless People in Families - Female, 2016',
 'Sheltered Total Homeless People in Families - Male, 2016',
 'Sheltered Total Homeless People in Families - Transgender, 2016',
 'Sheltered Total Homeless People in Families - Non-Hispanic/Non-Latino, 2016',
 'Sheltered Total Homeless People in Families - Hispanic/Latino, 2016',
 'Sheltered Total Homeless People in Families - White, 2016',
 'Sheltered Total Homeless People in Families - Black or African American, 2016',
 'Sheltered Total Homeless People in Families - Asian, 2016',
 'Sheltered Total Homeless People in Families - American Indian or Alaska Native, 2016',
 'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered Total Homeless People in Families - Multiple Races, 2016',
 'Unsheltered Homeless People in Families, 2016',
 'Unsheltered Homeless People in Families - Under 18, 2016',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2016',
 'Unsheltered Homeless People in Families - Over 24, 2016',
 'Unsheltered Homeless People in Families - Female, 2016',
 'Unsheltered Homeless People in Families - Male, 2016',
 'Unsheltered Homeless People in Families - Transgender, 2016',
 'Unsheltered Homeless People in Families - Non-Hispanic/Non-Latino, 2016',
 'Unsheltered Homeless People in Families - Hispanic/Latino, 2016',
 'Unsheltered Homeless People in Families - White, 2016',
 'Unsheltered Homeless People in Families - Black or African American, 2016',
 'Unsheltered Homeless People in Families - Asian, 2016',
 'Unsheltered Homeless People in Families - American Indian or Alaska Native, 2016',
 'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016',
 'Unsheltered Homeless People in Families - Multiple Races, 2016',
 'Overall Homeless Family Households, 2016',
 'Sheltered ES Homeless Family Households, 2016',
 'Sheltered TH Homeless Family Households, 2016',
 'Sheltered Total Homeless Family Households, 2016',
 'Unsheltered Homeless Family Households, 2016',
 'Overall Chronically Homeless, 2016',
 'Sheltered ES Chronically Homeless, 2016',
 'Sheltered SH Chronically Homeless, 2016',
 'Sheltered Total Chronically Homeless, 2016',
 'Unsheltered Chronically Homeless, 2016',
 'Overall Chronically Homeless Individuals, 2016',
 'Sheltered ES Chronically Homeless Individuals, 2016',
 'Sheltered SH Chronically Homeless Individuals, 2016',
 'Sheltered Total Chronically Homeless Individuals, 2016',
 'Unsheltered Chronically Homeless Individuals, 2016',
 'Overall Chronically Homeless People in Families, 2016',
 'Sheltered ES Chronically Homeless People in Families, 2016',
 'Sheltered Total Chronically Homeless People in Families, 2016',
 'Unsheltered Chronically Homeless People in Families, 2016',
 'Overall Homeless Veterans, 2016',
 'Overall Homeless Veterans - Female, 2016',
 'Overall Homeless Veterans - Male, 2016',
 'Overall Homeless Veterans - Transgender, 2016',
 'Overall Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Overall Homeless Veterans - Hispanic/Latino, 2016',
 'Overall Homeless Veterans - White, 2016',
 'Overall Homeless Veterans - Black or African American, 2016',
 'Overall Homeless Veterans - Asian, 2016',
 'Overall Homeless Veterans - American Indian or Alaska Native, 2016',
 'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Overall Homeless Veterans - Multiple Races, 2016',
 'Sheltered ES Homeless Veterans, 2016',
 'Sheltered ES Homeless Veterans - Female, 2016',
 'Sheltered ES Homeless Veterans - Male, 2016',
 'Sheltered ES Homeless Veterans - Transgender, 2016',
 'Sheltered ES Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Sheltered ES Homeless Veterans - Hispanic/Latino, 2016',
 'Sheltered ES Homeless Veterans - White, 2016',
 'Sheltered ES Homeless Veterans - Black or African American, 2016',
 'Sheltered ES Homeless Veterans - Asian, 2016',
 'Sheltered ES Homeless Veterans - American Indian or Alaska Native, 2016',
 'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered ES Homeless Veterans - Multiple Races, 2016',
 'Sheltered TH Homeless Veterans, 2016',
 'Sheltered TH Homeless Veterans - Female, 2016',
 'Sheltered TH Homeless Veterans - Male, 2016',
 'Sheltered TH Homeless Veterans - Transgender, 2016',
 'Sheltered TH Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Sheltered TH Homeless Veterans - Hispanic/Latino, 2016',
 'Sheltered TH Homeless Veterans - White, 2016',
 'Sheltered TH Homeless Veterans - Black or African American, 2016',
 'Sheltered TH Homeless Veterans - Asian, 2016',
 'Sheltered TH Homeless Veterans - American Indian or Alaska Native, 2016',
 'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered TH Homeless Veterans - Multiple Races, 2016',
 'Sheltered SH Homeless Veterans, 2016',
 'Sheltered SH Homeless Veterans - Female, 2016',
 'Sheltered SH Homeless Veterans - Male, 2016',
 'Sheltered SH Homeless Veterans - Transgender, 2016',
 'Sheltered SH Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Sheltered SH Homeless Veterans - Hispanic/Latino, 2016',
 'Sheltered SH Homeless Veterans - White, 2016',
 'Sheltered SH Homeless Veterans - Black or African American, 2016',
 'Sheltered SH Homeless Veterans - Asian, 2016',
 'Sheltered SH Homeless Veterans - American Indian or Alaska Native, 2016',
 'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered SH Homeless Veterans - Multiple Races, 2016',
 'Sheltered Total Homeless Veterans, 2016',
 'Sheltered Total Homeless Veterans - Female, 2016',
 'Sheltered Total Homeless Veterans - Male, 2016',
 'Sheltered Total Homeless Veterans - Transgender, 2016',
 'Sheltered Total Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Sheltered Total Homeless Veterans - Hispanic/Latino, 2016',
 'Sheltered Total Homeless Veterans - White, 2016',
 'Sheltered Total Homeless Veterans - Black or African American, 2016',
 'Sheltered Total Homeless Veterans - Asian, 2016',
 'Sheltered Total Homeless Veterans - American Indian or Alaska Native, 2016',
 'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Sheltered Total Homeless Veterans - Multiple Races, 2016',
 'Unsheltered Homeless Veterans, 2016',
 'Unsheltered Homeless Veterans - Female, 2016',
 'Unsheltered Homeless Veterans - Male, 2016',
 'Unsheltered Homeless Veterans - Transgender, 2016',
 'Unsheltered Homeless Veterans - Non-Hispanic/Non-Latino, 2016',
 'Unsheltered Homeless Veterans - Hispanic/Latino, 2016',
 'Unsheltered Homeless Veterans - White, 2016',
 'Unsheltered Homeless Veterans - Black or African American, 2016',
 'Unsheltered Homeless Veterans - Asian, 2016',
 'Unsheltered Homeless Veterans - American Indian or Alaska Native, 2016',
 'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016',
 'Unsheltered Homeless Veterans - Multiple Races, 2016',
 'Overall Homeless Unaccompanied Youth (Under 25), 2016',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25), 2016',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25), 2016',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25), 2016',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25), 2016',
 'Unsheltered Homeless Unaccompanied Youth (Under 25), 2016',
 'Overall Homeless Unaccompanied Youth Under 18, 2016',
 'Sheltered ES Homeless Unaccompanied Youth Under 18, 2016',
 'Sheltered TH Homeless Unaccompanied Youth Under 18, 2016',
 'Sheltered Total Homeless Unaccompanied Youth Under 18, 2016',
 'Unsheltered Homeless Unaccompanied Youth Under 18, 2016',
 'Overall Homeless Unaccompanied Youth Age 18-24, 2016',
 'Sheltered ES Homeless Unaccompanied Youth Age 18-24, 2016',
 'Sheltered TH Homeless Unaccompanied Youth Age 18-24, 2016',
 'Sheltered SH Homeless Unaccompanied Youth Age 18-24, 2016',
 'Sheltered Total Homeless Unaccompanied Youth Age 18-24, 2016',
 'Unsheltered Homeless Unaccompanied Youth Age 18-24, 2016',
 'Overall Homeless Parenting Youth (Under 25), 2016',
 'Sheltered ES Homeless Parenting Youth (Under 25), 2016',
 'Sheltered TH Homeless Parenting Youth (Under 25), 2016',
 'Sheltered Total Homeless Parenting Youth (Under 25), 2016',
 'Unsheltered Homeless Parenting Youth (Under 25), 2016',
 'Overall Homeless Parenting Youth Under 18, 2016',
 'Sheltered ES Homeless Parenting Youth Under 18, 2016',
 'Sheltered TH Homeless Parenting Youth Under 18, 2016',
 'Sheltered Total Homeless Parenting Youth Under 18, 2016',
 'Unsheltered Homeless Parenting Youth Under 18, 2016',
 'Overall Homeless Parenting Youth Age 18-24, 2016',
 'Sheltered ES Homeless Parenting Youth Age 18-24, 2016',
 'Sheltered TH Homeless Parenting Youth Age 18-24, 2016',
 'Sheltered Total Homeless Parenting Youth Age 18-24, 2016',
 'Unsheltered Homeless Parenting Youth Age 18-24, 2016',
 'Overall Homeless Children of Parenting Youth, 2016',
 'Sheltered ES Homeless Children of Parenting Youth, 2016',
 'Sheltered TH Homeless Children of Parenting Youth, 2016',
 'Sheltered Total Homeless Children of Parenting Youth, 2016',
 'Unsheltered Homeless Children of Parenting Youth, 2016'
 ]

In [125]:
# Apply rearranged column names
data_2016_df = data_2016_df[new_cols_2016]
data_2016_df.head()

,State,Year,Number of CoCs,"Overall Homeless, 2016","Overall Homeless - Under 18, 2016","Overall Homeless - Age 18 to 24, 2016","Overall Homeless - Over 24, 2016","Overall Homeless - Female, 2016","Overall Homeless - Male, 2016","Overall Homeless - Transgender, 2016",...,"Overall Homeless Parenting Youth Age 18-24, 2016","Sheltered ES Homeless Parenting Youth Age 18-24, 2016","Sheltered TH Homeless Parenting Youth Age 18-24, 2016","Sheltered Total Homeless Parenting Youth Age 18-24, 2016","Unsheltered Homeless Parenting Youth Age 18-24, 2016","Overall Homeless Children of Parenting Youth, 2016","Sheltered ES Homeless Children of Parenting Youth, 2016","Sheltered TH Homeless Children of Parenting Youth, 2016","Sheltered Total Homeless Children of Parenting Youth, 2016","Unsheltered Homeless Children of Parenting Youth, 2016"
0,AK,2016,2.0,"1,940",274,173,"1,493",808,"1,127",5,...,9,2,7,9,0,10,2,8,10,0
1,AL,2016,8.0,"4,111",681,304,"3,126","1,733","2,366",12,...,26,14,6,20,6,45,22,17,39,6
2,AR,2016,7.0,"2,463",432,197,"1,834","1,047","1,415",1,...,13,12,1,13,0,13,12,1,13,0
3,AS,2016,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2016,3.0,"9,707","2,022",733,"6,952","3,685","6,005",17,...,149,69,80,149,0,222,96,126,222,0

In [126]:
# rename columns to remove year from each column title
dict = {
 'Overall Homeless, 2016':'Overall Homeless',
 'Overall Homeless - Under 18, 2016':'Overall Homeless - Under 18',
 'Overall Homeless - Age 18 to 24, 2016':'Overall Homeless - Age 18 to 24',
 'Overall Homeless - Over 24, 2016':'Overall Homeless - Over 24',
 'Overall Homeless - Female, 2016':'Overall Homeless - Female',
 'Overall Homeless - Male, 2016':'Overall Homeless - Male',
 'Overall Homeless - Transgender, 2016':'Overall Homeless - Transgender',
 'Overall Homeless - Non-Hispanic/Non-Latino, 2016':'Overall Homeless - Non-Hispanic/Non-Latino',
 'Overall Homeless - Hispanic/Latino, 2016':'Overall Homeless - Hispanic/Latino',
 'Overall Homeless - White, 2016':'Overall Homeless - White',
 'Overall Homeless - Black or African American, 2016':'Overall Homeless - Black or African American',
 'Overall Homeless - Asian, 2016':'Overall Homeless - Asian',
 'Overall Homeless - American Indian or Alaska Native, 2016':'Overall Homeless - American Indian or Alaska Native',
 'Overall Homeless - Native Hawaiian or Other Pacific Islander, 2016':'Overall Homeless - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless - Multiple Races, 2016':'Overall Homeless - Multiple Races',
 
 'Sheltered ES Homeless, 2016':'Sheltered ES Homeless', 
 'Sheltered ES Homeless - Under 18, 2016':'Sheltered ES Homeless - Under 18',
 'Sheltered ES Homeless - Age 18 to 24, 2016':'Sheltered ES Homeless - Age 18 to 24',
 'Sheltered ES Homeless - Over 24, 2016':'Sheltered ES Homeless - Over 24',
 'Sheltered ES Homeless - Female, 2016':'Sheltered ES Homeless - Female',
 'Sheltered ES Homeless - Male, 2016':'Sheltered ES Homeless - Male',
 'Sheltered ES Homeless - Transgender, 2016':'Sheltered ES Homeless - Transgender',
 'Sheltered ES Homeless - Non-Hispanic/Non-Latino, 2016':'Sheltered ES Homeless - Non-Hispanic/Non-Latino',
 'Sheltered ES Homeless - Hispanic/Latino, 2016':'Sheltered ES Homeless - Hispanic/Latino',
 'Sheltered ES Homeless - White, 2016':'Sheltered ES Homeless - White',
 'Sheltered ES Homeless - Black or African American, 2016':'Sheltered ES Homeless - Black or African American',
 'Sheltered ES Homeless - Asian, 2016':'Sheltered ES Homeless - Asian',
 'Sheltered ES Homeless - American Indian or Alaska Native, 2016':'Sheltered ES Homeless - American Indian or Alaska Native',
 'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless - Multiple Races, 2016':'Sheltered ES Homeless - Multiple Races',
    
 'Sheltered TH Homeless, 2016':'Sheltered TH Homeless', 
 'Sheltered TH Homeless - Under 18, 2016':'Sheltered TH Homeless - Under 18',
 'Sheltered TH Homeless - Age 18 to 24, 2016':'Sheltered TH Homeless - Age 18 to 24',
 'Sheltered TH Homeless - Over 24, 2016':'Sheltered TH Homeless - Over 24',
 'Sheltered TH Homeless - Female, 2016':'Sheltered TH Homeless - Female',
 'Sheltered TH Homeless - Male, 2016':'Sheltered TH Homeless - Male',
 'Sheltered TH Homeless - Transgender, 2016':'Sheltered TH Homeless - Transgender',
 'Sheltered TH Homeless - Non-Hispanic/Non-Latino, 2016':'Sheltered TH Homeless - Non-Hispanic/Non-Latino',
 'Sheltered TH Homeless - Hispanic/Latino, 2016':'Sheltered TH Homeless - Hispanic/Latino',
 'Sheltered TH Homeless - White, 2016':'Sheltered TH Homeless - White',
 'Sheltered TH Homeless - Black or African American, 2016':'Sheltered TH Homeless - Black or African American',
 'Sheltered TH Homeless - Asian, 2016':'Sheltered TH Homeless - Asian',
 'Sheltered TH Homeless - American Indian or Alaska Native, 2016':'Sheltered TH Homeless - American Indian or Alaska Native',
 'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless - Multiple Races, 2016':'Sheltered TH Homeless - Multiple Races',
    
 'Sheltered SH Homeless, 2016':'Sheltered SH Homeless', 
 'Sheltered SH Homeless - Under 18, 2016':'Sheltered SH Homeless - Under 18',
 'Sheltered SH Homeless - Age 18 to 24, 2016':'Sheltered SH Homeless - Age 18 to 24',
 'Sheltered SH Homeless - Over 24, 2016':'Sheltered SH Homeless - Over 24',
 'Sheltered SH Homeless - Female, 2016':'Sheltered SH Homeless - Female',
 'Sheltered SH Homeless - Male, 2016':'Sheltered SH Homeless - Male',
 'Sheltered SH Homeless - Transgender, 2016':'Sheltered SH Homeless - Transgender',
 'Sheltered SH Homeless - Non-Hispanic/Non-Latino, 2016':'Sheltered SH Homeless - Non-Hispanic/Non-Latino',
 'Sheltered SH Homeless - Hispanic/Latino, 2016':'Sheltered SH Homeless - Hispanic/Latino',
 'Sheltered SH Homeless - White, 2016':'Sheltered SH Homeless - White',
 'Sheltered SH Homeless - Black or African American, 2016':'Sheltered SH Homeless - Black or African American',
 'Sheltered SH Homeless - Asian, 2016':'Sheltered SH Homeless - Asian',
 'Sheltered SH Homeless - American Indian or Alaska Native, 2016':'Sheltered SH Homeless - American Indian or Alaska Native',
 'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered SH Homeless - Multiple Races, 2016':'Sheltered SH Homeless - Multiple Races',
    
 'Sheltered Total Homeless, 2016':'Sheltered Total Homeless',
 'Sheltered Total Homeless - Under 18, 2016':'Sheltered Total Homeless - Under 18',
 'Sheltered Total Homeless - Age 18 to 24, 2016':'Sheltered Total Homeless - Age 18 to 24',
 'Sheltered Total Homeless - Over 24, 2016':'Sheltered Total Homeless - Over 24',
 'Sheltered Total Homeless - Female, 2016':'Sheltered Total Homeless - Female',
 'Sheltered Total Homeless - Male, 2016':'Sheltered Total Homeless - Male',
 'Sheltered Total Homeless - Transgender, 2016':'Sheltered Total Homeless - Transgender',
 'Sheltered Total Homeless - Non-Hispanic/Non-Latino, 2016':'Sheltered Total Homeless - Non-Hispanic/Non-Latino',
 'Sheltered Total Homeless - Hispanic/Latino, 2016':'Sheltered Total Homeless - Hispanic/Latino',
 'Sheltered Total Homeless - White, 2016':'Sheltered Total Homeless - White',
 'Sheltered Total Homeless - Black or African American, 2016':'Sheltered Total Homeless - Black or African American',
 'Sheltered Total Homeless - Asian, 2016':'Sheltered Total Homeless - Asian',
 'Sheltered Total Homeless - American Indian or Alaska Native, 2016':'Sheltered Total Homeless - American Indian or Alaska Native',
 'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless - Multiple Races, 2016':'Sheltered Total Homeless - Multiple Races',
    
 'Unsheltered Homeless, 2016':'Unsheltered Homeless',
 'Unsheltered Homeless - Under 18, 2016':'Unsheltered Homeless - Under 18',
 'Unsheltered Homeless - Age 18 to 24, 2016':'Unsheltered Homeless - Age 18 to 24',
 'Unsheltered Homeless - Over 24, 2016':'Unsheltered Homeless - Over 24',
 'Unsheltered Homeless - Female, 2016':'Unsheltered Homeless - Female',
 'Unsheltered Homeless - Male, 2016':'Unsheltered Homeless - Male',
 'Unsheltered Homeless - Transgender, 2016':'Unsheltered Homeless - Transgender',
 'Unsheltered Homeless - Non-Hispanic/Non-Latino, 2016':'Unsheltered Homeless - Non-Hispanic/Non-Latino',
 'Unsheltered Homeless - Hispanic/Latino, 2016':'Unsheltered Homeless - Hispanic/Latino',
 'Unsheltered Homeless - White, 2016':'Unsheltered Homeless - White',
 'Unsheltered Homeless - Black or African American, 2016':'Unsheltered Homeless - Black or African American',
 'Unsheltered Homeless - Asian, 2016':'Unsheltered Homeless - Asian',
 'Unsheltered Homeless - American Indian or Alaska Native, 2016':'Unsheltered Homeless - American Indian or Alaska Native',
 'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander, 2016':'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless - Multiple Races, 2016':'Unsheltered Homeless - Multiple Races',
    
 'Overall Homeless Individuals, 2016':'Overall Homeless Individuals',
 'Overall Homeless Individuals - Under 18, 2016':'Overall Homeless Individuals - Under 18',
 'Overall Homeless Individuals - Age 18 to 24, 2016':'Overall Homeless Individuals - Age 18 to 24',
 'Overall Homeless Individuals - Over 24, 2016':'Overall Homeless Individuals - Over 24',
 'Overall Homeless Individuals - Female, 2016':'Overall Homeless Individuals - Female',
 'Overall Homeless Individuals - Male, 2016':'Overall Homeless Individuals - Male',
 'Overall Homeless Individuals - Transgender, 2016':'Overall Homeless Individuals - Transgender',
 'Overall Homeless Individuals - Non-Hispanic/Non-Latino, 2016':'Overall Homeless Individuals - Non-Hispanic/Non-Latino',
 'Overall Homeless Individuals - Hispanic/Latino, 2016':'Overall Homeless Individuals - Hispanic/Latino',
 'Overall Homeless Individuals - White, 2016':'Overall Homeless Individuals - White',
 'Overall Homeless Individuals - Black or African American, 2016':'Overall Homeless Individuals - Black or African American',
 'Overall Homeless Individuals - Asian, 2016':'Overall Homeless Individuals - Asian',
 'Overall Homeless Individuals - American Indian or Alaska Native, 2016':'Overall Homeless Individuals - American Indian or Alaska Native',
 'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016':'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless Individuals - Multiple Races, 2016':'Overall Homeless Individuals - Multiple Races',
    
 'Sheltered ES Homeless Individuals, 2016':'Sheltered ES Homeless Individuals',
 'Sheltered ES Homeless Individuals - Under 18, 2016':'Sheltered ES Homeless Individuals - Under 18',
 'Sheltered ES Homeless Individuals - Age 18 to 24, 2016':'Sheltered ES Homeless Individuals - Age 18 to 24',
 'Sheltered ES Homeless Individuals - Over 24, 2016':'Sheltered ES Homeless Individuals - Over 24',
 'Sheltered ES Homeless Individuals - Female, 2016':'Sheltered ES Homeless Individuals - Female',
 'Sheltered ES Homeless Individuals - Male, 2016':'Sheltered ES Homeless Individuals - Male',
 'Sheltered ES Homeless Individuals - Transgender, 2016':'Sheltered ES Homeless Individuals - Transgender',
 'Sheltered ES Homeless Individuals - Non-Hispanic/Non-Latino, 2016':'Sheltered ES Homeless Individuals - Non-Hispanic/Non-Latino',
 'Sheltered ES Homeless Individuals - Hispanic/Latino, 2016':'Sheltered ES Homeless Individuals - Hispanic/Latino',
 'Sheltered ES Homeless Individuals - White, 2016':'Sheltered ES Homeless Individuals - White',
 'Sheltered ES Homeless Individuals - Black or African American, 2016':'Sheltered ES Homeless Individuals - Black or African American',
 'Sheltered ES Homeless Individuals - Asian, 2016':'Sheltered ES Homeless Individuals - Asian',
 'Sheltered ES Homeless Individuals - American Indian or Alaska Native, 2016':'Sheltered ES Homeless Individuals - American Indian or Alaska Native',
 'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless Individuals - Multiple Races, 2016':'Sheltered ES Homeless Individuals - Multiple Races',

    
 'Sheltered TH Homeless Individuals, 2016':'Sheltered TH Homeless Individuals',
 'Sheltered TH Homeless Individuals - Under 18, 2016':'Sheltered TH Homeless Individuals - Under 18',
 'Sheltered TH Homeless Individuals - Age 18 to 24, 2016':'Sheltered TH Homeless Individuals - Age 18 to 24',
 'Sheltered TH Homeless Individuals - Over 24, 2016':'Sheltered TH Homeless Individuals - Over 24',
 'Sheltered TH Homeless Individuals - Female, 2016':'Sheltered TH Homeless Individuals - Female',
 'Sheltered TH Homeless Individuals - Male, 2016':'Sheltered TH Homeless Individuals - Male',
 'Sheltered TH Homeless Individuals - Transgender, 2016':'Sheltered TH Homeless Individuals - Transgender',
 'Sheltered TH Homeless Individuals - Non-Hispanic/Non-Latino, 2016':'Sheltered TH Homeless Individuals - Non-Hispanic/Non-Latino',
 'Sheltered TH Homeless Individuals - Hispanic/Latino, 2016':'Sheltered TH Homeless Individuals - Hispanic/Latino',
 'Sheltered TH Homeless Individuals - White, 2016':'Sheltered TH Homeless Individuals - White',
 'Sheltered TH Homeless Individuals - Black or African American, 2016':'Sheltered TH Homeless Individuals - Black or African American',
 'Sheltered TH Homeless Individuals - Asian, 2016':'Sheltered TH Homeless Individuals - Asian',
 'Sheltered TH Homeless Individuals - American Indian or Alaska Native, 2016':'Sheltered TH Homeless Individuals - American Indian or Alaska Native',
 'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless Individuals - Multiple Races, 2016':'Sheltered TH Homeless Individuals - Multiple Races',
    
 'Sheltered SH Homeless Individuals, 2016':'Sheltered SH Homeless Individuals',
 'Sheltered SH Homeless Individuals - Age 18 to 24, 2016':'Sheltered SH Homeless Individuals - Age 18 to 24',
 'Sheltered SH Homeless Individuals - Over 24, 2016':'Sheltered SH Homeless Individuals - Over 24',
 'Sheltered SH Homeless Individuals - Female, 2016':'Sheltered SH Homeless Individuals - Female',
 'Sheltered SH Homeless Individuals - Male, 2016':'Sheltered SH Homeless Individuals - Male',
 'Sheltered SH Homeless Individuals - Transgender, 2016':'Sheltered SH Homeless Individuals - Transgender',
 'Sheltered SH Homeless Individuals - Non-Hispanic/Non-Latino, 2016':'Sheltered SH Homeless Individuals - Non-Hispanic/Non-Latino',
 'Sheltered SH Homeless Individuals - Hispanic/Latino, 2016':'Sheltered SH Homeless Individuals - Hispanic/Latino',
 'Sheltered SH Homeless Individuals - White, 2016':'Sheltered SH Homeless Individuals - White',
 'Sheltered SH Homeless Individuals - Black or African American, 2016':'Sheltered SH Homeless Individuals - Black or African American',
 'Sheltered SH Homeless Individuals - Asian, 2016':'Sheltered SH Homeless Individuals - Asian',
 'Sheltered SH Homeless Individuals - American Indian or Alaska Native, 2016':'Sheltered SH Homeless Individuals - American Indian or Alaska Native',
 'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered SH Homeless Individuals - Multiple Races, 2016':'Sheltered SH Homeless Individuals - Multiple Races',
    
 'Sheltered Total Homeless Individuals, 2016':'Sheltered Total Homeless Individuals',
 'Sheltered Total Homeless Individuals - Under 18, 2016':'Sheltered Total Homeless Individuals - Under 18',
 'Sheltered Total Homeless Individuals - Age 18 to 24, 2016':'Sheltered Total Homeless Individuals - Age 18 to 24',
 'Sheltered Total Homeless Individuals - Over 24, 2016':'Sheltered Total Homeless Individuals - Over 24',
 'Sheltered Total Homeless Individuals - Female, 2016':'Sheltered Total Homeless Individuals - Female',
 'Sheltered Total Homeless Individuals - Male, 2016':'Sheltered Total Homeless Individuals - Male',
 'Sheltered Total Homeless Individuals - Transgender, 2016':'Sheltered Total Homeless Individuals - Transgender',
 'Sheltered Total Homeless Individuals - Non-Hispanic/Non-Latino, 2016':'Sheltered Total Homeless Individuals - Non-Hispanic/Non-Latino',
 'Sheltered Total Homeless Individuals - Hispanic/Latino, 2016':'Sheltered Total Homeless Individuals - Hispanic/Latino',
 'Sheltered Total Homeless Individuals - White, 2016':'Sheltered Total Homeless Individuals - White',
 'Sheltered Total Homeless Individuals - Black or African American, 2016':'Sheltered Total Homeless Individuals - Black or African American',
 'Sheltered Total Homeless Individuals - Asian, 2016':'Sheltered Total Homeless Individuals - Asian',
 'Sheltered Total Homeless Individuals - American Indian or Alaska Native, 2016':'Sheltered Total Homeless Individuals - American Indian or Alaska Native',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless Individuals - Multiple Races, 2016':'Sheltered Total Homeless Individuals - Multiple Races',
    
 'Unsheltered Homeless Individuals, 2016':'Unsheltered Homeless Individuals',
 'Unsheltered Homeless Individuals - Under 18, 2016':'Unsheltered Homeless Individuals - Under 18',
 'Unsheltered Homeless Individuals - Age 18 to 24, 2016':'Unsheltered Homeless Individuals - Age 18 to 24',
 'Unsheltered Homeless Individuals - Over 24, 2016':'Unsheltered Homeless Individuals - Over 24',
 'Unsheltered Homeless Individuals - Female, 2016':'Unsheltered Homeless Individuals - Female',
 'Unsheltered Homeless Individuals - Male, 2016':'Unsheltered Homeless Individuals - Male',
 'Unsheltered Homeless Individuals - Transgender, 2016':'Unsheltered Homeless Individuals - Transgender',
 'Unsheltered Homeless Individuals - Non-Hispanic/Non-Latino, 2016':'Unsheltered Homeless Individuals - Non-Hispanic/Non-Latino',
 'Unsheltered Homeless Individuals - Hispanic/Latino, 2016':'Unsheltered Homeless Individuals - Hispanic/Latino',
 'Unsheltered Homeless Individuals - White, 2016':'Unsheltered Homeless Individuals - White',
 'Unsheltered Homeless Individuals - Black or African American, 2016':'Unsheltered Homeless Individuals - Black or African American',
 'Unsheltered Homeless Individuals - Asian, 2016':'Unsheltered Homeless Individuals - Asian',
 'Unsheltered Homeless Individuals - American Indian or Alaska Native, 2016':'Unsheltered Homeless Individuals - American Indian or Alaska Native',
 'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander, 2016':'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless Individuals - Multiple Races, 2016':'Unsheltered Homeless Individuals - Multiple Races',
    
 'Overall Homeless People in Families, 2016':'Overall Homeless People in Families',
 'Overall Homeless People in Families - Under 18, 2016':'Overall Homeless People in Families - Under 18',
 'Overall Homeless People in Families - Age 18 to 24, 2016':'Overall Homeless People in Families - Age 18 to 24',
 'Overall Homeless People in Families - Over 24, 2016':'Overall Homeless People in Families - Over 24',
 'Overall Homeless People in Families - Female, 2016':'Overall Homeless People in Families',
 'Overall Homeless People in Families - Male, 2016':'Overall Homeless People in Families - Male',
 'Overall Homeless People in Families - Transgender, 2016':'Overall Homeless People in Families - Transgender',
 'Overall Homeless People in Families - Non-Hispanic/Non-Latino, 2016':'Overall Homeless People in Families - Non-Hispanic/Non-Latino',
 'Overall Homeless People in Families - Hispanic/Latino, 2016':'Overall Homeless People in Families - Hispanic/Latino',
 'Overall Homeless People in Families - White, 2016':'Overall Homeless People in Families - White',
 'Overall Homeless People in Families - Black or African American, 2016':'Overall Homeless People in Families - Black or African American',
 'Overall Homeless People in Families - Asian, 2016':'Overall Homeless People in Families - Asian',
 'Overall Homeless People in Families - American Indian or Alaska Native, 2016':'Overall Homeless People in Families - American Indian or Alaska Native',
 'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016':'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless People in Families - Multiple Races, 2016':'Overall Homeless People in Families - Multiple Races',
    
 'Sheltered ES Homeless People in Families, 2016':'Sheltered ES Homeless People in Families',
 'Sheltered ES Homeless People in Families - Under 18, 2016':'Sheltered ES Homeless People in Families - Under 18',
 'Sheltered ES Homeless People in Families - Age 18 to 24, 2016':'Sheltered ES Homeless People in Families - Age 18 to 24',
 'Sheltered ES Homeless People in Families - Over 24, 2016':'Sheltered ES Homeless People in Families - Over 24',
 'Sheltered ES Homeless People in Families - Female, 2016':'Sheltered ES Homeless People in Families - Female',
 'Sheltered ES Homeless People in Families - Male, 2016':'Sheltered ES Homeless People in Families - Male',
 'Sheltered ES Homeless People in Families - Transgender, 2016':'Sheltered ES Homeless People in Families - Transgender',
 'Sheltered ES Homeless People in Families - Non-Hispanic/Non-Latino, 2016':'Sheltered ES Homeless People in Families - Non-Hispanic/Non-Latino',
 'Sheltered ES Homeless People in Families - Hispanic/Latino, 2016':'Sheltered ES Homeless People in Families - Hispanic/Latino',
 'Sheltered ES Homeless People in Families - White, 2016':'Sheltered ES Homeless People in Families - White',
 'Sheltered ES Homeless People in Families - Black or African American, 2016':'Sheltered ES Homeless People in Families - Black or African American',
 'Sheltered ES Homeless People in Families - Asian, 2016':'Sheltered ES Homeless People in Families - Asian',
 'Sheltered ES Homeless People in Families - American Indian or Alaska Native, 2016':'Sheltered ES Homeless People in Families - American Indian or Alaska Native',
 'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless People in Families - Multiple Races, 2016':'Sheltered ES Homeless People in Families - Multiple Races',
    
 'Sheltered TH Homeless People in Families, 2016':'Sheltered TH Homeless People in Families',
 'Sheltered TH Homeless People in Families - Under 18, 2016':'Sheltered TH Homeless People in Families - Under 18',
 'Sheltered TH Homeless People in Families - Age 18 to 24, 2016':'Sheltered TH Homeless People in Families - Age 18 to 24',
 'Sheltered TH Homeless People in Families - Over 24, 2016':'Sheltered TH Homeless People in Families - Over 24',
 'Sheltered TH Homeless People in Families - Female, 2016':'Sheltered TH Homeless People in Families - Female',
 'Sheltered TH Homeless People in Families - Male, 2016':'Sheltered TH Homeless People in Families - Male',
 'Sheltered TH Homeless People in Families - Transgender, 2016':'Sheltered TH Homeless People in Families - Transgender',
 'Sheltered TH Homeless People in Families - Non-Hispanic/Non-Latino, 2016':'Sheltered TH Homeless People in Families - Non-Hispanic/Non-Latino',
 'Sheltered TH Homeless People in Families - Hispanic/Latino, 2016':'Sheltered TH Homeless People in Families - Hispanic/Latino',
 'Sheltered TH Homeless People in Families - White, 2016':'Sheltered TH Homeless People in Families - White',
 'Sheltered TH Homeless People in Families - Black or African American, 2016':'Sheltered TH Homeless People in Families - Black or African American',
 'Sheltered TH Homeless People in Families - Asian, 2016':'Sheltered TH Homeless People in Families - Asian',
 'Sheltered TH Homeless People in Families - American Indian or Alaska Native, 2016':'Sheltered TH Homeless People in Families - American Indian or Alaska Native',
 'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless People in Families - Multiple Races, 2016':'Sheltered TH Homeless People in Families - Multiple Races',
    
    
 'Sheltered Total Homeless People in Families, 2016':'Sheltered Total Homeless People in Families',
 'Sheltered Total Homeless People in Families - Under 18, 2016':'Sheltered Total Homeless People in Families - Under 18',
 'Sheltered Total Homeless People in Families - Age 18 to 24, 2016':'Sheltered Total Homeless People in Families - Age 18 to 24',
 'Sheltered Total Homeless People in Families - Over 24, 2016':'Sheltered Total Homeless People in Families - Over 24',
 'Sheltered Total Homeless People in Families - Female, 2016':'Sheltered Total Homeless People in Families - Female',
 'Sheltered Total Homeless People in Families - Male, 2016':'Sheltered Total Homeless People in Families - Male',
 'Sheltered Total Homeless People in Families - Transgender, 2016':'Sheltered Total Homeless People in Families - Transgender',
 'Sheltered Total Homeless People in Families - Non-Hispanic/Non-Latino, 2016':'Sheltered Total Homeless People in Families - Non-Hispanic/Non-Latino',
 'Sheltered Total Homeless People in Families - Hispanic/Latino, 2016':'Sheltered Total Homeless People in Families - Hispanic/Latino',
 'Sheltered Total Homeless People in Families - White, 2016':'Sheltered Total Homeless People in Families - White',
 'Sheltered Total Homeless People in Families - Black or African American, 2016':'Sheltered Total Homeless People in Families - Black or African American',
 'Sheltered Total Homeless People in Families - Asian, 2016':'Sheltered Total Homeless People in Families - Asian',
 'Sheltered Total Homeless People in Families - American Indian or Alaska Native, 2016':'Sheltered Total Homeless People in Families - American Indian or Alaska Native',
 'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless People in Families - Multiple Races, 2016':'Sheltered Total Homeless People in Families - Multiple Races',
    
 'Unsheltered Homeless People in Families, 2016':'Unsheltered Homeless People in Families',
 'Unsheltered Homeless People in Families - Under 18, 2016':'Unsheltered Homeless People in Families - Under 18',
 'Unsheltered Homeless People in Families - Age 18 to 24, 2016':'Unsheltered Homeless People in Families - Age 18 to 24',
 'Unsheltered Homeless People in Families - Over 24, 2016':'Unsheltered Homeless People in Families - Over 24',
 'Unsheltered Homeless People in Families - Female, 2016':'Unsheltered Homeless People in Families - Female',
 'Unsheltered Homeless People in Families - Male, 2016':'Unsheltered Homeless People in Families - Male',
 'Unsheltered Homeless People in Families - Transgender, 2016':'Unsheltered Homeless People in Families - Transgender',
 'Unsheltered Homeless People in Families - Non-Hispanic/Non-Latino, 2016':'Unsheltered Homeless People in Families - Non-Hispanic/Non-Latino',
 'Unsheltered Homeless People in Families - Hispanic/Latino, 2016':'Unsheltered Homeless People in Families - Hispanic/Latino',
 'Unsheltered Homeless People in Families - White, 2016':'Unsheltered Homeless People in Families - White',
 'Unsheltered Homeless People in Families - Black or African American, 2016':'Unsheltered Homeless People in Families - Black or African American',
 'Unsheltered Homeless People in Families - Asian, 2016':'Unsheltered Homeless People in Families - Asian',
 'Unsheltered Homeless People in Families - American Indian or Alaska Native, 2016':'Unsheltered Homeless People in Families - American Indian or Alaska Native',
 'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander, 2016':'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless People in Families - Multiple Races, 2016':'Unsheltered Homeless People in Families - Multiple Races',
    
 'Overall Homeless Family Households, 2016':'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households, 2016':'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households, 2016':'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households, 2016':'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households, 2016':'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless, 2016':'Overall Chronically Homeless',
 'Sheltered ES Chronically Homeless, 2016':'Sheltered ES Chronically Homeless',
 'Sheltered SH Chronically Homeless, 2016':'Sheltered SH Chronically Homeless',
 'Sheltered Total Chronically Homeless, 2016':'Sheltered Total Chronically Homeless',
 'Unsheltered Chronically Homeless, 2016':'Unsheltered Chronically Homeless',
 'Overall Chronically Homeless Individuals, 2016':'Overall Chronically Homeless Individuals',
 'Sheltered ES Chronically Homeless Individuals, 2016':'Sheltered ES Chronically Homeless Individuals',
 'Sheltered SH Chronically Homeless Individuals, 2016':'Sheltered SH Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals, 2016':'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals, 2016':'Unsheltered Chronically Homeless Individuals',
 'Overall Chronically Homeless People in Families, 2016':'Overall Chronically Homeless People in Families',
 'Sheltered ES Chronically Homeless People in Families, 2016':'Sheltered ES Chronically Homeless People in Families',
 'Sheltered Total Chronically Homeless People in Families, 2016':'Sheltered Total Chronically Homeless People in Families',
 'Unsheltered Chronically Homeless People in Families, 2016':'Unsheltered Chronically Homeless People in Families',
    
 'Overall Homeless Veterans, 2016':'Overall Homeless Veterans',
 'Overall Homeless Veterans - Female, 2016':'Overall Homeless Veterans - Female',
 'Overall Homeless Veterans - Male, 2016':'Overall Homeless Veterans - Male',
 'Overall Homeless Veterans - Transgender, 2016':'Overall Homeless Veterans - Transgender',
 'Overall Homeless Veterans - Non-Hispanic/Non-Latino, 2016':'Overall Homeless Veterans - Non-Hispanic/Non-Latino',
 'Overall Homeless Veterans - Hispanic/Latino, 2016':'Overall Homeless Veterans - Hispanic/Latino',
 'Overall Homeless Veterans - White, 2016':'Overall Homeless Veterans - White',
 'Overall Homeless Veterans - Black or African American, 2016':'Overall Homeless Veterans - Black or African American',
 'Overall Homeless Veterans - Asian, 2016':'Overall Homeless Veterans - Asian',
 'Overall Homeless Veterans - American Indian or Alaska Native, 2016':'Overall Homeless Veterans - American Indian or Alaska Native',
 'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016':'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless Veterans - Multiple Races, 2016':'Overall Homeless Veterans - Multiple Races',
    
 'Sheltered ES Homeless Veterans, 2016':'Sheltered ES Homeless Veterans',
 'Sheltered ES Homeless Veterans - Female, 2016':'Sheltered ES Homeless Veterans - Female',
 'Sheltered ES Homeless Veterans - Male, 2016':'Sheltered ES Homeless Veterans - Male',
 'Sheltered ES Homeless Veterans - Transgender, 2016':'Sheltered ES Homeless Veterans - Transgender',
 'Sheltered ES Homeless Veterans - Non-Hispanic/Non-Latino, 2016':'Sheltered ES Homeless Veterans - Non-Hispanic/Non-Latino',
 'Sheltered ES Homeless Veterans - Hispanic/Latino, 2016':'Sheltered ES Homeless Veterans - Hispanic/Latino',
 'Sheltered ES Homeless Veterans - White, 2016':'Sheltered ES Homeless Veterans - White',
 'Sheltered ES Homeless Veterans - Black or African American, 2016':'Sheltered ES Homeless Veterans - Black or African American',
 'Sheltered ES Homeless Veterans - Asian, 2016':'Sheltered ES Homeless Veterans - Asian',
 'Sheltered ES Homeless Veterans - American Indian or Alaska Native, 2016':'Sheltered ES Homeless Veterans - American Indian or Alaska Native',
 'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless Veterans - Multiple Races, 2016':'Sheltered ES Homeless Veterans - Multiple Races',
    
 'Sheltered TH Homeless Veterans, 2016':'Sheltered TH Homeless Veterans',
 'Sheltered TH Homeless Veterans - Female, 2016':'Sheltered TH Homeless Veterans - Female',
 'Sheltered TH Homeless Veterans - Male, 2016':'Sheltered TH Homeless Veterans - Male',
 'Sheltered TH Homeless Veterans - Transgender, 2016':'Sheltered TH Homeless Veterans - Transgender',
 'Sheltered TH Homeless Veterans - Non-Hispanic/Non-Latino, 2016':'Sheltered TH Homeless Veterans - Non-Hispanic/Non-Latino',
 'Sheltered TH Homeless Veterans - Hispanic/Latino, 2016':'Sheltered TH Homeless Veterans - Hispanic/Latino',
 'Sheltered TH Homeless Veterans - White, 2016':'Sheltered TH Homeless Veterans - White',
 'Sheltered TH Homeless Veterans - Black or African American, 2016':'Sheltered TH Homeless Veterans - Black or African American',
 'Sheltered TH Homeless Veterans - Asian, 2016':'Sheltered TH Homeless Veterans - Asian',
 'Sheltered TH Homeless Veterans - American Indian or Alaska Native, 2016':'Sheltered TH Homeless Veterans - American Indian or Alaska Native',
 'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless Veterans - Multiple Races, 2016':'Sheltered TH Homeless Veterans - Multiple Races',
    
 'Sheltered SH Homeless Veterans, 2016':'Sheltered SH Homeless Veterans',
 'Sheltered SH Homeless Veterans - Female, 2016':'Sheltered SH Homeless Veterans - Female',
 'Sheltered SH Homeless Veterans - Male, 2016':'Sheltered SH Homeless Veterans - Male',
 'Sheltered SH Homeless Veterans - Transgender, 2016':'Sheltered SH Homeless Veterans - Transgender',
 'Sheltered SH Homeless Veterans - Non-Hispanic/Non-Latino, 2016':'Sheltered SH Homeless Veterans - Non-Hispanic/Non-Latino',
 'Sheltered SH Homeless Veterans - Hispanic/Latino, 2016':'Sheltered SH Homeless Veterans - Hispanic/Latino',
 'Sheltered SH Homeless Veterans - White, 2016':'Sheltered SH Homeless Veterans - White',
 'Sheltered SH Homeless Veterans - Black or African American, 2016':'Sheltered SH Homeless Veterans - Black or African American',
 'Sheltered SH Homeless Veterans - Asian, 2016':'Sheltered SH Homeless Veterans - Asian',
 'Sheltered SH Homeless Veterans - American Indian or Alaska Native, 2016':'Sheltered SH Homeless Veterans - American Indian or Alaska Native',
 'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered SH Homeless Veterans - Multiple Races, 2016':'Sheltered SH Homeless Veterans - Multiple Races',
    
 'Sheltered Total Homeless Veterans, 2016':'Sheltered Total Homeless Veterans',
 'Sheltered Total Homeless Veterans - Female, 2016':'Sheltered Total Homeless Veterans - Female',
 'Sheltered Total Homeless Veterans - Male, 2016':'Sheltered Total Homeless Veterans - Male',
 'Sheltered Total Homeless Veterans - Transgender, 2016':'Sheltered Total Homeless Veterans - Transgender',
 'Sheltered Total Homeless Veterans - Non-Hispanic/Non-Latino, 2016':'Sheltered Total Homeless Veterans - Non-Hispanic/Non-Latino',
 'Sheltered Total Homeless Veterans - Hispanic/Latino, 2016':'Sheltered Total Homeless Veterans - Hispanic/Latino',
 'Sheltered Total Homeless Veterans - White, 2016':'Sheltered Total Homeless Veterans - White',
 'Sheltered Total Homeless Veterans - Black or African American, 2016':'Sheltered Total Homeless Veterans - Black or African American',
 'Sheltered Total Homeless Veterans - Asian, 2016':'Sheltered Total Homeless Veterans - Asian',
 'Sheltered Total Homeless Veterans - American Indian or Alaska Native, 2016':'Sheltered Total Homeless Veterans - American Indian or Alaska Native',
 'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016':'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless Veterans - Multiple Races, 2016':'Sheltered Total Homeless Veterans - Multiple Races',
    
 'Unsheltered Homeless Veterans, 2016':'Unsheltered Homeless Veterans',
 'Unsheltered Homeless Veterans - Female, 2016':'Unsheltered Homeless Veterans - Female',
 'Unsheltered Homeless Veterans - Male, 2016':'Unsheltered Homeless Veterans - Male',
 'Unsheltered Homeless Veterans - Transgender, 2016':'Unsheltered Homeless Veterans - Transgender',
 'Unsheltered Homeless Veterans - Non-Hispanic/Non-Latino, 2016':'Unsheltered Homeless Veterans - Non-Hispanic/Non-Latino',
 'Unsheltered Homeless Veterans - Hispanic/Latino, 2016':'Unsheltered Homeless Veterans - Hispanic/Latino',
 'Unsheltered Homeless Veterans - White, 2016':'Unsheltered Homeless Veterans - White',
 'Unsheltered Homeless Veterans - Black or African American, 2016':'Unsheltered Homeless Veterans - Black or African American',
 'Unsheltered Homeless Veterans - Asian, 2016':'Unsheltered Homeless Veterans - Asian',
 'Unsheltered Homeless Veterans - American Indian or Alaska Native, 2016':'Unsheltered Homeless Veterans - American Indian or Alaska Native',
 'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander, 2016':'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless Veterans - Multiple Races, 2016':'Unsheltered Homeless Veterans - Multiple Races',
    
 'Overall Homeless Unaccompanied Youth (Under 25), 2016':'Overall Homeless Unaccompanied Youth (Under 25)',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25), 2016':'Sheltered ES Homeless Unaccompanied Youth (Under 25)',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25), 2016':'Sheltered TH Homeless Unaccompanied Youth (Under 25)',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25), 2016':'Sheltered SH Homeless Unaccompanied Youth (Under 25)',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25), 2016':'Sheltered Total Homeless Unaccompanied Youth (Under 25)',
 'Unsheltered Homeless Unaccompanied Youth (Under 25), 2016':'Unsheltered Homeless Unaccompanied Youth (Under 25)',
 'Overall Homeless Unaccompanied Youth Under 18, 2016':'Overall Homeless Unaccompanied Youth Under 18',
 'Sheltered ES Homeless Unaccompanied Youth Under 18, 2016':'Sheltered ES Homeless Unaccompanied Youth Under 18',
 'Sheltered TH Homeless Unaccompanied Youth Under 18, 2016':'Sheltered TH Homeless Unaccompanied Youth Under 18',
 'Sheltered SH Homeless Unaccompanied Youth Under 18, 2016':'Sheltered SH Homeless Unaccompanied Youth Under 18',
 'Sheltered Total Homeless Unaccompanied Youth Under 18, 2016':'Sheltered Total Homeless Unaccompanied Youth Under 18',
 'Unsheltered Homeless Unaccompanied Youth Under 18, 2016':'Unsheltered Homeless Unaccompanied Youth Under 18',
 'Overall Homeless Unaccompanied Youth Age 18-24, 2016':'Overall Homeless Unaccompanied Youth Age 18-24',
 'Sheltered ES Homeless Unaccompanied Youth Age 18-24, 2016':'Sheltered ES Homeless Unaccompanied Youth Age 18-24',
 'Sheltered TH Homeless Unaccompanied Youth Age 18-24, 2016':'Sheltered TH Homeless Unaccompanied Youth Age 18-24',
 'Sheltered SH Homeless Unaccompanied Youth Age 18-24, 2016':'Sheltered SH Homeless Unaccompanied Youth Age 18-24',
 'Sheltered Total Homeless Unaccompanied Youth Age 18-24, 2016':'Sheltered Total Homeless Unaccompanied Youth Age 18-24',
 'Unsheltered Homeless Unaccompanied Youth Age 18-24, 2016':'Unsheltered Homeless Unaccompanied Youth Age 18-24',
 'Overall Homeless Parenting Youth (Under 25), 2016':'Overall Homeless Parenting Youth (Under 25)',
 'Sheltered ES Homeless Parenting Youth (Under 25), 2016':'Sheltered ES Homeless Parenting Youth (Under 25)',
 'Sheltered TH Homeless Parenting Youth (Under 25), 2016':'Sheltered TH Homeless Parenting Youth (Under 25)',
 'Sheltered Total Homeless Parenting Youth (Under 25), 2016':'Sheltered Total Homeless Parenting Youth (Under 25)',
 'Unsheltered Homeless Parenting Youth (Under 25), 2016':'Unsheltered Homeless Parenting Youth (Under 25)',
 'Overall Homeless Parenting Youth Under 18, 2016':'Overall Homeless Parenting Youth Under 18',
 'Sheltered ES Homeless Parenting Youth Under 18, 2016':'Sheltered ES Homeless Parenting Youth Under 18',
 'Sheltered TH Homeless Parenting Youth Under 18, 2016':'Sheltered TH Homeless Parenting Youth Under 18',
 'Sheltered Total Homeless Parenting Youth Under 18, 2016':'Sheltered Total Homeless Parenting Youth Under 18',
 'Unsheltered Homeless Parenting Youth Under 18, 2016':'Unsheltered Homeless Parenting Youth Under 18',
 'Overall Homeless Parenting Youth Age 18-24, 2016':'Overall Homeless Parenting Youth Age 18-24',
 'Sheltered ES Homeless Parenting Youth Age 18-24, 2016':'Sheltered ES Homeless Parenting Youth Age 18-24',
 'Sheltered TH Homeless Parenting Youth Age 18-24, 2016':'Sheltered TH Homeless Parenting Youth Age 18-24',
 'Sheltered Total Homeless Parenting Youth Age 18-24, 2016':'Sheltered Total Homeless Parenting Youth Age 18-24',
 'Unsheltered Homeless Parenting Youth Age 18-24, 2016':'Unsheltered Homeless Parenting Youth Age 18-24',
 'Overall Homeless Children of Parenting Youth, 2016':'Overall Homeless Children of Parenting Youth',
 'Sheltered ES Homeless Children of Parenting Youth, 2016':'Sheltered ES Homeless Children of Parenting Youth',
 'Sheltered TH Homeless Children of Parenting Youth, 2016':'Sheltered TH Homeless Children of Parenting Youth',
 'Sheltered Total Homeless Children of Parenting Youth, 2016':'Sheltered Total Homeless Children of Parenting Youth',
 'Unsheltered Homeless Children of Parenting Youth, 2016': 'Unsheltered Homeless Children of Parenting Youth'
       }
data_2016_df.rename(columns=dict, inplace=True)

In [127]:
data_2016_df.head()

,State,Year,Number of CoCs,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK,2016,2.0,"1,940",274,173,"1,493",808,"1,127",5,...,9,2,7,9,0,10,2,8,10,0
1,AL,2016,8.0,"4,111",681,304,"3,126","1,733","2,366",12,...,26,14,6,20,6,45,22,17,39,6
2,AR,2016,7.0,"2,463",432,197,"1,834","1,047","1,415",1,...,13,12,1,13,0,13,12,1,13,0
3,AS,2016,0.0,,,,,,,,...,,,,,,,,,,
4,AZ,2016,3.0,"9,707","2,022",733,"6,952","3,685","6,005",17,...,149,69,80,149,0,222,96,126,222,0

In [128]:
# Export df to sql table
data_2016_df.to_sql(name='data_2016', con=engine, if_exists='replace')